///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ADSAutomationPhaseIII.TC_10573
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TC10573Repo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("9a93b08d-33d3-4a42-9f3c-d94cf12500c7")]
    public partial class TC10573Repo : RepoGenBaseFolder
    {
        static TC10573Repo instance = new TC10573Repo();
        TC10573RepoFolders.ServersListAppFolder _serverslist;
        TC10573RepoFolders.DataStudioAppFolder _datastudio;
        TC10573RepoFolders.FileModifiedAppFolder _filemodified;
        TC10573RepoFolders.QueryWindowAppFolder _querywindow;

        /// <summary>
        /// Gets the singleton class instance representing the TC10573Repo element repository.
        /// </summary>
        [RepositoryFolder("9a93b08d-33d3-4a42-9f3c-d94cf12500c7")]
        public static TC10573Repo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TC10573Repo() 
            : base("TC10573Repo", "/", null, 0, false, "9a93b08d-33d3-4a42-9f3c-d94cf12500c7", ".\\RepositoryImages\\TC10573Repo9a93b08d.rximgres")
        {
            _serverslist = new TC10573RepoFolders.ServersListAppFolder(this);
            _datastudio = new TC10573RepoFolders.DataStudioAppFolder(this);
            _filemodified = new TC10573RepoFolders.FileModifiedAppFolder(this);
            _querywindow = new TC10573RepoFolders.QueryWindowAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("9a93b08d-33d3-4a42-9f3c-d94cf12500c7")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ServersList folder.
        /// </summary>
        [RepositoryFolder("074e9ce7-9035-4f66-9c1e-6128b4f5101b")]
        public virtual TC10573RepoFolders.ServersListAppFolder ServersList
        {
            get { return _serverslist; }
        }

        /// <summary>
        /// The DataStudio folder.
        /// </summary>
        [RepositoryFolder("9c477525-7dd9-45a1-95e8-4a1c88d023f3")]
        public virtual TC10573RepoFolders.DataStudioAppFolder DataStudio
        {
            get { return _datastudio; }
        }

        /// <summary>
        /// The FileModified folder.
        /// </summary>
        [RepositoryFolder("e023f516-9d72-4d93-987f-b52734da129a")]
        public virtual TC10573RepoFolders.FileModifiedAppFolder FileModified
        {
            get { return _filemodified; }
        }

        /// <summary>
        /// The QueryWindow folder.
        /// </summary>
        [RepositoryFolder("1c014b3c-4015-4732-8361-e38970e9ec66")]
        public virtual TC10573RepoFolders.QueryWindowAppFolder QueryWindow
        {
            get { return _querywindow; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class TC10573RepoFolders
    {
        /// <summary>
        /// The ServersListAppFolder folder.
        /// </summary>
        [RepositoryFolder("074e9ce7-9035-4f66-9c1e-6128b4f5101b")]
        public partial class ServersListAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _localdbserverstreeitemInfo;
            RepoItemInfo _mongodbInfo;
            RepoItemInfo _queryboxInfo;
            RepoItemInfo _fluidshellwindowInfo;

            /// <summary>
            /// Creates a new ServersList  folder.
            /// </summary>
            public ServersListAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ServersList", "/form[@title~'^Aqua Data Studio']", parentFolder, 30000, null, true, "074e9ce7-9035-4f66-9c1e-6128b4f5101b", "")
            {
                _localdbserverstreeitemInfo = new RepoItemInfo(this, "LocalDBServersTreeItem", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//container[@name='viewport']/tree[@name='schemaTree']/?/?/treeitem[@text='Local Database Servers']", 30000, null, "0f6e214a-25ee-4eaa-81ac-a97c7eb5ef44");
                _mongodbInfo = new RepoItemInfo(this, "MongoDB", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^MongoDB\\ 172\\.24\\.1\\.155\\ v3\\.4']", 30000, null, "769b3f88-1245-4b5e-8f23-fe0e56a76ed6");
                _queryboxInfo = new RepoItemInfo(this, "QueryBox", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myInnerComponent']//container[@type='QueryPanel']/container[@name='panel']/?/?/container[@name='splitPane']//container[@type='EditorImpl$MyScrollPane']/container[6]/element[@type='EditorComponentImpl']", 30000, null, "953a742b-3728-4080-b6f9-3b7ff87b5364");
                _fluidshellwindowInfo = new RepoItemInfo(this, "FluidShellWindow", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//container[@type='TerminalMongoPanelView']//element[@name='screen']", 30000, null, "b5661195-dcf4-401d-b540-1b42fd865bc6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("074e9ce7-9035-4f66-9c1e-6128b4f5101b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("074e9ce7-9035-4f66-9c1e-6128b4f5101b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LocalDBServersTreeItem item.
            /// </summary>
            [RepositoryItem("0f6e214a-25ee-4eaa-81ac-a97c7eb5ef44")]
            public virtual Ranorex.TreeItem LocalDBServersTreeItem
            {
                get
                {
                    return _localdbserverstreeitemInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The LocalDBServersTreeItem item info.
            /// </summary>
            [RepositoryItemInfo("0f6e214a-25ee-4eaa-81ac-a97c7eb5ef44")]
            public virtual RepoItemInfo LocalDBServersTreeItemInfo
            {
                get
                {
                    return _localdbserverstreeitemInfo;
                }
            }

            /// <summary>
            /// The MongoDB item.
            /// </summary>
            [RepositoryItem("769b3f88-1245-4b5e-8f23-fe0e56a76ed6")]
            public virtual Ranorex.TreeItem MongoDB
            {
                get
                {
                    return _mongodbInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The MongoDB item info.
            /// </summary>
            [RepositoryItemInfo("769b3f88-1245-4b5e-8f23-fe0e56a76ed6")]
            public virtual RepoItemInfo MongoDBInfo
            {
                get
                {
                    return _mongodbInfo;
                }
            }

            /// <summary>
            /// The QueryBox item.
            /// </summary>
            [RepositoryItem("953a742b-3728-4080-b6f9-3b7ff87b5364")]
            public virtual Ranorex.Unknown QueryBox
            {
                get
                {
                    return _queryboxInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The QueryBox item info.
            /// </summary>
            [RepositoryItemInfo("953a742b-3728-4080-b6f9-3b7ff87b5364")]
            public virtual RepoItemInfo QueryBoxInfo
            {
                get
                {
                    return _queryboxInfo;
                }
            }

            /// <summary>
            /// The FluidShellWindow item.
            /// </summary>
            [RepositoryItem("b5661195-dcf4-401d-b540-1b42fd865bc6")]
            public virtual Ranorex.Unknown FluidShellWindow
            {
                get
                {
                    return _fluidshellwindowInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The FluidShellWindow item info.
            /// </summary>
            [RepositoryItemInfo("b5661195-dcf4-401d-b540-1b42fd865bc6")]
            public virtual RepoItemInfo FluidShellWindowInfo
            {
                get
                {
                    return _fluidshellwindowInfo;
                }
            }
        }

        /// <summary>
        /// The DataStudioAppFolder folder.
        /// </summary>
        [RepositoryFolder("9c477525-7dd9-45a1-95e8-4a1c88d023f3")]
        public partial class DataStudioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _mongojsInfo;
            RepoItemInfo _mongoshellInfo;

            /// <summary>
            /// Creates a new DataStudio  folder.
            /// </summary>
            public DataStudioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DataStudio", "/form[@processname='datastudio']", parentFolder, 30000, null, true, "9c477525-7dd9-45a1-95e8-4a1c88d023f3", "")
            {
                _mongojsInfo = new RepoItemInfo(this, "MongoJS", ".//menuitem[@text='Query Analyzer (MongoJS)']", 30000, null, "fd4999c7-a39e-4448-9fb0-dfbc5f50b040");
                _mongoshellInfo = new RepoItemInfo(this, "MongoShell", ".//menuitem[@text='MongoShell']", 30000, null, "6ef4b840-adf8-4e7c-9655-0b68b76fc3f6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9c477525-7dd9-45a1-95e8-4a1c88d023f3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9c477525-7dd9-45a1-95e8-4a1c88d023f3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MongoJS item.
            /// </summary>
            [RepositoryItem("fd4999c7-a39e-4448-9fb0-dfbc5f50b040")]
            public virtual Ranorex.MenuItem MongoJS
            {
                get
                {
                    return _mongojsInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MongoJS item info.
            /// </summary>
            [RepositoryItemInfo("fd4999c7-a39e-4448-9fb0-dfbc5f50b040")]
            public virtual RepoItemInfo MongoJSInfo
            {
                get
                {
                    return _mongojsInfo;
                }
            }

            /// <summary>
            /// The MongoShell item.
            /// </summary>
            [RepositoryItem("6ef4b840-adf8-4e7c-9655-0b68b76fc3f6")]
            public virtual Ranorex.MenuItem MongoShell
            {
                get
                {
                    return _mongoshellInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MongoShell item info.
            /// </summary>
            [RepositoryItemInfo("6ef4b840-adf8-4e7c-9655-0b68b76fc3f6")]
            public virtual RepoItemInfo MongoShellInfo
            {
                get
                {
                    return _mongoshellInfo;
                }
            }
        }

        /// <summary>
        /// The FileModifiedAppFolder folder.
        /// </summary>
        [RepositoryFolder("e023f516-9d72-4d93-987f-b52734da129a")]
        public partial class FileModifiedAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _discardbuttonInfo;

            /// <summary>
            /// Creates a new FileModified  folder.
            /// </summary>
            public FileModifiedAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FileModified", "/form[@title='File Modified']", parentFolder, 30000, null, true, "e023f516-9d72-4d93-987f-b52734da129a", "")
            {
                _discardbuttonInfo = new RepoItemInfo(this, "DiscardButton", ".//container[@name='OptionPane.buttonArea']/button[@text='Discard']", 30000, null, "2f6a6708-f14b-4f61-b831-60b96d7c607d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e023f516-9d72-4d93-987f-b52734da129a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e023f516-9d72-4d93-987f-b52734da129a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DiscardButton item.
            /// </summary>
            [RepositoryItem("2f6a6708-f14b-4f61-b831-60b96d7c607d")]
            public virtual Ranorex.Button DiscardButton
            {
                get
                {
                    return _discardbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DiscardButton item info.
            /// </summary>
            [RepositoryItemInfo("2f6a6708-f14b-4f61-b831-60b96d7c607d")]
            public virtual RepoItemInfo DiscardButtonInfo
            {
                get
                {
                    return _discardbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The QueryWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("1c014b3c-4015-4732-8361-e38970e9ec66")]
        public partial class QueryWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _newInfo;
            RepoItemInfo _queryboxInfo;

            /// <summary>
            /// Creates a new QueryWindow  folder.
            /// </summary>
            public QueryWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("QueryWindow", "/form[@title~'^Aqua\\ Data\\ Studio\\ \\[Untitle']", parentFolder, 30000, null, true, "1c014b3c-4015-4732-8361-e38970e9ec66", "")
            {
                _newInfo = new RepoItemInfo(this, "New", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//container[@type='QueryPanel']//container[@name='editorToolBar']/button[1]", 30000, null, "0ad584d7-99ac-4d77-aac7-08c83be02ed5");
                _queryboxInfo = new RepoItemInfo(this, "QueryBox", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myInnerComponent']//container[@type='QueryPanel']/container[@name='panel']/?/?/container[@name='splitPane']//container[@type='LoadingDecorator$MyLayeredPane']/container[@type='JPanel']/container[@type='JPanel']/container[@type='EditorImpl$MyScrollPane']/container[6]/element[@type='EditorComponentImpl']", 30000, null, "68718b9d-f07f-4b4f-814c-a093104b90b8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1c014b3c-4015-4732-8361-e38970e9ec66")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1c014b3c-4015-4732-8361-e38970e9ec66")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The New item.
            /// </summary>
            [RepositoryItem("0ad584d7-99ac-4d77-aac7-08c83be02ed5")]
            public virtual Ranorex.Button New
            {
                get
                {
                    return _newInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The New item info.
            /// </summary>
            [RepositoryItemInfo("0ad584d7-99ac-4d77-aac7-08c83be02ed5")]
            public virtual RepoItemInfo NewInfo
            {
                get
                {
                    return _newInfo;
                }
            }

            /// <summary>
            /// The QueryBox item.
            /// </summary>
            [RepositoryItem("68718b9d-f07f-4b4f-814c-a093104b90b8")]
            public virtual Ranorex.Unknown QueryBox
            {
                get
                {
                    return _queryboxInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The QueryBox item info.
            /// </summary>
            [RepositoryItemInfo("68718b9d-f07f-4b4f-814c-a093104b90b8")]
            public virtual RepoItemInfo QueryBoxInfo
            {
                get
                {
                    return _queryboxInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}