///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ADSAutomationPhaseIII.TC_10570
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TC10570Repo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("9a72e597-9b08-4844-adde-bf2726cace5a")]
    public partial class TC10570Repo : RepoGenBaseFolder
    {
        static TC10570Repo instance = new TC10570Repo();
        TC10570RepoFolders.ApplicationAppFolder _application;
        TC10570RepoFolders.DatastudioAppFolder _datastudio;
        TC10570RepoFolders.OptionsAppFolder _options;
        TC10570RepoFolders.FileMenuAppFolder _filemenu;
        TC10570RepoFolders.DropdownSelection_QueryPanelAppFolder _dropdownselection_querypanel;
        TC10570RepoFolders.LookupAppFolder _lookup;
        TC10570RepoFolders.CloseQueryPanelpopupAppFolder _closequerypanelpopup;
        TC10570RepoFolders.Copy_of_OptionsAppFolder _copy_of_options;
        TC10570RepoFolders.QueryPanelAppFolder _querypanel;
        TC10570RepoFolders.DropDatabaseAppFolder _dropdatabase;
        TC10570RepoFolders.CreatedDBExistsAppFolder _createddbexists;
        TC10570RepoFolders.CreateDatabaseAppFolder _createdatabase;

        /// <summary>
        /// Gets the singleton class instance representing the TC10570Repo element repository.
        /// </summary>
        [RepositoryFolder("9a72e597-9b08-4844-adde-bf2726cace5a")]
        public static TC10570Repo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TC10570Repo() 
            : base("TC10570Repo", "/", null, 0, false, "9a72e597-9b08-4844-adde-bf2726cace5a", ".\\RepositoryImages\\TC10570Repo9a72e597.rximgres")
        {
            _application = new TC10570RepoFolders.ApplicationAppFolder(this);
            _datastudio = new TC10570RepoFolders.DatastudioAppFolder(this);
            _options = new TC10570RepoFolders.OptionsAppFolder(this);
            _filemenu = new TC10570RepoFolders.FileMenuAppFolder(this);
            _dropdownselection_querypanel = new TC10570RepoFolders.DropdownSelection_QueryPanelAppFolder(this);
            _lookup = new TC10570RepoFolders.LookupAppFolder(this);
            _closequerypanelpopup = new TC10570RepoFolders.CloseQueryPanelpopupAppFolder(this);
            _copy_of_options = new TC10570RepoFolders.Copy_of_OptionsAppFolder(this);
            _querypanel = new TC10570RepoFolders.QueryPanelAppFolder(this);
            _dropdatabase = new TC10570RepoFolders.DropDatabaseAppFolder(this);
            _createddbexists = new TC10570RepoFolders.CreatedDBExistsAppFolder(this);
            _createdatabase = new TC10570RepoFolders.CreateDatabaseAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("9a72e597-9b08-4844-adde-bf2726cace5a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Application folder.
        /// </summary>
        [RepositoryFolder("d54a3fac-3b92-4b4a-9c2b-770fb3053792")]
        public virtual TC10570RepoFolders.ApplicationAppFolder Application
        {
            get { return _application; }
        }

        /// <summary>
        /// The Datastudio folder.
        /// </summary>
        [RepositoryFolder("f91c2511-0a1a-4be8-a8a7-09023121563d")]
        public virtual TC10570RepoFolders.DatastudioAppFolder Datastudio
        {
            get { return _datastudio; }
        }

        /// <summary>
        /// The Options folder.
        /// </summary>
        [RepositoryFolder("cf1f1a18-8f1c-4719-9e41-bcc0e522dd35")]
        public virtual TC10570RepoFolders.OptionsAppFolder Options
        {
            get { return _options; }
        }

        /// <summary>
        /// The FileMenu folder.
        /// </summary>
        [RepositoryFolder("f8882a9b-8f0d-4632-a459-567435ae8c2a")]
        public virtual TC10570RepoFolders.FileMenuAppFolder FileMenu
        {
            get { return _filemenu; }
        }

        /// <summary>
        /// The DropdownSelection_QueryPanel folder.
        /// </summary>
        [RepositoryFolder("df24f824-4535-4551-9339-bfd9a5d40d50")]
        public virtual TC10570RepoFolders.DropdownSelection_QueryPanelAppFolder DropdownSelection_QueryPanel
        {
            get { return _dropdownselection_querypanel; }
        }

        /// <summary>
        /// The Lookup folder.
        /// </summary>
        [RepositoryFolder("e6168ddd-34ac-430c-a07b-571303d188dd")]
        public virtual TC10570RepoFolders.LookupAppFolder Lookup
        {
            get { return _lookup; }
        }

        /// <summary>
        /// The CloseQueryPanelpopup folder.
        /// </summary>
        [RepositoryFolder("e14df672-d378-45a0-ba5d-2211f8070d72")]
        public virtual TC10570RepoFolders.CloseQueryPanelpopupAppFolder CloseQueryPanelpopup
        {
            get { return _closequerypanelpopup; }
        }

        /// <summary>
        /// The Copy_of_Options folder.
        /// </summary>
        [RepositoryFolder("1308850b-0513-4da4-a644-f37436837bfe")]
        public virtual TC10570RepoFolders.Copy_of_OptionsAppFolder Copy_of_Options
        {
            get { return _copy_of_options; }
        }

        /// <summary>
        /// The QueryPanel folder.
        /// </summary>
        [RepositoryFolder("076ece9d-0d14-4451-9730-237611e809fc")]
        public virtual TC10570RepoFolders.QueryPanelAppFolder QueryPanel
        {
            get { return _querypanel; }
        }

        /// <summary>
        /// The DropDatabase folder.
        /// </summary>
        [RepositoryFolder("d1a83459-57d8-4611-8c5c-132336ee3647")]
        public virtual TC10570RepoFolders.DropDatabaseAppFolder DropDatabase
        {
            get { return _dropdatabase; }
        }

        /// <summary>
        /// The CreatedDBExists folder.
        /// </summary>
        [RepositoryFolder("ddc4dd4a-1430-4d31-af10-42291e2fde85")]
        public virtual TC10570RepoFolders.CreatedDBExistsAppFolder CreatedDBExists
        {
            get { return _createddbexists; }
        }

        /// <summary>
        /// The CreateDatabase folder.
        /// </summary>
        [RepositoryFolder("dc649592-998b-4bd1-a17a-461a3d6f8ce1")]
        public virtual TC10570RepoFolders.CreateDatabaseAppFolder CreateDatabase
        {
            get { return _createdatabase; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class TC10570RepoFolders
    {
        /// <summary>
        /// The ApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("d54a3fac-3b92-4b4a-9c2b-770fb3053792")]
        public partial class ApplicationAppFolder : RepoGenBaseFolder
        {
            TC10570RepoFolders.CreateDatabasePanelFolder _createdatabasepanel;
            RepoItemInfo _filemenuInfo;
            RepoItemInfo _mongodbserverlistInfo;
            SelectQueryPaneInfoClass _selectquerypaneInfo;

            /// <summary>
            /// Creates a new Application  folder.
            /// </summary>
            public ApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Application", "/form[@title~'^Aqua\\ Data\\ Studio']", parentFolder, 30000, null, true, "d54a3fac-3b92-4b4a-9c2b-770fb3053792", "")
            {
                _createdatabasepanel = new TC10570RepoFolders.CreateDatabasePanelFolder(this);
                _filemenuInfo = new RepoItemInfo(this, "FileMenu", ".//menuitem[@text='File']", 30000, null, "da992c0f-dfcc-4c8a-a60b-60218253b432");
                _mongodbserverlistInfo = new RepoItemInfo(this, "MongoDBServerlist", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^MongoDB\\ 172\\.24\\.1\\.155\\ v3\\.4']", 30000, null, "c32a1335-02c2-4351-9aaf-24155c3eed88");
                _selectquerypaneInfo = new SelectQueryPaneInfoClass(this);
            }

            /// <summary>
            /// The SelectQueryPaneInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("00b2bfb6-6e12-4974-a4d8-08a42233c812")]
            public class SelectQueryPaneInfoClass : RepoItemInfo
            {
                /// <summary>
                /// SelectQueryPaneInfoClass class constructor.
                /// </summary>
                public SelectQueryPaneInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "SelectQueryPane", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//container[@type='QueryPanel']//container[@name='splitPane']//container[@name='_gridResultsView']/?/?/container[@accessiblename='select * from ads_Collection']", 30000, null, "00b2bfb6-6e12-4974-a4d8-08a42233c812")
                { }

                /// <summary>
                /// Gets the QueryExecuted item image.
                /// </summary>
                /// <returns>The QueryExecuted image.</returns>
                [RepositoryImage("97602de8-cda6-4288-98da-2bb1afa2a04d")]
                public CompressedImage GetQueryExecuted()
                {
                    return GetImage("97602de8-cda6-4288-98da-2bb1afa2a04d");
                }

                /// <summary>
                /// Gets the QueryExecuted item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("97602de8-cda6-4288-98da-2bb1afa2a04d")]
                public CompressedImage GetQueryExecuted(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("97602de8-cda6-4288-98da-2bb1afa2a04d", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d54a3fac-3b92-4b4a-9c2b-770fb3053792")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d54a3fac-3b92-4b4a-9c2b-770fb3053792")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FileMenu item.
            /// </summary>
            [RepositoryItem("da992c0f-dfcc-4c8a-a60b-60218253b432")]
            public virtual Ranorex.MenuItem FileMenu
            {
                get
                {
                    return _filemenuInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The FileMenu item info.
            /// </summary>
            [RepositoryItemInfo("da992c0f-dfcc-4c8a-a60b-60218253b432")]
            public virtual RepoItemInfo FileMenuInfo
            {
                get
                {
                    return _filemenuInfo;
                }
            }

            /// <summary>
            /// The MongoDBServerlist item.
            /// </summary>
            [RepositoryItem("c32a1335-02c2-4351-9aaf-24155c3eed88")]
            public virtual Ranorex.TreeItem MongoDBServerlist
            {
                get
                {
                    return _mongodbserverlistInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The MongoDBServerlist item info.
            /// </summary>
            [RepositoryItemInfo("c32a1335-02c2-4351-9aaf-24155c3eed88")]
            public virtual RepoItemInfo MongoDBServerlistInfo
            {
                get
                {
                    return _mongodbserverlistInfo;
                }
            }

            /// <summary>
            /// The SelectQueryPane item.
            /// </summary>
            [RepositoryItem("00b2bfb6-6e12-4974-a4d8-08a42233c812")]
            public virtual Ranorex.Container SelectQueryPane
            {
                get
                {
                    return _selectquerypaneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SelectQueryPane item info.
            /// </summary>
            [RepositoryItemInfo("00b2bfb6-6e12-4974-a4d8-08a42233c812")]
            public virtual SelectQueryPaneInfoClass SelectQueryPaneInfo
            {
                get
                {
                    return _selectquerypaneInfo;
                }
            }

            /// <summary>
            /// The CreateDatabasePanel folder.
            /// </summary>
            [RepositoryFolder("84735de7-20c4-4d89-bc29-de923d38240d")]
            public virtual TC10570RepoFolders.CreateDatabasePanelFolder CreateDatabasePanel
            {
                get { return _createdatabasepanel; }
            }
        }

        /// <summary>
        /// The CreateDatabasePanelFolder folder.
        /// </summary>
        [RepositoryFolder("84735de7-20c4-4d89-bc29-de923d38240d")]
        public partial class CreateDatabasePanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _collectionsnameInfo;
            RepoItemInfo _databasenameInfo;
            RepoItemInfo _databasesInfo;
            RepoItemInfo _createdbbuttonInfo;
            RepoItemInfo _querypaneldropdownarrowInfo;
            RepoItemInfo _dorpnewdbInfo;
            RepoItemInfo _adsdbnewInfo;
            RepoItemInfo _createdatabaseInfo;

            /// <summary>
            /// Creates a new CreateDatabasePanel  folder.
            /// </summary>
            public CreateDatabasePanelFolder(RepoGenBaseFolder parentFolder) :
                    base("CreateDatabasePanel", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']", parentFolder, 30000, null, false, "84735de7-20c4-4d89-bc29-de923d38240d", "")
            {
                _collectionsnameInfo = new RepoItemInfo(this, "CollectionsName", "?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//container[@type='CommonSchemaTab$8']/?/?/container[@accessiblename='General   ']/container[2]/?/?/text[@name='_mongoCollNameField']", 30000, null, "efaa5bb8-3e24-4a47-8063-a6faa519a2c3");
                _databasenameInfo = new RepoItemInfo(this, "DatabaseName", "?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//container[@type='CommonSchemaTab$8']/?/?/container[@accessiblename='General   ']/container[2]/?/?/text[@name='nameField']", 30000, null, "0c352df3-cd2a-4eab-b41b-2b5252eb47f6");
                _databasesInfo = new RepoItemInfo(this, "Databases", "container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^MongoDB\\ 172\\.24\\.1\\.155\\ v3\\.4']/treeitem[@text='Databases']", 30000, null, "0f562a69-b6ee-4405-9e1f-8342ebb64052");
                _createdbbuttonInfo = new RepoItemInfo(this, "CreateDBButton", "?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//container[@type='CommonSchemaTab$8']//button[@text='Create']", 30000, null, "0117683d-f123-4f28-a7d0-7f9c2aead11c");
                _querypaneldropdownarrowInfo = new RepoItemInfo(this, "QueryPanelDropdownarrow", "?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//container[@type='QueryPanel']//container[@name='panelBar']//combobox[@name='databaseField']/button[@text='']", 30000, null, "a8ce86fb-949d-4d66-b454-aceff99bcb58");
                _dorpnewdbInfo = new RepoItemInfo(this, "DorpnewDB", "container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^MongoDB\\ 172\\.24\\.1\\.155\\ v3\\.4']/?/?/treeitem[@text='ads_db']", 30000, null, "5bce1020-1cd1-46fd-9f1a-3c5e537bc28f");
                _adsdbnewInfo = new RepoItemInfo(this, "AdsDBNew", "container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'MongoDB 172.24.1.155 v3.4.1']/?/?/treeitem[@text='ads_DBNew']", 30000, null, "c969a298-7e81-4840-a036-b963927b0c28");
                _createdatabaseInfo = new RepoItemInfo(this, "CreateDatabase", "?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//tabpage[@title='Create: Database']", 30000, null, "f9a2590b-f779-4727-8f31-ba2417e557c9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("84735de7-20c4-4d89-bc29-de923d38240d")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("84735de7-20c4-4d89-bc29-de923d38240d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CollectionsName item.
            /// </summary>
            [RepositoryItem("efaa5bb8-3e24-4a47-8063-a6faa519a2c3")]
            public virtual Ranorex.Text CollectionsName
            {
                get
                {
                    return _collectionsnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CollectionsName item info.
            /// </summary>
            [RepositoryItemInfo("efaa5bb8-3e24-4a47-8063-a6faa519a2c3")]
            public virtual RepoItemInfo CollectionsNameInfo
            {
                get
                {
                    return _collectionsnameInfo;
                }
            }

            /// <summary>
            /// The DatabaseName item.
            /// </summary>
            [RepositoryItem("0c352df3-cd2a-4eab-b41b-2b5252eb47f6")]
            public virtual Ranorex.Text DatabaseName
            {
                get
                {
                    return _databasenameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The DatabaseName item info.
            /// </summary>
            [RepositoryItemInfo("0c352df3-cd2a-4eab-b41b-2b5252eb47f6")]
            public virtual RepoItemInfo DatabaseNameInfo
            {
                get
                {
                    return _databasenameInfo;
                }
            }

            /// <summary>
            /// The Databases item.
            /// </summary>
            [RepositoryItem("0f562a69-b6ee-4405-9e1f-8342ebb64052")]
            public virtual Ranorex.TreeItem Databases
            {
                get
                {
                    return _databasesInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Databases item info.
            /// </summary>
            [RepositoryItemInfo("0f562a69-b6ee-4405-9e1f-8342ebb64052")]
            public virtual RepoItemInfo DatabasesInfo
            {
                get
                {
                    return _databasesInfo;
                }
            }

            /// <summary>
            /// The CreateDBButton item.
            /// </summary>
            [RepositoryItem("0117683d-f123-4f28-a7d0-7f9c2aead11c")]
            public virtual Ranorex.Button CreateDBButton
            {
                get
                {
                    return _createdbbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CreateDBButton item info.
            /// </summary>
            [RepositoryItemInfo("0117683d-f123-4f28-a7d0-7f9c2aead11c")]
            public virtual RepoItemInfo CreateDBButtonInfo
            {
                get
                {
                    return _createdbbuttonInfo;
                }
            }

            /// <summary>
            /// The QueryPanelDropdownarrow item.
            /// </summary>
            [RepositoryItem("a8ce86fb-949d-4d66-b454-aceff99bcb58")]
            public virtual Ranorex.Button QueryPanelDropdownarrow
            {
                get
                {
                    return _querypaneldropdownarrowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The QueryPanelDropdownarrow item info.
            /// </summary>
            [RepositoryItemInfo("a8ce86fb-949d-4d66-b454-aceff99bcb58")]
            public virtual RepoItemInfo QueryPanelDropdownarrowInfo
            {
                get
                {
                    return _querypaneldropdownarrowInfo;
                }
            }

            /// <summary>
            /// The DorpnewDB item.
            /// </summary>
            [RepositoryItem("5bce1020-1cd1-46fd-9f1a-3c5e537bc28f")]
            public virtual Ranorex.TreeItem DorpnewDB
            {
                get
                {
                    return _dorpnewdbInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The DorpnewDB item info.
            /// </summary>
            [RepositoryItemInfo("5bce1020-1cd1-46fd-9f1a-3c5e537bc28f")]
            public virtual RepoItemInfo DorpnewDBInfo
            {
                get
                {
                    return _dorpnewdbInfo;
                }
            }

            /// <summary>
            /// The AdsDBNew item.
            /// </summary>
            [RepositoryItem("c969a298-7e81-4840-a036-b963927b0c28")]
            public virtual Ranorex.TreeItem AdsDBNew
            {
                get
                {
                    return _adsdbnewInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The AdsDBNew item info.
            /// </summary>
            [RepositoryItemInfo("c969a298-7e81-4840-a036-b963927b0c28")]
            public virtual RepoItemInfo AdsDBNewInfo
            {
                get
                {
                    return _adsdbnewInfo;
                }
            }

            /// <summary>
            /// The CreateDatabase item.
            /// </summary>
            [RepositoryItem("f9a2590b-f779-4727-8f31-ba2417e557c9")]
            public virtual Ranorex.TabPage CreateDatabase
            {
                get
                {
                    return _createdatabaseInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The CreateDatabase item info.
            /// </summary>
            [RepositoryItemInfo("f9a2590b-f779-4727-8f31-ba2417e557c9")]
            public virtual RepoItemInfo CreateDatabaseInfo
            {
                get
                {
                    return _createdatabaseInfo;
                }
            }
        }

        /// <summary>
        /// The DatastudioAppFolder folder.
        /// </summary>
        [RepositoryFolder("f91c2511-0a1a-4be8-a8a7-09023121563d")]
        public partial class DatastudioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _optionsInfo;
            RepoItemInfo _mongosqlInfo;
            RepoItemInfo _mongojsInfo;
            RepoItemInfo _queryanalyzerInfo;
            RepoItemInfo _createdatabaseInfo;
            RepoItemInfo _dbcreatedInfo;
            RepoItemInfo _testdbcreatedInfo;
            RepoItemInfo _adsdbdropdownInfo;
            RepoItemInfo _tomdbdropdownInfo;
            RepoItemInfo _closeInfo;
            RepoItemInfo _dropdatabaseInfo;

            /// <summary>
            /// Creates a new Datastudio  folder.
            /// </summary>
            public DatastudioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Datastudio", "/form[@class='SunAwtWindow']", parentFolder, 30000, null, false, "f91c2511-0a1a-4be8-a8a7-09023121563d", "")
            {
                _optionsInfo = new RepoItemInfo(this, "Options", "?/?/menuitem[@text='Options']", 30000, null, "70f3219a-48de-4f5d-aeca-a758cf2ff59c");
                _mongosqlInfo = new RepoItemInfo(this, "MongoSQL", ".//container[@name='viewport']/list[@name='ComboBox.list']/listitem[@text='MongoSQL']", 30000, null, "a7ab4a46-c570-4ce8-983f-38b85b518da4");
                _mongojsInfo = new RepoItemInfo(this, "MongoJS", ".//container[@name='viewport']/list[@name='ComboBox.list']/listitem[@text='MongoJS']", 30000, null, "552ba23a-d589-4149-82f5-971777ca8287");
                _queryanalyzerInfo = new RepoItemInfo(this, "QueryAnalyzer", "?/?/menuitem[@text='Query Analyzer']", 30000, null, "7b90a9f1-0d30-4afd-91e4-62294668ed6b");
                _createdatabaseInfo = new RepoItemInfo(this, "CreateDatabase", "?/?/menuitem[@text='Create Database']", 30000, null, "ce2cb9de-2984-4a46-8046-6a2d4e0ec3cb");
                _dbcreatedInfo = new RepoItemInfo(this, "DBCreated", ".//container[@name='viewport']/list[@name='ComboBox.list']/listitem[@text='ads_DBNew']", 30000, null, "7bc69cf3-f7f1-4934-b205-ca77a1723324");
                _testdbcreatedInfo = new RepoItemInfo(this, "TestDBCreated", ".//container[@name='viewport']/list[@name='ComboBox.list']/listitem[@text='NewData']", 30000, null, "4c66f90b-a11a-4a88-a34c-c79a29c98053");
                _adsdbdropdownInfo = new RepoItemInfo(this, "AdsDbDropdown", ".//container[@name='viewport']/list[@name='ComboBox.list']/listitem[@text='ads_db']", 30000, null, "e001041d-e749-4ac1-a162-7e2cceca96e8");
                _tomdbdropdownInfo = new RepoItemInfo(this, "TomDBDropdown", ".//container[@name='viewport']/list[@name='ComboBox.list']/listitem[@text='tom']", 30000, null, "43a8175c-f905-4c23-91d8-5dd7e6e9f8cf");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/menuitem[@name='TabDocumentPane.close']", 30000, null, "2e00e64d-e94a-4d08-8de5-ea147e42b315");
                _dropdatabaseInfo = new RepoItemInfo(this, "DropDatabase", "?/?/menuitem[@text='Drop Database']", 30000, null, "fa68bc3c-17b9-4eb4-9753-35c810e09c1d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f91c2511-0a1a-4be8-a8a7-09023121563d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f91c2511-0a1a-4be8-a8a7-09023121563d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Options item.
            /// </summary>
            [RepositoryItem("70f3219a-48de-4f5d-aeca-a758cf2ff59c")]
            public virtual Ranorex.MenuItem Options
            {
                get
                {
                    return _optionsInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Options item info.
            /// </summary>
            [RepositoryItemInfo("70f3219a-48de-4f5d-aeca-a758cf2ff59c")]
            public virtual RepoItemInfo OptionsInfo
            {
                get
                {
                    return _optionsInfo;
                }
            }

            /// <summary>
            /// The MongoSQL item.
            /// </summary>
            [RepositoryItem("a7ab4a46-c570-4ce8-983f-38b85b518da4")]
            public virtual Ranorex.ListItem MongoSQL
            {
                get
                {
                    return _mongosqlInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The MongoSQL item info.
            /// </summary>
            [RepositoryItemInfo("a7ab4a46-c570-4ce8-983f-38b85b518da4")]
            public virtual RepoItemInfo MongoSQLInfo
            {
                get
                {
                    return _mongosqlInfo;
                }
            }

            /// <summary>
            /// The MongoJS item.
            /// </summary>
            [RepositoryItem("552ba23a-d589-4149-82f5-971777ca8287")]
            public virtual Ranorex.ListItem MongoJS
            {
                get
                {
                    return _mongojsInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The MongoJS item info.
            /// </summary>
            [RepositoryItemInfo("552ba23a-d589-4149-82f5-971777ca8287")]
            public virtual RepoItemInfo MongoJSInfo
            {
                get
                {
                    return _mongojsInfo;
                }
            }

            /// <summary>
            /// The QueryAnalyzer item.
            /// </summary>
            [RepositoryItem("7b90a9f1-0d30-4afd-91e4-62294668ed6b")]
            public virtual Ranorex.MenuItem QueryAnalyzer
            {
                get
                {
                    return _queryanalyzerInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The QueryAnalyzer item info.
            /// </summary>
            [RepositoryItemInfo("7b90a9f1-0d30-4afd-91e4-62294668ed6b")]
            public virtual RepoItemInfo QueryAnalyzerInfo
            {
                get
                {
                    return _queryanalyzerInfo;
                }
            }

            /// <summary>
            /// The CreateDatabase item.
            /// </summary>
            [RepositoryItem("ce2cb9de-2984-4a46-8046-6a2d4e0ec3cb")]
            public virtual Ranorex.MenuItem CreateDatabase
            {
                get
                {
                    return _createdatabaseInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The CreateDatabase item info.
            /// </summary>
            [RepositoryItemInfo("ce2cb9de-2984-4a46-8046-6a2d4e0ec3cb")]
            public virtual RepoItemInfo CreateDatabaseInfo
            {
                get
                {
                    return _createdatabaseInfo;
                }
            }

            /// <summary>
            /// The DBCreated item.
            /// </summary>
            [RepositoryItem("7bc69cf3-f7f1-4934-b205-ca77a1723324")]
            public virtual Ranorex.ListItem DBCreated
            {
                get
                {
                    return _dbcreatedInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The DBCreated item info.
            /// </summary>
            [RepositoryItemInfo("7bc69cf3-f7f1-4934-b205-ca77a1723324")]
            public virtual RepoItemInfo DBCreatedInfo
            {
                get
                {
                    return _dbcreatedInfo;
                }
            }

            /// <summary>
            /// The TestDBCreated item.
            /// </summary>
            [RepositoryItem("4c66f90b-a11a-4a88-a34c-c79a29c98053")]
            public virtual Ranorex.ListItem TestDBCreated
            {
                get
                {
                    return _testdbcreatedInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The TestDBCreated item info.
            /// </summary>
            [RepositoryItemInfo("4c66f90b-a11a-4a88-a34c-c79a29c98053")]
            public virtual RepoItemInfo TestDBCreatedInfo
            {
                get
                {
                    return _testdbcreatedInfo;
                }
            }

            /// <summary>
            /// The AdsDbDropdown item.
            /// </summary>
            [RepositoryItem("e001041d-e749-4ac1-a162-7e2cceca96e8")]
            public virtual Ranorex.ListItem AdsDbDropdown
            {
                get
                {
                    return _adsdbdropdownInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The AdsDbDropdown item info.
            /// </summary>
            [RepositoryItemInfo("e001041d-e749-4ac1-a162-7e2cceca96e8")]
            public virtual RepoItemInfo AdsDbDropdownInfo
            {
                get
                {
                    return _adsdbdropdownInfo;
                }
            }

            /// <summary>
            /// The TomDBDropdown item.
            /// </summary>
            [RepositoryItem("43a8175c-f905-4c23-91d8-5dd7e6e9f8cf")]
            public virtual Ranorex.ListItem TomDBDropdown
            {
                get
                {
                    return _tomdbdropdownInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The TomDBDropdown item info.
            /// </summary>
            [RepositoryItemInfo("43a8175c-f905-4c23-91d8-5dd7e6e9f8cf")]
            public virtual RepoItemInfo TomDBDropdownInfo
            {
                get
                {
                    return _tomdbdropdownInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("2e00e64d-e94a-4d08-8de5-ea147e42b315")]
            public virtual Ranorex.MenuItem Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("2e00e64d-e94a-4d08-8de5-ea147e42b315")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The DropDatabase item.
            /// </summary>
            [RepositoryItem("fa68bc3c-17b9-4eb4-9753-35c810e09c1d")]
            public virtual Ranorex.MenuItem DropDatabase
            {
                get
                {
                    return _dropdatabaseInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The DropDatabase item info.
            /// </summary>
            [RepositoryItemInfo("fa68bc3c-17b9-4eb4-9753-35c810e09c1d")]
            public virtual RepoItemInfo DropDatabaseInfo
            {
                get
                {
                    return _dropdatabaseInfo;
                }
            }
        }

        /// <summary>
        /// The OptionsAppFolder folder.
        /// </summary>
        [RepositoryFolder("cf1f1a18-8f1c-4719-9e41-bcc0e522dd35")]
        public partial class OptionsAppFolder : RepoGenBaseFolder
        {
            TC10570RepoFolders.MenuOptionsFolder _menuoptions;
            RepoItemInfo _defaultsyntaxbuttInfo;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _autocompletioncheckboxInfo;
            RepoItemInfo _autocompletioncheckboxcheckedInfo;
            RepoItemInfo _mongosqlInfo;
            RepoItemInfo _mongojsInfo;

            /// <summary>
            /// Creates a new Options  folder.
            /// </summary>
            public OptionsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Options", "/form[@title='Options']", parentFolder, 30000, null, false, "cf1f1a18-8f1c-4719-9e41-bcc0e522dd35", "")
            {
                _menuoptions = new TC10570RepoFolders.MenuOptionsFolder(this);
                _defaultsyntaxbuttInfo = new RepoItemInfo(this, "DefaultSyntaxButt", "container[1]/?/?/container[@name='mySplitter']/container[3]/?/?/container[@name='myContent']//container[@type='JideSplitPane']//container[@type='JBScrollPane']//table[@name='table']/combobox[@type='AQComboBoxOptionEditor$AQComboBoxTableRendererEditor$1']/button[@text='']", 30000, null, "407a5f37-bbc7-4eb8-8f0c-54d20091d37d");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "container[2]/container[@type='JPanel']//button[@text='OK']", 30000, null, "63291711-1a62-4316-8a10-44dcd4148d3d");
                _autocompletioncheckboxInfo = new RepoItemInfo(this, "AutoCompletionCheckbox", "container[1]/?/?/container[@name='mySplitter']/container[3]/?/?/container[@name='myContent']//container[@type='JideSplitPane']/container[1]/?/?/container[@type='JBScrollPane']/container[1]/table[@name='table']/checkbox[@text='']", 30000, null, "9f4ed480-54db-4f82-a461-3ae2163b702b");
                _autocompletioncheckboxcheckedInfo = new RepoItemInfo(this, "AutoCompletionCheckboxChecked", "container[1]/?/?/container[@name='mySplitter']/container[3]/?/?/container[@name='myContent']//container[@type='JideSplitPane']/container[1]/?/?/container[@type='JBScrollPane']/container[1]/table[@name='table']/row[@index='1']/cell[@text='true']", 30000, null, "88f789ee-5804-487d-bfb3-59f077e588a2");
                _mongosqlInfo = new RepoItemInfo(this, "MongoSQL", "container[1]/?/?/container[@name='mySplitter']/container[3]/?/?/container[@name='myContent']//container[@type='JideSplitPane']//container[@type='JBScrollPane']//row//cell[@text='Default Syntax']/../cell[2]", 30000, null, "a7aff6d2-dbcf-4113-b59e-3d8a3e9e3b7f");
                _mongojsInfo = new RepoItemInfo(this, "MongoJS", "container[1]/?/?/container[@name='mySplitter']/container[3]/?/?/container[@name='myContent']/element/container[3]//container[@name='propertyTable']/container[@type='JBScrollPane']/container[1]/table[@name='table']/row[@index='5']/cell[@text='MongoJS']", 30000, null, "b5068667-ed46-426e-8fd2-95555b189071");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cf1f1a18-8f1c-4719-9e41-bcc0e522dd35")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cf1f1a18-8f1c-4719-9e41-bcc0e522dd35")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DefaultSyntaxButt item.
            /// </summary>
            [RepositoryItem("407a5f37-bbc7-4eb8-8f0c-54d20091d37d")]
            public virtual Ranorex.Button DefaultSyntaxButt
            {
                get
                {
                    return _defaultsyntaxbuttInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DefaultSyntaxButt item info.
            /// </summary>
            [RepositoryItemInfo("407a5f37-bbc7-4eb8-8f0c-54d20091d37d")]
            public virtual RepoItemInfo DefaultSyntaxButtInfo
            {
                get
                {
                    return _defaultsyntaxbuttInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("63291711-1a62-4316-8a10-44dcd4148d3d")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("63291711-1a62-4316-8a10-44dcd4148d3d")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The AutoCompletionCheckbox item.
            /// </summary>
            [RepositoryItem("9f4ed480-54db-4f82-a461-3ae2163b702b")]
            public virtual Ranorex.CheckBox AutoCompletionCheckbox
            {
                get
                {
                    return _autocompletioncheckboxInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The AutoCompletionCheckbox item info.
            /// </summary>
            [RepositoryItemInfo("9f4ed480-54db-4f82-a461-3ae2163b702b")]
            public virtual RepoItemInfo AutoCompletionCheckboxInfo
            {
                get
                {
                    return _autocompletioncheckboxInfo;
                }
            }

            /// <summary>
            /// The AutoCompletionCheckboxChecked item.
            /// </summary>
            [RepositoryItem("88f789ee-5804-487d-bfb3-59f077e588a2")]
            public virtual Ranorex.Cell AutoCompletionCheckboxChecked
            {
                get
                {
                    return _autocompletioncheckboxcheckedInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The AutoCompletionCheckboxChecked item info.
            /// </summary>
            [RepositoryItemInfo("88f789ee-5804-487d-bfb3-59f077e588a2")]
            public virtual RepoItemInfo AutoCompletionCheckboxCheckedInfo
            {
                get
                {
                    return _autocompletioncheckboxcheckedInfo;
                }
            }

            /// <summary>
            /// The MongoSQL item.
            /// </summary>
            [RepositoryItem("a7aff6d2-dbcf-4113-b59e-3d8a3e9e3b7f")]
            public virtual Ranorex.Cell MongoSQL
            {
                get
                {
                    return _mongosqlInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The MongoSQL item info.
            /// </summary>
            [RepositoryItemInfo("a7aff6d2-dbcf-4113-b59e-3d8a3e9e3b7f")]
            public virtual RepoItemInfo MongoSQLInfo
            {
                get
                {
                    return _mongosqlInfo;
                }
            }

            /// <summary>
            /// The MongoJS item.
            /// </summary>
            [RepositoryItem("b5068667-ed46-426e-8fd2-95555b189071")]
            public virtual Ranorex.Cell MongoJS
            {
                get
                {
                    return _mongojsInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The MongoJS item info.
            /// </summary>
            [RepositoryItemInfo("b5068667-ed46-426e-8fd2-95555b189071")]
            public virtual RepoItemInfo MongoJSInfo
            {
                get
                {
                    return _mongojsInfo;
                }
            }

            /// <summary>
            /// The MenuOptions folder.
            /// </summary>
            [RepositoryFolder("54f3fbce-e3c9-4e57-a6dc-513ca531ce22")]
            public virtual TC10570RepoFolders.MenuOptionsFolder MenuOptions
            {
                get { return _menuoptions; }
            }
        }

        /// <summary>
        /// The MenuOptionsFolder folder.
        /// </summary>
        [RepositoryFolder("54f3fbce-e3c9-4e57-a6dc-513ca531ce22")]
        public partial class MenuOptionsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _options_queryanalyserInfo;
            RepoItemInfo _mangodbsqlInfo;

            /// <summary>
            /// Creates a new MenuOptions  folder.
            /// </summary>
            public MenuOptionsFolder(RepoGenBaseFolder parentFolder) :
                    base("MenuOptions", "container[1]/?/?/container[@name='mySplitter']//container[@type='SettingsTreeView$2']/tree[@name='myTree']", parentFolder, 30000, null, false, "54f3fbce-e3c9-4e57-a6dc-513ca531ce22", "")
            {
                _options_queryanalyserInfo = new RepoItemInfo(this, "Options_QueryAnalyser", "treeitem/treeitem[14]", 30000, null, "0880e11b-2944-42a7-9891-c6c4628e0559");
                _mangodbsqlInfo = new RepoItemInfo(this, "MangoDBSQL", "treeitem/treeitem[14]/treeitem[19]", 30000, null, "6dbae1b7-896a-4923-8e77-5c51c623fda3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("54f3fbce-e3c9-4e57-a6dc-513ca531ce22")]
            public virtual Ranorex.Tree Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("54f3fbce-e3c9-4e57-a6dc-513ca531ce22")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Options_QueryAnalyser item.
            /// </summary>
            [RepositoryItem("0880e11b-2944-42a7-9891-c6c4628e0559")]
            public virtual Ranorex.TreeItem Options_QueryAnalyser
            {
                get
                {
                    return _options_queryanalyserInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Options_QueryAnalyser item info.
            /// </summary>
            [RepositoryItemInfo("0880e11b-2944-42a7-9891-c6c4628e0559")]
            public virtual RepoItemInfo Options_QueryAnalyserInfo
            {
                get
                {
                    return _options_queryanalyserInfo;
                }
            }

            /// <summary>
            /// The MangoDBSQL item.
            /// </summary>
            [RepositoryItem("6dbae1b7-896a-4923-8e77-5c51c623fda3")]
            public virtual Ranorex.TreeItem MangoDBSQL
            {
                get
                {
                    return _mangodbsqlInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The MangoDBSQL item info.
            /// </summary>
            [RepositoryItemInfo("6dbae1b7-896a-4923-8e77-5c51c623fda3")]
            public virtual RepoItemInfo MangoDBSQLInfo
            {
                get
                {
                    return _mangodbsqlInfo;
                }
            }
        }

        /// <summary>
        /// The FileMenuAppFolder folder.
        /// </summary>
        [RepositoryFolder("f8882a9b-8f0d-4632-a459-567435ae8c2a")]
        public partial class FileMenuAppFolder : RepoGenBaseFolder
        {
            TC10570RepoFolders.MyFirstComponentFolder _myfirstcomponent;
            RepoItemInfo _mongodbInfo;
            RepoItemInfo _mongodb172241155v341Info;
            RepoItemInfo _editorcomponentimplInfo;
            RepoItemInfo _mycontentInfo;
            RepoItemInfo _querytextareaInfo;
            RepoItemInfo _executebuttonInfo;
            RepoItemInfo _editorcomponentimpl1Info;
            RepoItemInfo _queryeditorInfo;
            RepoItemInfo _selectads_dbInfo;
            RepoItemInfo _selecttom_dbInfo;
            RepoItemInfo _editormangodbInfo;
            RepoItemInfo _querytextvalidateInfo;
            RepoItemInfo _tabpage_querypanelInfo;

            /// <summary>
            /// Creates a new FileMenu  folder.
            /// </summary>
            public FileMenuAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FileMenu", "/form[@title~'^Aqua\\ Data\\ Studio\\ \\[Untitle']", parentFolder, 30000, null, true, "f8882a9b-8f0d-4632-a459-567435ae8c2a", "")
            {
                _myfirstcomponent = new TC10570RepoFolders.MyFirstComponentFolder(this);
                _mongodbInfo = new RepoItemInfo(this, "MongoDB", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='MongoDB 172.24.1.155 v3.4.1']", 30000, null, "b6276824-2f74-47c1-bec8-03feb5710c9a");
                _mongodb172241155v341Info = new RepoItemInfo(this, "MongoDB172241155V341", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^MongoDB\\ 172\\.24\\.1\\.155\\ v3\\.4']", 30000, null, "7fdabd5b-ce95-48e6-ae34-6642ee4d58ad");
                _editorcomponentimplInfo = new RepoItemInfo(this, "EditorComponentImpl", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myInnerComponent']/?/?/container[@accessiblename='@MongoDB 172.24.1.155 v3.4.1 [Untitled 2]']/container[3]/container[@name='panel']/?/?/container[@name='splitPane']//container[@type='EditorImpl$MyScrollPane']/container[6]/element[@type='EditorComponentImpl']", 30000, null, "5ea24e0f-1928-4042-b6c1-a05a9d2430a2");
                _mycontentInfo = new RepoItemInfo(this, "MyContent", "container[@name='myContent']", 30000, null, "8e29deee-a259-4adc-8ced-e99b52d53e36");
                _querytextareaInfo = new RepoItemInfo(this, "QueryTextArea", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myInnerComponent']//container[@type='QueryPanel']/container[@name='panel']/?/?/container[@name='splitPane']//container[@type='EditorImpl$MyScrollPane']/container[6]/element[@type='EditorComponentImpl']", 30000, null, "6fbf87f8-0a2e-436c-8a45-a3ab4e12e8fb");
                _executebuttonInfo = new RepoItemInfo(this, "ExecuteButton", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//container[@type='QueryPanel']//container[@name='toolBar']/button[@name='executeButton']", 30000, null, "4bc1d460-79cd-4669-b1b4-3231840f527a");
                _editorcomponentimpl1Info = new RepoItemInfo(this, "EditorComponentImpl1", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//container[@type='QueryPanel']//container[@name='splitPane']//container[@name='_theTextResultMessageComponent']/?/?/container[@type='EditorImpl$MyScrollPane']/container[1]/element[@type='EditorComponentImpl']", 30000, null, "0f246225-bfce-47d3-9354-cf90abe832c5");
                _queryeditorInfo = new RepoItemInfo(this, "QueryEditor", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myInnerComponent']//container[@type='QueryPanel']/container[@name='panel']/?/?/container[@name='splitPane']//container[@type='LoadingDecorator$MyLayeredPane']/container[@type='JPanel']/container[@type='JPanel']/container[@type='EditorImpl$MyScrollPane']/container[6]/element[@type='EditorComponentImpl']", 30000, null, "58a051eb-0dd3-46a7-bde2-e5d8963ade68");
                _selectads_dbInfo = new RepoItemInfo(this, "SelectADS_DB", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^MongoDB\\ 172\\.24\\.1\\.155\\ v3\\.4']/?/?/treeitem[@text='ads_db']", 30000, null, "33dda679-9a88-484a-a22b-fe4563ca508e");
                _selecttom_dbInfo = new RepoItemInfo(this, "SelectTom_DB", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^MongoDB\\ 172\\.24\\.1\\.155\\ v3\\.4']/?/?/treeitem[@text='tom']", 30000, null, "69ae0be1-d22c-4045-8814-f7bf9b948f52");
                _editormangodbInfo = new RepoItemInfo(this, "EditorMangoDB", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myInnerComponent']//container[@type='QueryPanel']/container[@name='panel']/?/?/container[@name='splitPane']//container[@type='EditorImpl$MyScrollPane']/container[6]/element[@type='EditorComponentImpl']", 30000, null, "b4a5ad40-e3d1-4ea1-b833-3871403b09d8");
                _querytextvalidateInfo = new RepoItemInfo(this, "QueryTextValidate", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//container[@type='QueryPanel']/container[@name='panel']/?/?/container[@name='splitPane']/?/?/container[@name='tabbedPane']/container[@name='_gridResultsView']//container[@type='ResultSetTableView$ResultGridsSplitPane']//container[@type='HorizontalLayoutPanel']/container[@type='JPanel']/text[@caption~'^\\ 0\\ record']", 30000, null, "51197da5-5c1d-4132-87bf-a62e45d9c5c9");
                _tabpage_querypanelInfo = new RepoItemInfo(this, "TabPage_QueryPanel", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']//container[@type='PlatDockingContentPanel']//tabpage[@title~'^@MongoDB\\ 172\\.24\\.1\\.155\\ v3\\.']", 30000, null, "6874654b-512e-4f05-a513-b1d62404b35c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f8882a9b-8f0d-4632-a459-567435ae8c2a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f8882a9b-8f0d-4632-a459-567435ae8c2a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MongoDB item.
            /// </summary>
            [RepositoryItem("b6276824-2f74-47c1-bec8-03feb5710c9a")]
            public virtual Ranorex.TreeItem MongoDB
            {
                get
                {
                    return _mongodbInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The MongoDB item info.
            /// </summary>
            [RepositoryItemInfo("b6276824-2f74-47c1-bec8-03feb5710c9a")]
            public virtual RepoItemInfo MongoDBInfo
            {
                get
                {
                    return _mongodbInfo;
                }
            }

            /// <summary>
            /// The MongoDB172241155V341 item.
            /// </summary>
            [RepositoryItem("7fdabd5b-ce95-48e6-ae34-6642ee4d58ad")]
            public virtual Ranorex.TreeItem MongoDB172241155V341
            {
                get
                {
                    return _mongodb172241155v341Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The MongoDB172241155V341 item info.
            /// </summary>
            [RepositoryItemInfo("7fdabd5b-ce95-48e6-ae34-6642ee4d58ad")]
            public virtual RepoItemInfo MongoDB172241155V341Info
            {
                get
                {
                    return _mongodb172241155v341Info;
                }
            }

            /// <summary>
            /// The EditorComponentImpl item.
            /// </summary>
            [RepositoryItem("5ea24e0f-1928-4042-b6c1-a05a9d2430a2")]
            public virtual Ranorex.Unknown EditorComponentImpl
            {
                get
                {
                    return _editorcomponentimplInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The EditorComponentImpl item info.
            /// </summary>
            [RepositoryItemInfo("5ea24e0f-1928-4042-b6c1-a05a9d2430a2")]
            public virtual RepoItemInfo EditorComponentImplInfo
            {
                get
                {
                    return _editorcomponentimplInfo;
                }
            }

            /// <summary>
            /// The MyContent item.
            /// </summary>
            [RepositoryItem("8e29deee-a259-4adc-8ced-e99b52d53e36")]
            public virtual Ranorex.Container MyContent
            {
                get
                {
                    return _mycontentInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The MyContent item info.
            /// </summary>
            [RepositoryItemInfo("8e29deee-a259-4adc-8ced-e99b52d53e36")]
            public virtual RepoItemInfo MyContentInfo
            {
                get
                {
                    return _mycontentInfo;
                }
            }

            /// <summary>
            /// The QueryTextArea item.
            /// </summary>
            [RepositoryItem("6fbf87f8-0a2e-436c-8a45-a3ab4e12e8fb")]
            public virtual Ranorex.Unknown QueryTextArea
            {
                get
                {
                    return _querytextareaInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The QueryTextArea item info.
            /// </summary>
            [RepositoryItemInfo("6fbf87f8-0a2e-436c-8a45-a3ab4e12e8fb")]
            public virtual RepoItemInfo QueryTextAreaInfo
            {
                get
                {
                    return _querytextareaInfo;
                }
            }

            /// <summary>
            /// The ExecuteButton item.
            /// </summary>
            [RepositoryItem("4bc1d460-79cd-4669-b1b4-3231840f527a")]
            public virtual Ranorex.Button ExecuteButton
            {
                get
                {
                    return _executebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ExecuteButton item info.
            /// </summary>
            [RepositoryItemInfo("4bc1d460-79cd-4669-b1b4-3231840f527a")]
            public virtual RepoItemInfo ExecuteButtonInfo
            {
                get
                {
                    return _executebuttonInfo;
                }
            }

            /// <summary>
            /// The EditorComponentImpl1 item.
            /// </summary>
            [RepositoryItem("0f246225-bfce-47d3-9354-cf90abe832c5")]
            public virtual Ranorex.Unknown EditorComponentImpl1
            {
                get
                {
                    return _editorcomponentimpl1Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The EditorComponentImpl1 item info.
            /// </summary>
            [RepositoryItemInfo("0f246225-bfce-47d3-9354-cf90abe832c5")]
            public virtual RepoItemInfo EditorComponentImpl1Info
            {
                get
                {
                    return _editorcomponentimpl1Info;
                }
            }

            /// <summary>
            /// The QueryEditor item.
            /// </summary>
            [RepositoryItem("58a051eb-0dd3-46a7-bde2-e5d8963ade68")]
            public virtual Ranorex.Unknown QueryEditor
            {
                get
                {
                    return _queryeditorInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The QueryEditor item info.
            /// </summary>
            [RepositoryItemInfo("58a051eb-0dd3-46a7-bde2-e5d8963ade68")]
            public virtual RepoItemInfo QueryEditorInfo
            {
                get
                {
                    return _queryeditorInfo;
                }
            }

            /// <summary>
            /// The SelectADS_DB item.
            /// </summary>
            [RepositoryItem("33dda679-9a88-484a-a22b-fe4563ca508e")]
            public virtual Ranorex.TreeItem SelectADS_DB
            {
                get
                {
                    return _selectads_dbInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The SelectADS_DB item info.
            /// </summary>
            [RepositoryItemInfo("33dda679-9a88-484a-a22b-fe4563ca508e")]
            public virtual RepoItemInfo SelectADS_DBInfo
            {
                get
                {
                    return _selectads_dbInfo;
                }
            }

            /// <summary>
            /// The SelectTom_DB item.
            /// </summary>
            [RepositoryItem("69ae0be1-d22c-4045-8814-f7bf9b948f52")]
            public virtual Ranorex.TreeItem SelectTom_DB
            {
                get
                {
                    return _selecttom_dbInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The SelectTom_DB item info.
            /// </summary>
            [RepositoryItemInfo("69ae0be1-d22c-4045-8814-f7bf9b948f52")]
            public virtual RepoItemInfo SelectTom_DBInfo
            {
                get
                {
                    return _selecttom_dbInfo;
                }
            }

            /// <summary>
            /// The EditorMangoDB item.
            /// </summary>
            [RepositoryItem("b4a5ad40-e3d1-4ea1-b833-3871403b09d8")]
            public virtual Ranorex.Unknown EditorMangoDB
            {
                get
                {
                    return _editormangodbInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The EditorMangoDB item info.
            /// </summary>
            [RepositoryItemInfo("b4a5ad40-e3d1-4ea1-b833-3871403b09d8")]
            public virtual RepoItemInfo EditorMangoDBInfo
            {
                get
                {
                    return _editormangodbInfo;
                }
            }

            /// <summary>
            /// The QueryTextValidate item.
            /// </summary>
            [RepositoryItem("51197da5-5c1d-4132-87bf-a62e45d9c5c9")]
            public virtual Ranorex.Text QueryTextValidate
            {
                get
                {
                    return _querytextvalidateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The QueryTextValidate item info.
            /// </summary>
            [RepositoryItemInfo("51197da5-5c1d-4132-87bf-a62e45d9c5c9")]
            public virtual RepoItemInfo QueryTextValidateInfo
            {
                get
                {
                    return _querytextvalidateInfo;
                }
            }

            /// <summary>
            /// The TabPage_QueryPanel item.
            /// </summary>
            [RepositoryItem("6874654b-512e-4f05-a513-b1d62404b35c")]
            public virtual Ranorex.TabPage TabPage_QueryPanel
            {
                get
                {
                    return _tabpage_querypanelInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TabPage_QueryPanel item info.
            /// </summary>
            [RepositoryItemInfo("6874654b-512e-4f05-a513-b1d62404b35c")]
            public virtual RepoItemInfo TabPage_QueryPanelInfo
            {
                get
                {
                    return _tabpage_querypanelInfo;
                }
            }

            /// <summary>
            /// The MyFirstComponent folder.
            /// </summary>
            [RepositoryFolder("be5dc9ff-7aaa-49eb-8f3b-1aa90453d537")]
            public virtual TC10570RepoFolders.MyFirstComponentFolder MyFirstComponent
            {
                get { return _myfirstcomponent; }
            }
        }

        /// <summary>
        /// The MyFirstComponentFolder folder.
        /// </summary>
        [RepositoryFolder("be5dc9ff-7aaa-49eb-8f3b-1aa90453d537")]
        public partial class MyFirstComponentFolder : RepoGenBaseFolder
        {
            RepoItemInfo _databasesInfo;
            RepoItemInfo _mongodb172241155v321Info;

            /// <summary>
            /// Creates a new MyFirstComponent  folder.
            /// </summary>
            public MyFirstComponentFolder(RepoGenBaseFolder parentFolder) :
                    base("MyFirstComponent", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']", parentFolder, 30000, null, false, "be5dc9ff-7aaa-49eb-8f3b-1aa90453d537", "")
            {
                _databasesInfo = new RepoItemInfo(this, "Databases", ".//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^MongoDB\\ 172\\.24\\.1\\.155\\ v3\\.2']/treeitem[@text='Databases']", 30000, null, "eaaec602-5edc-41ce-95cf-d097ea2c4483");
                _mongodb172241155v321Info = new RepoItemInfo(this, "MongoDB172241155V321", "?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^MongoDB\\ 172\\.24\\.1\\.155\\ v3\\.2']", 30000, null, "d13bb9d4-a5d5-4b64-8ed7-ecb4fbfcb1c6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("be5dc9ff-7aaa-49eb-8f3b-1aa90453d537")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("be5dc9ff-7aaa-49eb-8f3b-1aa90453d537")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Databases item.
            /// </summary>
            [RepositoryItem("eaaec602-5edc-41ce-95cf-d097ea2c4483")]
            public virtual Ranorex.TreeItem Databases
            {
                get
                {
                    return _databasesInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Databases item info.
            /// </summary>
            [RepositoryItemInfo("eaaec602-5edc-41ce-95cf-d097ea2c4483")]
            public virtual RepoItemInfo DatabasesInfo
            {
                get
                {
                    return _databasesInfo;
                }
            }

            /// <summary>
            /// The MongoDB172241155V321 item.
            /// </summary>
            [RepositoryItem("d13bb9d4-a5d5-4b64-8ed7-ecb4fbfcb1c6")]
            public virtual Ranorex.TreeItem MongoDB172241155V321
            {
                get
                {
                    return _mongodb172241155v321Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The MongoDB172241155V321 item info.
            /// </summary>
            [RepositoryItemInfo("d13bb9d4-a5d5-4b64-8ed7-ecb4fbfcb1c6")]
            public virtual RepoItemInfo MongoDB172241155V321Info
            {
                get
                {
                    return _mongodb172241155v321Info;
                }
            }
        }

        /// <summary>
        /// The DropdownSelection_QueryPanelAppFolder folder.
        /// </summary>
        [RepositoryFolder("df24f824-4535-4551-9339-bfd9a5d40d50")]
        public partial class DropdownSelection_QueryPanelAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _dropdownselectionInfo;

            /// <summary>
            /// Creates a new DropdownSelection_QueryPanel  folder.
            /// </summary>
            public DropdownSelection_QueryPanelAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DropdownSelection_QueryPanel", "/form[@title='' and @processname='datastudio']", parentFolder, 30000, null, false, "df24f824-4535-4551-9339-bfd9a5d40d50", "")
            {
                _dropdownselectionInfo = new RepoItemInfo(this, "DropdownSelection", "?/?/container[@type='OpaquePanel']//container[@name='mainPanel']/?/?/container[@type='JBViewport']/list[@type='LookupImpl$1']/listitem[@index='0']", 30000, null, "b9d9a49f-4cf6-42c3-a134-b78fa4bbe1f0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("df24f824-4535-4551-9339-bfd9a5d40d50")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("df24f824-4535-4551-9339-bfd9a5d40d50")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DropdownSelection item.
            /// </summary>
            [RepositoryItem("b9d9a49f-4cf6-42c3-a134-b78fa4bbe1f0")]
            public virtual Ranorex.ListItem DropdownSelection
            {
                get
                {
                    return _dropdownselectionInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The DropdownSelection item info.
            /// </summary>
            [RepositoryItemInfo("b9d9a49f-4cf6-42c3-a134-b78fa4bbe1f0")]
            public virtual RepoItemInfo DropdownSelectionInfo
            {
                get
                {
                    return _dropdownselectionInfo;
                }
            }
        }

        /// <summary>
        /// The LookupAppFolder folder.
        /// </summary>
        [RepositoryFolder("e6168ddd-34ac-430c-a07b-571303d188dd")]
        public partial class LookupAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Lookup  folder.
            /// </summary>
            public LookupAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Lookup", "/form//container[2]/container[@type='JBScrollPane']/container[@type='JBViewport']/list[@type='LookupImpl$1']/listitem[@text~'^LookupElementBuilder:\\ str']", parentFolder, 30000, null, true, "e6168ddd-34ac-430c-a07b-571303d188dd", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e6168ddd-34ac-430c-a07b-571303d188dd")]
            public virtual Ranorex.ListItem Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e6168ddd-34ac-430c-a07b-571303d188dd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The CloseQueryPanelpopupAppFolder folder.
        /// </summary>
        [RepositoryFolder("e14df672-d378-45a0-ba5d-2211f8070d72")]
        public partial class CloseQueryPanelpopupAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _discardInfo;

            /// <summary>
            /// Creates a new CloseQueryPanelpopup  folder.
            /// </summary>
            public CloseQueryPanelpopupAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CloseQueryPanelpopup", "/form[@title='File Modified']", parentFolder, 30000, null, false, "e14df672-d378-45a0-ba5d-2211f8070d72", "")
            {
                _discardInfo = new RepoItemInfo(this, "Discard", "?/?/container[@name='OptionPane.buttonArea']/button[@text='Discard']", 30000, null, "b415e16e-fe0c-4f0e-b483-56a069088665");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e14df672-d378-45a0-ba5d-2211f8070d72")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e14df672-d378-45a0-ba5d-2211f8070d72")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Discard item.
            /// </summary>
            [RepositoryItem("b415e16e-fe0c-4f0e-b483-56a069088665")]
            public virtual Ranorex.Button Discard
            {
                get
                {
                    return _discardInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Discard item info.
            /// </summary>
            [RepositoryItemInfo("b415e16e-fe0c-4f0e-b483-56a069088665")]
            public virtual RepoItemInfo DiscardInfo
            {
                get
                {
                    return _discardInfo;
                }
            }
        }

        /// <summary>
        /// The Copy_of_OptionsAppFolder folder.
        /// </summary>
        [RepositoryFolder("1308850b-0513-4da4-a644-f37436837bfe")]
        public partial class Copy_of_OptionsAppFolder : RepoGenBaseFolder
        {
            TC10570RepoFolders.MenuOptionsFolder1 _menuoptions;
            RepoItemInfo _defaultsyntaxbuttInfo;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _autocompletioncheckboxInfo;
            RepoItemInfo _autocompletioncheckboxcheckedInfo;
            RepoItemInfo _mongosqlInfo;

            /// <summary>
            /// Creates a new Copy_of_Options  folder.
            /// </summary>
            public Copy_of_OptionsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Copy_of_Options", "/form[@title='Options']", parentFolder, 30000, null, false, "1308850b-0513-4da4-a644-f37436837bfe", "")
            {
                _menuoptions = new TC10570RepoFolders.MenuOptionsFolder1(this);
                _defaultsyntaxbuttInfo = new RepoItemInfo(this, "DefaultSyntaxButt", "container[1]/?/?/container[@name='mySplitter']/container[3]/?/?/container[@name='myContent']//container[@type='JideSplitPane']//container[@type='JBScrollPane']//table[@name='table']/combobox[@type='AQComboBoxOptionEditor$AQComboBoxTableRendererEditor$1']/button[@text='']", 30000, null, "d44a3b62-72cf-4cc0-92f7-4371706768a6");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "container[2]/container[@type='JPanel']//button[@text='OK']", 30000, null, "db7d0f18-7c51-42f8-9e35-916f38f08462");
                _autocompletioncheckboxInfo = new RepoItemInfo(this, "AutoCompletionCheckbox", "container[1]/?/?/container[@name='mySplitter']/container[3]/?/?/container[@name='myContent']//container[@type='JideSplitPane']/container[1]/?/?/container[@type='JBScrollPane']/container[1]/table[@name='table']/checkbox[@text='']", 30000, null, "94bbf253-a07e-497f-b29f-7a1ba04b00e3");
                _autocompletioncheckboxcheckedInfo = new RepoItemInfo(this, "AutoCompletionCheckboxChecked", "container[1]/?/?/container[@name='mySplitter']/container[3]/?/?/container[@name='myContent']//container[@type='JideSplitPane']/container[1]/?/?/container[@type='JBScrollPane']/container[1]/table[@name='table']/row[@index='1']/cell[@text='true']", 30000, null, "a91ee739-63a9-44d4-af22-ae6d4290d5b9");
                _mongosqlInfo = new RepoItemInfo(this, "MongoSQL", "container[1]/?/?/container[@name='mySplitter']/container[3]/?/?/container[@name='myContent']//container[@type='JideSplitPane']//container[@type='JBScrollPane']//row//cell[@text='Default Syntax']/../cell[2]", 30000, null, "caf33da0-7968-40a8-adbe-42f3c15cc29c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1308850b-0513-4da4-a644-f37436837bfe")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1308850b-0513-4da4-a644-f37436837bfe")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DefaultSyntaxButt item.
            /// </summary>
            [RepositoryItem("d44a3b62-72cf-4cc0-92f7-4371706768a6")]
            public virtual Ranorex.Button DefaultSyntaxButt
            {
                get
                {
                    return _defaultsyntaxbuttInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DefaultSyntaxButt item info.
            /// </summary>
            [RepositoryItemInfo("d44a3b62-72cf-4cc0-92f7-4371706768a6")]
            public virtual RepoItemInfo DefaultSyntaxButtInfo
            {
                get
                {
                    return _defaultsyntaxbuttInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("db7d0f18-7c51-42f8-9e35-916f38f08462")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("db7d0f18-7c51-42f8-9e35-916f38f08462")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The AutoCompletionCheckbox item.
            /// </summary>
            [RepositoryItem("94bbf253-a07e-497f-b29f-7a1ba04b00e3")]
            public virtual Ranorex.CheckBox AutoCompletionCheckbox
            {
                get
                {
                    return _autocompletioncheckboxInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The AutoCompletionCheckbox item info.
            /// </summary>
            [RepositoryItemInfo("94bbf253-a07e-497f-b29f-7a1ba04b00e3")]
            public virtual RepoItemInfo AutoCompletionCheckboxInfo
            {
                get
                {
                    return _autocompletioncheckboxInfo;
                }
            }

            /// <summary>
            /// The AutoCompletionCheckboxChecked item.
            /// </summary>
            [RepositoryItem("a91ee739-63a9-44d4-af22-ae6d4290d5b9")]
            public virtual Ranorex.Cell AutoCompletionCheckboxChecked
            {
                get
                {
                    return _autocompletioncheckboxcheckedInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The AutoCompletionCheckboxChecked item info.
            /// </summary>
            [RepositoryItemInfo("a91ee739-63a9-44d4-af22-ae6d4290d5b9")]
            public virtual RepoItemInfo AutoCompletionCheckboxCheckedInfo
            {
                get
                {
                    return _autocompletioncheckboxcheckedInfo;
                }
            }

            /// <summary>
            /// The MongoSQL item.
            /// </summary>
            [RepositoryItem("caf33da0-7968-40a8-adbe-42f3c15cc29c")]
            public virtual Ranorex.Cell MongoSQL
            {
                get
                {
                    return _mongosqlInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The MongoSQL item info.
            /// </summary>
            [RepositoryItemInfo("caf33da0-7968-40a8-adbe-42f3c15cc29c")]
            public virtual RepoItemInfo MongoSQLInfo
            {
                get
                {
                    return _mongosqlInfo;
                }
            }

            /// <summary>
            /// The MenuOptions folder.
            /// </summary>
            [RepositoryFolder("6fd1d10e-7334-407b-8484-77c03925fb93")]
            public virtual TC10570RepoFolders.MenuOptionsFolder1 MenuOptions
            {
                get { return _menuoptions; }
            }
        }

        /// <summary>
        /// The MenuOptionsFolder1 folder.
        /// </summary>
        [RepositoryFolder("6fd1d10e-7334-407b-8484-77c03925fb93")]
        public partial class MenuOptionsFolder1 : RepoGenBaseFolder
        {
            RepoItemInfo _options_queryanalyserInfo;
            RepoItemInfo _mangodbsqlInfo;

            /// <summary>
            /// Creates a new MenuOptions  folder.
            /// </summary>
            public MenuOptionsFolder1(RepoGenBaseFolder parentFolder) :
                    base("MenuOptions", "container[1]/?/?/container[@name='mySplitter']//container[@type='SettingsTreeView$2']/tree[@name='myTree']", parentFolder, 30000, null, false, "6fd1d10e-7334-407b-8484-77c03925fb93", "")
            {
                _options_queryanalyserInfo = new RepoItemInfo(this, "Options_QueryAnalyser", "treeitem/treeitem[14]", 30000, null, "25ca7ff2-e086-4b55-a0fe-3c2f71ad05b6");
                _mangodbsqlInfo = new RepoItemInfo(this, "MangoDBSQL", "treeitem/treeitem[14]/treeitem[19]", 30000, null, "68abdd86-8a3a-47b7-970e-e09e1909d9dc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6fd1d10e-7334-407b-8484-77c03925fb93")]
            public virtual Ranorex.Tree Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6fd1d10e-7334-407b-8484-77c03925fb93")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Options_QueryAnalyser item.
            /// </summary>
            [RepositoryItem("25ca7ff2-e086-4b55-a0fe-3c2f71ad05b6")]
            public virtual Ranorex.TreeItem Options_QueryAnalyser
            {
                get
                {
                    return _options_queryanalyserInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Options_QueryAnalyser item info.
            /// </summary>
            [RepositoryItemInfo("25ca7ff2-e086-4b55-a0fe-3c2f71ad05b6")]
            public virtual RepoItemInfo Options_QueryAnalyserInfo
            {
                get
                {
                    return _options_queryanalyserInfo;
                }
            }

            /// <summary>
            /// The MangoDBSQL item.
            /// </summary>
            [RepositoryItem("68abdd86-8a3a-47b7-970e-e09e1909d9dc")]
            public virtual Ranorex.TreeItem MangoDBSQL
            {
                get
                {
                    return _mangodbsqlInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The MangoDBSQL item info.
            /// </summary>
            [RepositoryItemInfo("68abdd86-8a3a-47b7-970e-e09e1909d9dc")]
            public virtual RepoItemInfo MangoDBSQLInfo
            {
                get
                {
                    return _mangodbsqlInfo;
                }
            }
        }

        /// <summary>
        /// The QueryPanelAppFolder folder.
        /// </summary>
        [RepositoryFolder("076ece9d-0d14-4451-9730-237611e809fc")]
        public partial class QueryPanelAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new QueryPanel  folder.
            /// </summary>
            public QueryPanelAppFolder(RepoGenBaseFolder parentFolder) :
                    base("QueryPanel", "/form[@title~'^Aqua\\ Data\\ Studio\\ \\[Untitle']/container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//container[@type='QueryPanel']/container[@name='panel']/?/?/container[@name='splitPane']/?/?/container[@name='tabbedPane']/container[@name='_gridResultsView']//container[@type='ResultSetTableView$ResultGridsSplitPane']//container[@type='HorizontalLayoutPanel']/container[@type='JPanel']/text[@caption=' 0 record(s)]']", parentFolder, 30000, null, true, "076ece9d-0d14-4451-9730-237611e809fc", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("076ece9d-0d14-4451-9730-237611e809fc")]
            public virtual Ranorex.Text Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("076ece9d-0d14-4451-9730-237611e809fc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The DropDatabaseAppFolder folder.
        /// </summary>
        [RepositoryFolder("d1a83459-57d8-4611-8c5c-132336ee3647")]
        public partial class DropDatabaseAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonyesInfo;

            /// <summary>
            /// Creates a new DropDatabase  folder.
            /// </summary>
            public DropDatabaseAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DropDatabase", "/form[@title='Drop Database']", parentFolder, 30000, null, false, "d1a83459-57d8-4611-8c5c-132336ee3647", "")
            {
                _buttonyesInfo = new RepoItemInfo(this, "ButtonYes", "?/?/container[@name='OptionPane.buttonArea']/button[@text='Yes']", 30000, null, "d81085f5-d4c9-4f07-9469-ee48727111e8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d1a83459-57d8-4611-8c5c-132336ee3647")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d1a83459-57d8-4611-8c5c-132336ee3647")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonYes item.
            /// </summary>
            [RepositoryItem("d81085f5-d4c9-4f07-9469-ee48727111e8")]
            public virtual Ranorex.Button ButtonYes
            {
                get
                {
                    return _buttonyesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonYes item info.
            /// </summary>
            [RepositoryItemInfo("d81085f5-d4c9-4f07-9469-ee48727111e8")]
            public virtual RepoItemInfo ButtonYesInfo
            {
                get
                {
                    return _buttonyesInfo;
                }
            }
        }

        /// <summary>
        /// The CreatedDBExistsAppFolder folder.
        /// </summary>
        [RepositoryFolder("ddc4dd4a-1430-4d31-af10-42291e2fde85")]
        public partial class CreatedDBExistsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new CreatedDBExists  folder.
            /// </summary>
            public CreatedDBExistsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CreatedDBExists", "/form[@title~'^An\\ SQL\\ statement\\ failed\\ t']", parentFolder, 30000, null, false, "ddc4dd4a-1430-4d31-af10-42291e2fde85", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "?/?/container[@name='OptionPane.buttonArea']/button[@name='OptionPane.button']", 30000, null, "b7928b93-e595-464a-9ffe-2d58ccb6c1a8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ddc4dd4a-1430-4d31-af10-42291e2fde85")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ddc4dd4a-1430-4d31-af10-42291e2fde85")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("b7928b93-e595-464a-9ffe-2d58ccb6c1a8")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("b7928b93-e595-464a-9ffe-2d58ccb6c1a8")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The CreateDatabaseAppFolder folder.
        /// </summary>
        [RepositoryFolder("dc649592-998b-4bd1-a17a-461a3d6f8ce1")]
        public partial class CreateDatabaseAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _discardbuttonInfo;

            /// <summary>
            /// Creates a new CreateDatabase  folder.
            /// </summary>
            public CreateDatabaseAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CreateDatabase", "/form[@title='Create: Database']", parentFolder, 30000, null, true, "dc649592-998b-4bd1-a17a-461a3d6f8ce1", "")
            {
                _discardbuttonInfo = new RepoItemInfo(this, "DiscardButton", ".//container[@name='OptionPane.buttonArea']/button[@text='Discard']", 30000, null, "0b2ac365-d035-45ea-a1a4-571ececbc345");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dc649592-998b-4bd1-a17a-461a3d6f8ce1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dc649592-998b-4bd1-a17a-461a3d6f8ce1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DiscardButton item.
            /// </summary>
            [RepositoryItem("0b2ac365-d035-45ea-a1a4-571ececbc345")]
            public virtual Ranorex.Button DiscardButton
            {
                get
                {
                    return _discardbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DiscardButton item info.
            /// </summary>
            [RepositoryItemInfo("0b2ac365-d035-45ea-a1a4-571ececbc345")]
            public virtual RepoItemInfo DiscardButtonInfo
            {
                get
                {
                    return _discardbuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}