///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ADSAutomationPhaseIII.TC_10584
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TC10584_Repo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("c3a23cb1-831a-4265-85df-32442ba172ce")]
    public partial class TC10584_Repo : RepoGenBaseFolder
    {
        static TC10584_Repo instance = new TC10584_Repo();
        TC10584_RepoFolders.AquaDataStudioAppFolder _aquadatastudio;
        TC10584_RepoFolders.DatastudioAppFolder _datastudio;
        TC10584_RepoFolders.AquaDataStudio_AdditionalAppFolder _aquadatastudio_additional;
        TC10584_RepoFolders.NewServerGroupAppFolder _newservergroup;
        TC10584_RepoFolders.ServersAppFolder _servers;
        TC10584_RepoFolders.RemoveServerGroupAppFolder _removeservergroup;

        /// <summary>
        /// Gets the singleton class instance representing the TC10584_Repo element repository.
        /// </summary>
        [RepositoryFolder("c3a23cb1-831a-4265-85df-32442ba172ce")]
        public static TC10584_Repo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TC10584_Repo() 
            : base("TC10584_Repo", "/", null, 0, false, "c3a23cb1-831a-4265-85df-32442ba172ce", ".\\RepositoryImages\\TC10584_Repoc3a23cb1.rximgres")
        {
            _aquadatastudio = new TC10584_RepoFolders.AquaDataStudioAppFolder(this);
            _datastudio = new TC10584_RepoFolders.DatastudioAppFolder(this);
            _aquadatastudio_additional = new TC10584_RepoFolders.AquaDataStudio_AdditionalAppFolder(this);
            _newservergroup = new TC10584_RepoFolders.NewServerGroupAppFolder(this);
            _servers = new TC10584_RepoFolders.ServersAppFolder(this);
            _removeservergroup = new TC10584_RepoFolders.RemoveServerGroupAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c3a23cb1-831a-4265-85df-32442ba172ce")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The AquaDataStudio folder.
        /// </summary>
        [RepositoryFolder("1d9ce719-d3f2-4d68-8dcf-5e4ca8931bc8")]
        public virtual TC10584_RepoFolders.AquaDataStudioAppFolder AquaDataStudio
        {
            get { return _aquadatastudio; }
        }

        /// <summary>
        /// The Datastudio folder.
        /// </summary>
        [RepositoryFolder("dda1b4d2-276e-499e-bafa-5bf51d3e6cb1")]
        public virtual TC10584_RepoFolders.DatastudioAppFolder Datastudio
        {
            get { return _datastudio; }
        }

        /// <summary>
        /// The AquaDataStudio_Additional folder.
        /// </summary>
        [RepositoryFolder("fb645b49-efc0-46ff-b6b0-77d39f98b517")]
        public virtual TC10584_RepoFolders.AquaDataStudio_AdditionalAppFolder AquaDataStudio_Additional
        {
            get { return _aquadatastudio_additional; }
        }

        /// <summary>
        /// The NewServerGroup folder.
        /// </summary>
        [RepositoryFolder("1708bbc2-a4fa-4e11-8c4f-9f5990351ff8")]
        public virtual TC10584_RepoFolders.NewServerGroupAppFolder NewServerGroup
        {
            get { return _newservergroup; }
        }

        /// <summary>
        /// The Servers folder.
        /// </summary>
        [RepositoryFolder("84ea137a-f58e-4bc0-ab31-b6ffd6c0c4e8")]
        public virtual TC10584_RepoFolders.ServersAppFolder Servers
        {
            get { return _servers; }
        }

        /// <summary>
        /// The RemoveServerGroup folder.
        /// </summary>
        [RepositoryFolder("67bf9665-9da3-46ea-ae4a-7b2edd43e269")]
        public virtual TC10584_RepoFolders.RemoveServerGroupAppFolder RemoveServerGroup
        {
            get { return _removeservergroup; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class TC10584_RepoFolders
    {
        /// <summary>
        /// The AquaDataStudioAppFolder folder.
        /// </summary>
        [RepositoryFolder("1d9ce719-d3f2-4d68-8dcf-5e4ca8931bc8")]
        public partial class AquaDataStudioAppFolder : RepoGenBaseFolder
        {
            TC10584_RepoFolders.LocalServersListFolder _localserverslist;
            RepoItemInfo _f1serversInfo;

            /// <summary>
            /// Creates a new AquaDataStudio  folder.
            /// </summary>
            public AquaDataStudioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AquaDataStudio", "/form[@title='Aqua Data Studio']", parentFolder, 30000, null, false, "1d9ce719-d3f2-4d68-8dcf-5e4ca8931bc8", "")
            {
                _localserverslist = new TC10584_RepoFolders.LocalServersListFolder(this);
                _f1serversInfo = new RepoItemInfo(this, "F1Servers", ".//container[@name='myLeftStripe']/checkbox[@text='F1: Servers']", 30000, null, "6aaab4ad-9454-4b82-a624-e17551230872");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1d9ce719-d3f2-4d68-8dcf-5e4ca8931bc8")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1d9ce719-d3f2-4d68-8dcf-5e4ca8931bc8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The F1Servers item.
            /// </summary>
            [RepositoryItem("6aaab4ad-9454-4b82-a624-e17551230872")]
            public virtual Ranorex.CheckBox F1Servers
            {
                get
                {
                    return _f1serversInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The F1Servers item info.
            /// </summary>
            [RepositoryItemInfo("6aaab4ad-9454-4b82-a624-e17551230872")]
            public virtual RepoItemInfo F1ServersInfo
            {
                get
                {
                    return _f1serversInfo;
                }
            }

            /// <summary>
            /// The LocalServersList folder.
            /// </summary>
            [RepositoryFolder("e32f5bc5-0b1d-4cf6-90c3-afc02651f9d2")]
            public virtual TC10584_RepoFolders.LocalServersListFolder LocalServersList
            {
                get { return _localserverslist; }
            }
        }

        /// <summary>
        /// The LocalServersListFolder folder.
        /// </summary>
        [RepositoryFolder("e32f5bc5-0b1d-4cf6-90c3-afc02651f9d2")]
        public partial class LocalServersListFolder : RepoGenBaseFolder
        {
            RepoItemInfo _errorhivecloudserverInfo;
            RepoItemInfo _amazonredshiftInfo;
            RepoItemInfo _hiveclouderahiveserverInfo;
            RepoItemInfo _cassandra17224112222Info;
            RepoItemInfo _schemabrowsertitlepanelbarInfo;

            /// <summary>
            /// Creates a new LocalServersList  folder.
            /// </summary>
            public LocalServersListFolder(RepoGenBaseFolder parentFolder) :
                    base("LocalServersList", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']", parentFolder, 30000, null, false, "e32f5bc5-0b1d-4cf6-90c3-afc02651f9d2", "")
            {
                _errorhivecloudserverInfo = new RepoItemInfo(this, "ErrorHiveCloudServer", ".//container[@name='viewport']/tree[@name='schemaTree']/?/?/treeitem[@text='Local Database Servers']/treeitem[24]/treeitem[@text='Error in getting Hiv...']", 30000, null, "782079e6-42c4-403b-a27e-3f6c1fabde7f");
                _amazonredshiftInfo = new RepoItemInfo(this, "AmazonRedshift", "?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='Amazon Redshift']", 30000, null, "becf7b93-f6a0-4e02-b31c-915be6c8b048");
                _hiveclouderahiveserverInfo = new RepoItemInfo(this, "HiveClouderaHiveServer", "?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']/?/?/treeitem[@text='Local Database Servers']/treeitem[24]", 30000, null, "f07621d4-5f3c-495f-83cd-995e8e0d9611");
                _cassandra17224112222Info = new RepoItemInfo(this, "Cassandra17224112222", "?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Cassandra\\ 172\\.24\\.1\\.122\\ 2\\.']", 30000, null, "a2794b68-9fe4-4015-9936-3c9b6d55ee23");
                _schemabrowsertitlepanelbarInfo = new RepoItemInfo(this, "SchemaBrowserTitlePanelBar", ".//container[@type='ToolWindowHeader$1']", 30000, null, "8d1931ec-46be-4044-8b80-040074a14427");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e32f5bc5-0b1d-4cf6-90c3-afc02651f9d2")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e32f5bc5-0b1d-4cf6-90c3-afc02651f9d2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ErrorHiveCloudServer item.
            /// </summary>
            [RepositoryItem("782079e6-42c4-403b-a27e-3f6c1fabde7f")]
            public virtual Ranorex.TreeItem ErrorHiveCloudServer
            {
                get
                {
                    return _errorhivecloudserverInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The ErrorHiveCloudServer item info.
            /// </summary>
            [RepositoryItemInfo("782079e6-42c4-403b-a27e-3f6c1fabde7f")]
            public virtual RepoItemInfo ErrorHiveCloudServerInfo
            {
                get
                {
                    return _errorhivecloudserverInfo;
                }
            }

            /// <summary>
            /// The AmazonRedshift item.
            /// </summary>
            [RepositoryItem("becf7b93-f6a0-4e02-b31c-915be6c8b048")]
            public virtual Ranorex.TreeItem AmazonRedshift
            {
                get
                {
                    return _amazonredshiftInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The AmazonRedshift item info.
            /// </summary>
            [RepositoryItemInfo("becf7b93-f6a0-4e02-b31c-915be6c8b048")]
            public virtual RepoItemInfo AmazonRedshiftInfo
            {
                get
                {
                    return _amazonredshiftInfo;
                }
            }

            /// <summary>
            /// The HiveClouderaHiveServer item.
            /// </summary>
            [RepositoryItem("f07621d4-5f3c-495f-83cd-995e8e0d9611")]
            public virtual Ranorex.TreeItem HiveClouderaHiveServer
            {
                get
                {
                    return _hiveclouderahiveserverInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The HiveClouderaHiveServer item info.
            /// </summary>
            [RepositoryItemInfo("f07621d4-5f3c-495f-83cd-995e8e0d9611")]
            public virtual RepoItemInfo HiveClouderaHiveServerInfo
            {
                get
                {
                    return _hiveclouderahiveserverInfo;
                }
            }

            /// <summary>
            /// The Cassandra17224112222 item.
            /// </summary>
            [RepositoryItem("a2794b68-9fe4-4015-9936-3c9b6d55ee23")]
            public virtual Ranorex.TreeItem Cassandra17224112222
            {
                get
                {
                    return _cassandra17224112222Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Cassandra17224112222 item info.
            /// </summary>
            [RepositoryItemInfo("a2794b68-9fe4-4015-9936-3c9b6d55ee23")]
            public virtual RepoItemInfo Cassandra17224112222Info
            {
                get
                {
                    return _cassandra17224112222Info;
                }
            }

            /// <summary>
            /// The SchemaBrowserTitlePanelBar item.
            /// </summary>
            [RepositoryItem("8d1931ec-46be-4044-8b80-040074a14427")]
            public virtual Ranorex.Container SchemaBrowserTitlePanelBar
            {
                get
                {
                    return _schemabrowsertitlepanelbarInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SchemaBrowserTitlePanelBar item info.
            /// </summary>
            [RepositoryItemInfo("8d1931ec-46be-4044-8b80-040074a14427")]
            public virtual RepoItemInfo SchemaBrowserTitlePanelBarInfo
            {
                get
                {
                    return _schemabrowsertitlepanelbarInfo;
                }
            }
        }

        /// <summary>
        /// The DatastudioAppFolder folder.
        /// </summary>
        [RepositoryFolder("dda1b4d2-276e-499e-bafa-5bf51d3e6cb1")]
        public partial class DatastudioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _connectInfo;
            RepoItemInfo _pinnedmodeInfo;
            RepoItemInfo _dockedmodeInfo;
            RepoItemInfo _floatingmodeInfo;
            RepoItemInfo _splitmodeInfo;
            RepoItemInfo _movetoInfo;
            RepoItemInfo _maximizepanelInfo;
            RepoItemInfo _hideInfo;
            RepoItemInfo _newservergroupInfo;
            RepoItemInfo _restorepanelsizeInfo;
            RepoItemInfo _amazonserverqueryanalyzerInfo;
            RepoItemInfo _topInfo;
            RepoItemInfo _bottomInfo;
            RepoItemInfo _rightInfo;
            RepoItemInfo _leftInfo;
            RepoItemInfo _deleteservergroupInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new Datastudio  folder.
            /// </summary>
            public DatastudioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Datastudio", "/form[@class='SunAwtWindow']", parentFolder, 30000, null, false, "dda1b4d2-276e-499e-bafa-5bf51d3e6cb1", "")
            {
                _connectInfo = new RepoItemInfo(this, "Connect", "?/?/menuitem[@text='Connect']", 30000, null, "225bd644-73e2-4d7f-b0b7-b88053d03ec4");
                _pinnedmodeInfo = new RepoItemInfo(this, "PinnedMode", "?/?/menuitem[@text='Pinned Mode']", 30000, null, "7cda73fe-40ed-413b-a31a-7b28cc8f4038");
                _dockedmodeInfo = new RepoItemInfo(this, "DockedMode", "?/?/menuitem[@text='Docked Mode']", 30000, null, "b896041b-847b-45da-bc04-01121fb28fff");
                _floatingmodeInfo = new RepoItemInfo(this, "FloatingMode", "?/?/menuitem[@text='Floating Mode']", 30000, null, "f1bdfe6e-f358-4451-a043-eb742cc36b5a");
                _splitmodeInfo = new RepoItemInfo(this, "SplitMode", "?/?/menuitem[@text='Split Mode']", 30000, null, "08c68a73-afd1-4176-83f8-571bfe99030f");
                _movetoInfo = new RepoItemInfo(this, "MoveTo", "?/?/menuitem[@text='Move to']", 30000, null, "7ade1947-d25c-4c35-a8c2-6b78dc8d8824");
                _maximizepanelInfo = new RepoItemInfo(this, "MaximizePanel", "?/?/menuitem[@text='Maximize Panel']", 30000, null, "682db769-5cf2-47d4-a0c7-68b71026469c");
                _hideInfo = new RepoItemInfo(this, "Hide", "?/?/menuitem[@text='Hide']", 30000, null, "b2a50d93-7376-4ded-bc1d-3ef03e8853c3");
                _newservergroupInfo = new RepoItemInfo(this, "NewServerGroup", "?/?/menuitem[@text='New Server Group']", 30000, null, "86445881-72d0-4e8a-93d7-34d4554e0c42");
                _restorepanelsizeInfo = new RepoItemInfo(this, "RestorePanelSize", "?/?/menuitem[@text='Restore Panel Size']", 30000, null, "d18f798b-5090-4a02-ba64-6f229bd1d88c");
                _amazonserverqueryanalyzerInfo = new RepoItemInfo(this, "AmazonServerQueryAnalyzer", "?/?/menuitem[@text='Query Analyzer']", 30000, null, "ebca8345-2d8f-41a0-82be-33685cf38f41");
                _topInfo = new RepoItemInfo(this, "Top", "?/?/menuitem[@text='Top']", 30000, null, "04658d9d-ee29-47fa-89fd-3ee44179d263");
                _bottomInfo = new RepoItemInfo(this, "Bottom", "?/?/menuitem[@text='Bottom']", 30000, null, "d8c79fbd-74d0-42ea-ac7c-bb8f14cae87c");
                _rightInfo = new RepoItemInfo(this, "Right", "?/?/menuitem[@text='Right']", 30000, null, "1c19b792-833a-4a02-90a4-bda0f0c2ca21");
                _leftInfo = new RepoItemInfo(this, "Left", "?/?/menuitem[@text='Left']", 30000, null, "2071a286-8ee9-4d8a-94ae-526d483e76e2");
                _deleteservergroupInfo = new RepoItemInfo(this, "DeleteServerGroup", "?/?/menuitem[@text='Delete Server Group']", 30000, null, "df93fa9c-04a6-4107-9485-3affe37b5b0d");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/menuitem[1]", 30000, null, "70dcd17a-6588-4ec4-bd56-87bd19d50d83");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dda1b4d2-276e-499e-bafa-5bf51d3e6cb1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dda1b4d2-276e-499e-bafa-5bf51d3e6cb1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Connect item.
            /// </summary>
            [RepositoryItem("225bd644-73e2-4d7f-b0b7-b88053d03ec4")]
            public virtual Ranorex.MenuItem Connect
            {
                get
                {
                    return _connectInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Connect item info.
            /// </summary>
            [RepositoryItemInfo("225bd644-73e2-4d7f-b0b7-b88053d03ec4")]
            public virtual RepoItemInfo ConnectInfo
            {
                get
                {
                    return _connectInfo;
                }
            }

            /// <summary>
            /// The PinnedMode item.
            /// </summary>
            [RepositoryItem("7cda73fe-40ed-413b-a31a-7b28cc8f4038")]
            public virtual Ranorex.MenuItem PinnedMode
            {
                get
                {
                    return _pinnedmodeInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The PinnedMode item info.
            /// </summary>
            [RepositoryItemInfo("7cda73fe-40ed-413b-a31a-7b28cc8f4038")]
            public virtual RepoItemInfo PinnedModeInfo
            {
                get
                {
                    return _pinnedmodeInfo;
                }
            }

            /// <summary>
            /// The DockedMode item.
            /// </summary>
            [RepositoryItem("b896041b-847b-45da-bc04-01121fb28fff")]
            public virtual Ranorex.MenuItem DockedMode
            {
                get
                {
                    return _dockedmodeInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The DockedMode item info.
            /// </summary>
            [RepositoryItemInfo("b896041b-847b-45da-bc04-01121fb28fff")]
            public virtual RepoItemInfo DockedModeInfo
            {
                get
                {
                    return _dockedmodeInfo;
                }
            }

            /// <summary>
            /// The FloatingMode item.
            /// </summary>
            [RepositoryItem("f1bdfe6e-f358-4451-a043-eb742cc36b5a")]
            public virtual Ranorex.MenuItem FloatingMode
            {
                get
                {
                    return _floatingmodeInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The FloatingMode item info.
            /// </summary>
            [RepositoryItemInfo("f1bdfe6e-f358-4451-a043-eb742cc36b5a")]
            public virtual RepoItemInfo FloatingModeInfo
            {
                get
                {
                    return _floatingmodeInfo;
                }
            }

            /// <summary>
            /// The SplitMode item.
            /// </summary>
            [RepositoryItem("08c68a73-afd1-4176-83f8-571bfe99030f")]
            public virtual Ranorex.MenuItem SplitMode
            {
                get
                {
                    return _splitmodeInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The SplitMode item info.
            /// </summary>
            [RepositoryItemInfo("08c68a73-afd1-4176-83f8-571bfe99030f")]
            public virtual RepoItemInfo SplitModeInfo
            {
                get
                {
                    return _splitmodeInfo;
                }
            }

            /// <summary>
            /// The MoveTo item.
            /// </summary>
            [RepositoryItem("7ade1947-d25c-4c35-a8c2-6b78dc8d8824")]
            public virtual Ranorex.MenuItem MoveTo
            {
                get
                {
                    return _movetoInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MoveTo item info.
            /// </summary>
            [RepositoryItemInfo("7ade1947-d25c-4c35-a8c2-6b78dc8d8824")]
            public virtual RepoItemInfo MoveToInfo
            {
                get
                {
                    return _movetoInfo;
                }
            }

            /// <summary>
            /// The MaximizePanel item.
            /// </summary>
            [RepositoryItem("682db769-5cf2-47d4-a0c7-68b71026469c")]
            public virtual Ranorex.MenuItem MaximizePanel
            {
                get
                {
                    return _maximizepanelInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MaximizePanel item info.
            /// </summary>
            [RepositoryItemInfo("682db769-5cf2-47d4-a0c7-68b71026469c")]
            public virtual RepoItemInfo MaximizePanelInfo
            {
                get
                {
                    return _maximizepanelInfo;
                }
            }

            /// <summary>
            /// The Hide item.
            /// </summary>
            [RepositoryItem("b2a50d93-7376-4ded-bc1d-3ef03e8853c3")]
            public virtual Ranorex.MenuItem Hide
            {
                get
                {
                    return _hideInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Hide item info.
            /// </summary>
            [RepositoryItemInfo("b2a50d93-7376-4ded-bc1d-3ef03e8853c3")]
            public virtual RepoItemInfo HideInfo
            {
                get
                {
                    return _hideInfo;
                }
            }

            /// <summary>
            /// The NewServerGroup item.
            /// </summary>
            [RepositoryItem("86445881-72d0-4e8a-93d7-34d4554e0c42")]
            public virtual Ranorex.MenuItem NewServerGroup
            {
                get
                {
                    return _newservergroupInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The NewServerGroup item info.
            /// </summary>
            [RepositoryItemInfo("86445881-72d0-4e8a-93d7-34d4554e0c42")]
            public virtual RepoItemInfo NewServerGroupInfo
            {
                get
                {
                    return _newservergroupInfo;
                }
            }

            /// <summary>
            /// The RestorePanelSize item.
            /// </summary>
            [RepositoryItem("d18f798b-5090-4a02-ba64-6f229bd1d88c")]
            public virtual Ranorex.MenuItem RestorePanelSize
            {
                get
                {
                    return _restorepanelsizeInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The RestorePanelSize item info.
            /// </summary>
            [RepositoryItemInfo("d18f798b-5090-4a02-ba64-6f229bd1d88c")]
            public virtual RepoItemInfo RestorePanelSizeInfo
            {
                get
                {
                    return _restorepanelsizeInfo;
                }
            }

            /// <summary>
            /// The AmazonServerQueryAnalyzer item.
            /// </summary>
            [RepositoryItem("ebca8345-2d8f-41a0-82be-33685cf38f41")]
            public virtual Ranorex.MenuItem AmazonServerQueryAnalyzer
            {
                get
                {
                    return _amazonserverqueryanalyzerInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The AmazonServerQueryAnalyzer item info.
            /// </summary>
            [RepositoryItemInfo("ebca8345-2d8f-41a0-82be-33685cf38f41")]
            public virtual RepoItemInfo AmazonServerQueryAnalyzerInfo
            {
                get
                {
                    return _amazonserverqueryanalyzerInfo;
                }
            }

            /// <summary>
            /// The Top item.
            /// </summary>
            [RepositoryItem("04658d9d-ee29-47fa-89fd-3ee44179d263")]
            public virtual Ranorex.MenuItem Top
            {
                get
                {
                    return _topInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Top item info.
            /// </summary>
            [RepositoryItemInfo("04658d9d-ee29-47fa-89fd-3ee44179d263")]
            public virtual RepoItemInfo TopInfo
            {
                get
                {
                    return _topInfo;
                }
            }

            /// <summary>
            /// The Bottom item.
            /// </summary>
            [RepositoryItem("d8c79fbd-74d0-42ea-ac7c-bb8f14cae87c")]
            public virtual Ranorex.MenuItem Bottom
            {
                get
                {
                    return _bottomInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Bottom item info.
            /// </summary>
            [RepositoryItemInfo("d8c79fbd-74d0-42ea-ac7c-bb8f14cae87c")]
            public virtual RepoItemInfo BottomInfo
            {
                get
                {
                    return _bottomInfo;
                }
            }

            /// <summary>
            /// The Right item.
            /// </summary>
            [RepositoryItem("1c19b792-833a-4a02-90a4-bda0f0c2ca21")]
            public virtual Ranorex.MenuItem Right
            {
                get
                {
                    return _rightInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Right item info.
            /// </summary>
            [RepositoryItemInfo("1c19b792-833a-4a02-90a4-bda0f0c2ca21")]
            public virtual RepoItemInfo RightInfo
            {
                get
                {
                    return _rightInfo;
                }
            }

            /// <summary>
            /// The Left item.
            /// </summary>
            [RepositoryItem("2071a286-8ee9-4d8a-94ae-526d483e76e2")]
            public virtual Ranorex.MenuItem Left
            {
                get
                {
                    return _leftInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Left item info.
            /// </summary>
            [RepositoryItemInfo("2071a286-8ee9-4d8a-94ae-526d483e76e2")]
            public virtual RepoItemInfo LeftInfo
            {
                get
                {
                    return _leftInfo;
                }
            }

            /// <summary>
            /// The DeleteServerGroup item.
            /// </summary>
            [RepositoryItem("df93fa9c-04a6-4107-9485-3affe37b5b0d")]
            public virtual Ranorex.MenuItem DeleteServerGroup
            {
                get
                {
                    return _deleteservergroupInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The DeleteServerGroup item info.
            /// </summary>
            [RepositoryItemInfo("df93fa9c-04a6-4107-9485-3affe37b5b0d")]
            public virtual RepoItemInfo DeleteServerGroupInfo
            {
                get
                {
                    return _deleteservergroupInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("70dcd17a-6588-4ec4-bd56-87bd19d50d83")]
            public virtual Ranorex.MenuItem Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("70dcd17a-6588-4ec4-bd56-87bd19d50d83")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The AquaDataStudio_AdditionalAppFolder folder.
        /// </summary>
        [RepositoryFolder("fb645b49-efc0-46ff-b6b0-77d39f98b517")]
        public partial class AquaDataStudio_AdditionalAppFolder : RepoGenBaseFolder
        {
            TC10584_RepoFolders.MyLayeredPaneFolder _mylayeredpane;
            TC10584_RepoFolders.MyFirstComponentFolder _myfirstcomponent;
            RepoItemInfo _f1serversInfo;
            RepoItemInfo _f5detailInfo;

            /// <summary>
            /// Creates a new AquaDataStudio_Additional  folder.
            /// </summary>
            public AquaDataStudio_AdditionalAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AquaDataStudio_Additional", "/form[@title~'^Aqua\\ Data\\ Studio\\ \\[Untitle']", parentFolder, 30000, null, false, "fb645b49-efc0-46ff-b6b0-77d39f98b517", "")
            {
                _mylayeredpane = new TC10584_RepoFolders.MyLayeredPaneFolder(this);
                _myfirstcomponent = new TC10584_RepoFolders.MyFirstComponentFolder(this);
                _f1serversInfo = new RepoItemInfo(this, "F1Servers", "?/?/container[@name='myLeftStripe']/checkbox[@text='F1: Servers']", 30000, null, "e83fab6b-41d6-4c7e-8495-e33df87e60bf");
                _f5detailInfo = new RepoItemInfo(this, "F5Detail", "?/?/container[@name='myBottomStripe']/checkbox[@text='F5: Detail']", 30000, null, "d231a69c-7b27-4bba-a478-336cff371f38");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fb645b49-efc0-46ff-b6b0-77d39f98b517")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fb645b49-efc0-46ff-b6b0-77d39f98b517")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The F1Servers item.
            /// </summary>
            [RepositoryItem("e83fab6b-41d6-4c7e-8495-e33df87e60bf")]
            public virtual Ranorex.CheckBox F1Servers
            {
                get
                {
                    return _f1serversInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The F1Servers item info.
            /// </summary>
            [RepositoryItemInfo("e83fab6b-41d6-4c7e-8495-e33df87e60bf")]
            public virtual RepoItemInfo F1ServersInfo
            {
                get
                {
                    return _f1serversInfo;
                }
            }

            /// <summary>
            /// The F5Detail item.
            /// </summary>
            [RepositoryItem("d231a69c-7b27-4bba-a478-336cff371f38")]
            public virtual Ranorex.CheckBox F5Detail
            {
                get
                {
                    return _f5detailInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The F5Detail item info.
            /// </summary>
            [RepositoryItemInfo("d231a69c-7b27-4bba-a478-336cff371f38")]
            public virtual RepoItemInfo F5DetailInfo
            {
                get
                {
                    return _f5detailInfo;
                }
            }

            /// <summary>
            /// The MyLayeredPane folder.
            /// </summary>
            [RepositoryFolder("8bd1529f-0c09-4043-bcb1-a7f7ddd12acf")]
            public virtual TC10584_RepoFolders.MyLayeredPaneFolder MyLayeredPane
            {
                get { return _mylayeredpane; }
            }

            /// <summary>
            /// The MyFirstComponent folder.
            /// </summary>
            [RepositoryFolder("1b54592c-77ff-491b-8d2d-a832e5c65bf1")]
            public virtual TC10584_RepoFolders.MyFirstComponentFolder MyFirstComponent
            {
                get { return _myfirstcomponent; }
            }
        }

        /// <summary>
        /// The MyLayeredPaneFolder folder.
        /// </summary>
        [RepositoryFolder("8bd1529f-0c09-4043-bcb1-a7f7ddd12acf")]
        public partial class MyLayeredPaneFolder : RepoGenBaseFolder
        {
            RepoItemInfo _analyzerwindowInfo;
            RepoItemInfo _horizontalscrollbarInfo;
            RepoItemInfo _verticalscrollbarInfo;
            RepoItemInfo _localdatabaseserversInfo;
            RepoItemInfo _hivehortonworksphoenix25109011Info;
            RepoItemInfo _informix172241140v1170Info;
            RepoItemInfo _hivemapr521hiveserver21090120Info;
            RepoItemInfo _schematreeInfo;
            RepoItemInfo _autocompletebuttonInfo;
            RepoItemInfo _schemabrowsertitlepanelqueryanalyserInfo;
            RepoItemInfo _rootatamazonredshiftpanelInfo;
            RepoItemInfo _queryanalysernameInfo;
            RepoItemInfo _schemabrowserdockedmodeInfo;
            RepoItemInfo _verticalscrolldownInfo;
            RepoItemInfo _horizontalscrolldownInfo;

            /// <summary>
            /// Creates a new MyLayeredPane  folder.
            /// </summary>
            public MyLayeredPaneFolder(RepoGenBaseFolder parentFolder) :
                    base("MyLayeredPane", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']", parentFolder, 30000, null, false, "8bd1529f-0c09-4043-bcb1-a7f7ddd12acf", "")
            {
                _analyzerwindowInfo = new RepoItemInfo(this, "AnalyzerWindow", ".//container[@type='PlatDockingContentPanel']/?/?/container[@accessiblename='root@Amazon Redshift [Untitled]']", 30000, null, "683c7885-f545-4e64-9091-0777e3c1bd42");
                _horizontalscrollbarInfo = new RepoItemInfo(this, "HorizontalScrollBar", "container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//scrollbar[@name='horizontalScrollBar']", 30000, null, "cfdcd46e-4257-428b-8102-7004647e3926");
                _verticalscrollbarInfo = new RepoItemInfo(this, "VerticalScrollBar", "container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//scrollbar[@name='verticalScrollBar']", 30000, null, "d9d024c3-bff2-4f5f-867b-0540e0352005");
                _localdatabaseserversInfo = new RepoItemInfo(this, "LocalDatabaseServers", "container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//container[@name='viewport']/tree[@name='schemaTree']/?/?/treeitem[@text='Local Database Servers']", 30000, null, "fcd15d6d-c66e-47ef-933d-be172ce7b687");
                _hivehortonworksphoenix25109011Info = new RepoItemInfo(this, "HiveHortonworksPhoenix25109011", "container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']/?/?/treeitem[@text='Local Database Servers']/treeitem[30]", 30000, null, "2b72dd0b-4c05-4982-a842-e76bf9ac13d5");
                _informix172241140v1170Info = new RepoItemInfo(this, "Informix172241140V1170", "container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Informix\\ 172\\.24\\.1\\.140\\ v11']", 30000, null, "3f9c9f29-3f51-4465-8abf-ab941bf879a1");
                _hivemapr521hiveserver21090120Info = new RepoItemInfo(this, "HiveMapr521Hiveserver21090120", "container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Hive\\ -\\ Mapr\\ 5\\.2\\.1\\ Hiveser']", 30000, null, "53bcd258-8837-4853-8c69-fdcd3df2143c");
                _schematreeInfo = new RepoItemInfo(this, "SchemaTree", "container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//container[@name='viewport']/tree[@name='schemaTree']", 30000, null, "a1e7b15a-56e0-4ad7-9f22-059f09e40412");
                _autocompletebuttonInfo = new RepoItemInfo(this, "AutoCompleteButton", "?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//container[@type='QueryPanel']//container[@name='toolBar']/button[@name='autoCompleteButton']", 30000, null, "7a7e4bc3-203f-4870-88f2-9357139fb6ac");
                _schemabrowsertitlepanelqueryanalyserInfo = new RepoItemInfo(this, "SchemaBrowserTitlePanelQueryanalyser", "?/?/container[@type='ThreeComponentsSplitter']/container[@name='myFirstComponent']//container[@type='ToolWindowHeader$1']", 30000, null, "20f882ef-e6cd-48e6-a397-dd2b61818d0a");
                _rootatamazonredshiftpanelInfo = new RepoItemInfo(this, "RootAtAmazonRedshiftPanel", "?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']/?/?/container[@accessiblename='root@Amazon Redshift [Untitled 3]']", 30000, null, "dfb0ff3b-f61d-4f01-99fd-804c1e89d557");
                _queryanalysernameInfo = new RepoItemInfo(this, "QueryAnalyserName", "?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//tabpage[@title~'^root@Amazon\\ Redshift\\ \\[Unt']", 30000, null, "a461d20c-166f-4876-909d-08d226b45327");
                _schemabrowserdockedmodeInfo = new RepoItemInfo(this, "SchemaBrowserDockedMode", ".//container[@type='ToolWindowHeader$1']", 30000, null, "44824e29-b379-4dba-98b5-a0d04ddccd84");
                _verticalscrolldownInfo = new RepoItemInfo(this, "VerticalScrollDown", "container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//scrollbar[@name='verticalScrollBar']/button[1]", 30000, null, "457ac683-4b5c-403e-aa4e-99d5e01a7dc4");
                _horizontalscrolldownInfo = new RepoItemInfo(this, "HorizontalScrollDown", "container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//scrollbar[@name='horizontalScrollBar']/button[1]", 30000, null, "50db9da9-e254-4db9-b31b-fe0c025cc25a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8bd1529f-0c09-4043-bcb1-a7f7ddd12acf")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8bd1529f-0c09-4043-bcb1-a7f7ddd12acf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AnalyzerWindow item.
            /// </summary>
            [RepositoryItem("683c7885-f545-4e64-9091-0777e3c1bd42")]
            public virtual Ranorex.Container AnalyzerWindow
            {
                get
                {
                    return _analyzerwindowInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The AnalyzerWindow item info.
            /// </summary>
            [RepositoryItemInfo("683c7885-f545-4e64-9091-0777e3c1bd42")]
            public virtual RepoItemInfo AnalyzerWindowInfo
            {
                get
                {
                    return _analyzerwindowInfo;
                }
            }

            /// <summary>
            /// The HorizontalScrollBar item.
            /// </summary>
            [RepositoryItem("cfdcd46e-4257-428b-8102-7004647e3926")]
            public virtual Ranorex.ScrollBar HorizontalScrollBar
            {
                get
                {
                    return _horizontalscrollbarInfo.CreateAdapter<Ranorex.ScrollBar>(true);
                }
            }

            /// <summary>
            /// The HorizontalScrollBar item info.
            /// </summary>
            [RepositoryItemInfo("cfdcd46e-4257-428b-8102-7004647e3926")]
            public virtual RepoItemInfo HorizontalScrollBarInfo
            {
                get
                {
                    return _horizontalscrollbarInfo;
                }
            }

            /// <summary>
            /// The VerticalScrollBar item.
            /// </summary>
            [RepositoryItem("d9d024c3-bff2-4f5f-867b-0540e0352005")]
            public virtual Ranorex.ScrollBar VerticalScrollBar
            {
                get
                {
                    return _verticalscrollbarInfo.CreateAdapter<Ranorex.ScrollBar>(true);
                }
            }

            /// <summary>
            /// The VerticalScrollBar item info.
            /// </summary>
            [RepositoryItemInfo("d9d024c3-bff2-4f5f-867b-0540e0352005")]
            public virtual RepoItemInfo VerticalScrollBarInfo
            {
                get
                {
                    return _verticalscrollbarInfo;
                }
            }

            /// <summary>
            /// The LocalDatabaseServers item.
            /// </summary>
            [RepositoryItem("fcd15d6d-c66e-47ef-933d-be172ce7b687")]
            public virtual Ranorex.TreeItem LocalDatabaseServers
            {
                get
                {
                    return _localdatabaseserversInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The LocalDatabaseServers item info.
            /// </summary>
            [RepositoryItemInfo("fcd15d6d-c66e-47ef-933d-be172ce7b687")]
            public virtual RepoItemInfo LocalDatabaseServersInfo
            {
                get
                {
                    return _localdatabaseserversInfo;
                }
            }

            /// <summary>
            /// The HiveHortonworksPhoenix25109011 item.
            /// </summary>
            [RepositoryItem("2b72dd0b-4c05-4982-a842-e76bf9ac13d5")]
            public virtual Ranorex.TreeItem HiveHortonworksPhoenix25109011
            {
                get
                {
                    return _hivehortonworksphoenix25109011Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The HiveHortonworksPhoenix25109011 item info.
            /// </summary>
            [RepositoryItemInfo("2b72dd0b-4c05-4982-a842-e76bf9ac13d5")]
            public virtual RepoItemInfo HiveHortonworksPhoenix25109011Info
            {
                get
                {
                    return _hivehortonworksphoenix25109011Info;
                }
            }

            /// <summary>
            /// The Informix172241140V1170 item.
            /// </summary>
            [RepositoryItem("3f9c9f29-3f51-4465-8abf-ab941bf879a1")]
            public virtual Ranorex.TreeItem Informix172241140V1170
            {
                get
                {
                    return _informix172241140v1170Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Informix172241140V1170 item info.
            /// </summary>
            [RepositoryItemInfo("3f9c9f29-3f51-4465-8abf-ab941bf879a1")]
            public virtual RepoItemInfo Informix172241140V1170Info
            {
                get
                {
                    return _informix172241140v1170Info;
                }
            }

            /// <summary>
            /// The HiveMapr521Hiveserver21090120 item.
            /// </summary>
            [RepositoryItem("53bcd258-8837-4853-8c69-fdcd3df2143c")]
            public virtual Ranorex.TreeItem HiveMapr521Hiveserver21090120
            {
                get
                {
                    return _hivemapr521hiveserver21090120Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The HiveMapr521Hiveserver21090120 item info.
            /// </summary>
            [RepositoryItemInfo("53bcd258-8837-4853-8c69-fdcd3df2143c")]
            public virtual RepoItemInfo HiveMapr521Hiveserver21090120Info
            {
                get
                {
                    return _hivemapr521hiveserver21090120Info;
                }
            }

            /// <summary>
            /// The SchemaTree item.
            /// </summary>
            [RepositoryItem("a1e7b15a-56e0-4ad7-9f22-059f09e40412")]
            public virtual Ranorex.Tree SchemaTree
            {
                get
                {
                    return _schematreeInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The SchemaTree item info.
            /// </summary>
            [RepositoryItemInfo("a1e7b15a-56e0-4ad7-9f22-059f09e40412")]
            public virtual RepoItemInfo SchemaTreeInfo
            {
                get
                {
                    return _schematreeInfo;
                }
            }

            /// <summary>
            /// The AutoCompleteButton item.
            /// </summary>
            [RepositoryItem("7a7e4bc3-203f-4870-88f2-9357139fb6ac")]
            public virtual Ranorex.Button AutoCompleteButton
            {
                get
                {
                    return _autocompletebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AutoCompleteButton item info.
            /// </summary>
            [RepositoryItemInfo("7a7e4bc3-203f-4870-88f2-9357139fb6ac")]
            public virtual RepoItemInfo AutoCompleteButtonInfo
            {
                get
                {
                    return _autocompletebuttonInfo;
                }
            }

            /// <summary>
            /// The SchemaBrowserTitlePanelQueryanalyser item.
            /// </summary>
            [RepositoryItem("20f882ef-e6cd-48e6-a397-dd2b61818d0a")]
            public virtual Ranorex.Container SchemaBrowserTitlePanelQueryanalyser
            {
                get
                {
                    return _schemabrowsertitlepanelqueryanalyserInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SchemaBrowserTitlePanelQueryanalyser item info.
            /// </summary>
            [RepositoryItemInfo("20f882ef-e6cd-48e6-a397-dd2b61818d0a")]
            public virtual RepoItemInfo SchemaBrowserTitlePanelQueryanalyserInfo
            {
                get
                {
                    return _schemabrowsertitlepanelqueryanalyserInfo;
                }
            }

            /// <summary>
            /// The RootAtAmazonRedshiftPanel item.
            /// </summary>
            [RepositoryItem("dfb0ff3b-f61d-4f01-99fd-804c1e89d557")]
            public virtual Ranorex.Container RootAtAmazonRedshiftPanel
            {
                get
                {
                    return _rootatamazonredshiftpanelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The RootAtAmazonRedshiftPanel item info.
            /// </summary>
            [RepositoryItemInfo("dfb0ff3b-f61d-4f01-99fd-804c1e89d557")]
            public virtual RepoItemInfo RootAtAmazonRedshiftPanelInfo
            {
                get
                {
                    return _rootatamazonredshiftpanelInfo;
                }
            }

            /// <summary>
            /// The QueryAnalyserName item.
            /// </summary>
            [RepositoryItem("a461d20c-166f-4876-909d-08d226b45327")]
            public virtual Ranorex.TabPage QueryAnalyserName
            {
                get
                {
                    return _queryanalysernameInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The QueryAnalyserName item info.
            /// </summary>
            [RepositoryItemInfo("a461d20c-166f-4876-909d-08d226b45327")]
            public virtual RepoItemInfo QueryAnalyserNameInfo
            {
                get
                {
                    return _queryanalysernameInfo;
                }
            }

            /// <summary>
            /// The SchemaBrowserDockedMode item.
            /// </summary>
            [RepositoryItem("44824e29-b379-4dba-98b5-a0d04ddccd84")]
            public virtual Ranorex.Container SchemaBrowserDockedMode
            {
                get
                {
                    return _schemabrowserdockedmodeInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SchemaBrowserDockedMode item info.
            /// </summary>
            [RepositoryItemInfo("44824e29-b379-4dba-98b5-a0d04ddccd84")]
            public virtual RepoItemInfo SchemaBrowserDockedModeInfo
            {
                get
                {
                    return _schemabrowserdockedmodeInfo;
                }
            }

            /// <summary>
            /// The VerticalScrollDown item.
            /// </summary>
            [RepositoryItem("457ac683-4b5c-403e-aa4e-99d5e01a7dc4")]
            public virtual Ranorex.Button VerticalScrollDown
            {
                get
                {
                    return _verticalscrolldownInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The VerticalScrollDown item info.
            /// </summary>
            [RepositoryItemInfo("457ac683-4b5c-403e-aa4e-99d5e01a7dc4")]
            public virtual RepoItemInfo VerticalScrollDownInfo
            {
                get
                {
                    return _verticalscrolldownInfo;
                }
            }

            /// <summary>
            /// The HorizontalScrollDown item.
            /// </summary>
            [RepositoryItem("50db9da9-e254-4db9-b31b-fe0c025cc25a")]
            public virtual Ranorex.Button HorizontalScrollDown
            {
                get
                {
                    return _horizontalscrolldownInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The HorizontalScrollDown item info.
            /// </summary>
            [RepositoryItemInfo("50db9da9-e254-4db9-b31b-fe0c025cc25a")]
            public virtual RepoItemInfo HorizontalScrollDownInfo
            {
                get
                {
                    return _horizontalscrolldownInfo;
                }
            }
        }

        /// <summary>
        /// The MyFirstComponentFolder folder.
        /// </summary>
        [RepositoryFolder("1b54592c-77ff-491b-8d2d-a832e5c65bf1")]
        public partial class MyFirstComponentFolder : RepoGenBaseFolder
        {
            RepoItemInfo _schematreeInfo;
            RepoItemInfo _newgroupInfo;
            RepoItemInfo _hiveclouderaimpala10901163513Info;
            RepoItemInfo _db2zos1928633139v12Info;
            RepoItemInfo _localdatabaseserversInfo;
            RepoItemInfo _informixserver12_5Info;
            RepoItemInfo _informix_databasesInfo;
            RepoItemInfo _informix_storageInfo;
            RepoItemInfo _informix_managementInfo;
            RepoItemInfo _oracleserver199Info;
            RepoItemInfo _myschemaInfo;
            RepoItemInfo _storageInfo;
            RepoItemInfo _managementInfo;
            RepoItemInfo _sqlserver1722411542017Info;
            RepoItemInfo _sqlservermanagementInfo;
            RepoItemInfo _toolwindowheaderdollar1Info;

            /// <summary>
            /// Creates a new MyFirstComponent  folder.
            /// </summary>
            public MyFirstComponentFolder(RepoGenBaseFolder parentFolder) :
                    base("MyFirstComponent", "container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']", parentFolder, 30000, null, false, "1b54592c-77ff-491b-8d2d-a832e5c65bf1", "")
            {
                _schematreeInfo = new RepoItemInfo(this, "SchemaTree", ".//container[@name='viewport']/tree[@name='schemaTree']", 30000, null, "b26f176a-2d50-439b-884e-d6224affa850");
                _newgroupInfo = new RepoItemInfo(this, "NewGroup", "?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='NewGroup']", 30000, null, "dc22dbcc-8c14-4aeb-98d6-910721ae2ef2");
                _hiveclouderaimpala10901163513Info = new RepoItemInfo(this, "HiveClouderaImpala10901163513", "?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Hive\\ -\\ Cloudera\\ Impala\\ 10']", 30000, null, "a5d61755-3fc3-4d30-a6de-0e10f9e2d919");
                _db2zos1928633139v12Info = new RepoItemInfo(this, "DB2ZOS1928633139V12", ".//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='NewGroup']/treeitem[@text='DB2 ZOS 192.86.33.139 V12']", 30000, null, "0c08b4d7-f784-4b6e-8a85-4858ffd1a31e");
                _localdatabaseserversInfo = new RepoItemInfo(this, "LocalDatabaseServers", ".//container[@name='viewport']/tree[@name='schemaTree']/?/?/treeitem[@text='Local Database Servers']", 30000, null, "c81a8542-5e9b-4935-9574-145b9e77432c");
                _informixserver12_5Info = new RepoItemInfo(this, "InformixServer12_5", "?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Informix\\ 172\\.24\\.1\\.145\\ v12']", 30000, null, "328c050c-94bd-487c-9565-e31aaa6f3266");
                _informix_databasesInfo = new RepoItemInfo(this, "Informix_Databases", ".//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Informix\\ 172\\.24\\.1\\.145\\ v12']/treeitem[@text='Databases']", 30000, null, "6d49a7e9-bd8f-4b8f-81f8-3b2fb484d3c6");
                _informix_storageInfo = new RepoItemInfo(this, "Informix_Storage", ".//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Informix\\ 172\\.24\\.1\\.145\\ v12']/treeitem[@text='Storage']", 30000, null, "e08950b5-e409-40ff-8cbb-5dfac0d39645");
                _informix_managementInfo = new RepoItemInfo(this, "Informix_Management", ".//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Informix\\ 172\\.24\\.1\\.145\\ v12']/treeitem[@text='Management']", 30000, null, "673a956c-b57f-43f7-92bd-8cb03e62e827");
                _oracleserver199Info = new RepoItemInfo(this, "OracleServer199", "?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Oracle\\ 172\\.24\\.1\\.199\\ v12\\.1']", 30000, null, "3f69010e-94f0-4592-ab55-7048eaa5582d");
                _myschemaInfo = new RepoItemInfo(this, "MySchema", ".//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Oracle\\ 172\\.24\\.1\\.199\\ v12\\.1']/treeitem[@text='My Schema']", 30000, null, "69402a40-8727-44b9-b170-e1aaff8b0031");
                _storageInfo = new RepoItemInfo(this, "Storage", ".//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Oracle\\ 172\\.24\\.1\\.199\\ v12\\.1']/treeitem[@text='Storage']", 30000, null, "1a856a20-74bd-42e4-9e8d-eddbae096e57");
                _managementInfo = new RepoItemInfo(this, "Management", ".//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Oracle\\ 172\\.24\\.1\\.199\\ v12\\.1']/treeitem[@text='Management']", 30000, null, "e6e511a5-0a7b-4b4e-a2d9-07576819ffb9");
                _sqlserver1722411542017Info = new RepoItemInfo(this, "SQLServer1722411542017", "?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^SQL\\ Server\\ 172\\.24\\.1\\.154\\ 2']", 30000, null, "5a5162e3-402d-4ace-9b86-4855454b9fc1");
                _sqlservermanagementInfo = new RepoItemInfo(this, "SQLServerManagement", ".//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^SQL\\ Server\\ 172\\.24\\.1\\.154\\ 2']/treeitem[@text='Management']", 30000, null, "9d404c67-ebeb-4d00-9427-0c86139381f7");
                _toolwindowheaderdollar1Info = new RepoItemInfo(this, "ToolWindowHeaderDollar1", ".//container[@type='ToolWindowHeader$1']", 30000, null, "5fc4aadb-cf8c-4b4f-a0f0-f8fba81c5ef7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1b54592c-77ff-491b-8d2d-a832e5c65bf1")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1b54592c-77ff-491b-8d2d-a832e5c65bf1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SchemaTree item.
            /// </summary>
            [RepositoryItem("b26f176a-2d50-439b-884e-d6224affa850")]
            public virtual Ranorex.Tree SchemaTree
            {
                get
                {
                    return _schematreeInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The SchemaTree item info.
            /// </summary>
            [RepositoryItemInfo("b26f176a-2d50-439b-884e-d6224affa850")]
            public virtual RepoItemInfo SchemaTreeInfo
            {
                get
                {
                    return _schematreeInfo;
                }
            }

            /// <summary>
            /// The NewGroup item.
            /// </summary>
            [RepositoryItem("dc22dbcc-8c14-4aeb-98d6-910721ae2ef2")]
            public virtual Ranorex.TreeItem NewGroup
            {
                get
                {
                    return _newgroupInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The NewGroup item info.
            /// </summary>
            [RepositoryItemInfo("dc22dbcc-8c14-4aeb-98d6-910721ae2ef2")]
            public virtual RepoItemInfo NewGroupInfo
            {
                get
                {
                    return _newgroupInfo;
                }
            }

            /// <summary>
            /// The HiveClouderaImpala10901163513 item.
            /// </summary>
            [RepositoryItem("a5d61755-3fc3-4d30-a6de-0e10f9e2d919")]
            public virtual Ranorex.TreeItem HiveClouderaImpala10901163513
            {
                get
                {
                    return _hiveclouderaimpala10901163513Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The HiveClouderaImpala10901163513 item info.
            /// </summary>
            [RepositoryItemInfo("a5d61755-3fc3-4d30-a6de-0e10f9e2d919")]
            public virtual RepoItemInfo HiveClouderaImpala10901163513Info
            {
                get
                {
                    return _hiveclouderaimpala10901163513Info;
                }
            }

            /// <summary>
            /// The DB2ZOS1928633139V12 item.
            /// </summary>
            [RepositoryItem("0c08b4d7-f784-4b6e-8a85-4858ffd1a31e")]
            public virtual Ranorex.TreeItem DB2ZOS1928633139V12
            {
                get
                {
                    return _db2zos1928633139v12Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The DB2ZOS1928633139V12 item info.
            /// </summary>
            [RepositoryItemInfo("0c08b4d7-f784-4b6e-8a85-4858ffd1a31e")]
            public virtual RepoItemInfo DB2ZOS1928633139V12Info
            {
                get
                {
                    return _db2zos1928633139v12Info;
                }
            }

            /// <summary>
            /// The LocalDatabaseServers item.
            /// </summary>
            [RepositoryItem("c81a8542-5e9b-4935-9574-145b9e77432c")]
            public virtual Ranorex.TreeItem LocalDatabaseServers
            {
                get
                {
                    return _localdatabaseserversInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The LocalDatabaseServers item info.
            /// </summary>
            [RepositoryItemInfo("c81a8542-5e9b-4935-9574-145b9e77432c")]
            public virtual RepoItemInfo LocalDatabaseServersInfo
            {
                get
                {
                    return _localdatabaseserversInfo;
                }
            }

            /// <summary>
            /// The InformixServer12_5 item.
            /// </summary>
            [RepositoryItem("328c050c-94bd-487c-9565-e31aaa6f3266")]
            public virtual Ranorex.TreeItem InformixServer12_5
            {
                get
                {
                    return _informixserver12_5Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The InformixServer12_5 item info.
            /// </summary>
            [RepositoryItemInfo("328c050c-94bd-487c-9565-e31aaa6f3266")]
            public virtual RepoItemInfo InformixServer12_5Info
            {
                get
                {
                    return _informixserver12_5Info;
                }
            }

            /// <summary>
            /// The Informix_Databases item.
            /// </summary>
            [RepositoryItem("6d49a7e9-bd8f-4b8f-81f8-3b2fb484d3c6")]
            public virtual Ranorex.TreeItem Informix_Databases
            {
                get
                {
                    return _informix_databasesInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Informix_Databases item info.
            /// </summary>
            [RepositoryItemInfo("6d49a7e9-bd8f-4b8f-81f8-3b2fb484d3c6")]
            public virtual RepoItemInfo Informix_DatabasesInfo
            {
                get
                {
                    return _informix_databasesInfo;
                }
            }

            /// <summary>
            /// The Informix_Storage item.
            /// </summary>
            [RepositoryItem("e08950b5-e409-40ff-8cbb-5dfac0d39645")]
            public virtual Ranorex.TreeItem Informix_Storage
            {
                get
                {
                    return _informix_storageInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Informix_Storage item info.
            /// </summary>
            [RepositoryItemInfo("e08950b5-e409-40ff-8cbb-5dfac0d39645")]
            public virtual RepoItemInfo Informix_StorageInfo
            {
                get
                {
                    return _informix_storageInfo;
                }
            }

            /// <summary>
            /// The Informix_Management item.
            /// </summary>
            [RepositoryItem("673a956c-b57f-43f7-92bd-8cb03e62e827")]
            public virtual Ranorex.TreeItem Informix_Management
            {
                get
                {
                    return _informix_managementInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Informix_Management item info.
            /// </summary>
            [RepositoryItemInfo("673a956c-b57f-43f7-92bd-8cb03e62e827")]
            public virtual RepoItemInfo Informix_ManagementInfo
            {
                get
                {
                    return _informix_managementInfo;
                }
            }

            /// <summary>
            /// The OracleServer199 item.
            /// </summary>
            [RepositoryItem("3f69010e-94f0-4592-ab55-7048eaa5582d")]
            public virtual Ranorex.TreeItem OracleServer199
            {
                get
                {
                    return _oracleserver199Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The OracleServer199 item info.
            /// </summary>
            [RepositoryItemInfo("3f69010e-94f0-4592-ab55-7048eaa5582d")]
            public virtual RepoItemInfo OracleServer199Info
            {
                get
                {
                    return _oracleserver199Info;
                }
            }

            /// <summary>
            /// The MySchema item.
            /// </summary>
            [RepositoryItem("69402a40-8727-44b9-b170-e1aaff8b0031")]
            public virtual Ranorex.TreeItem MySchema
            {
                get
                {
                    return _myschemaInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The MySchema item info.
            /// </summary>
            [RepositoryItemInfo("69402a40-8727-44b9-b170-e1aaff8b0031")]
            public virtual RepoItemInfo MySchemaInfo
            {
                get
                {
                    return _myschemaInfo;
                }
            }

            /// <summary>
            /// The Storage item.
            /// </summary>
            [RepositoryItem("1a856a20-74bd-42e4-9e8d-eddbae096e57")]
            public virtual Ranorex.TreeItem Storage
            {
                get
                {
                    return _storageInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Storage item info.
            /// </summary>
            [RepositoryItemInfo("1a856a20-74bd-42e4-9e8d-eddbae096e57")]
            public virtual RepoItemInfo StorageInfo
            {
                get
                {
                    return _storageInfo;
                }
            }

            /// <summary>
            /// The Management item.
            /// </summary>
            [RepositoryItem("e6e511a5-0a7b-4b4e-a2d9-07576819ffb9")]
            public virtual Ranorex.TreeItem Management
            {
                get
                {
                    return _managementInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Management item info.
            /// </summary>
            [RepositoryItemInfo("e6e511a5-0a7b-4b4e-a2d9-07576819ffb9")]
            public virtual RepoItemInfo ManagementInfo
            {
                get
                {
                    return _managementInfo;
                }
            }

            /// <summary>
            /// The SQLServer1722411542017 item.
            /// </summary>
            [RepositoryItem("5a5162e3-402d-4ace-9b86-4855454b9fc1")]
            public virtual Ranorex.TreeItem SQLServer1722411542017
            {
                get
                {
                    return _sqlserver1722411542017Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The SQLServer1722411542017 item info.
            /// </summary>
            [RepositoryItemInfo("5a5162e3-402d-4ace-9b86-4855454b9fc1")]
            public virtual RepoItemInfo SQLServer1722411542017Info
            {
                get
                {
                    return _sqlserver1722411542017Info;
                }
            }

            /// <summary>
            /// The SQLServerManagement item.
            /// </summary>
            [RepositoryItem("9d404c67-ebeb-4d00-9427-0c86139381f7")]
            public virtual Ranorex.TreeItem SQLServerManagement
            {
                get
                {
                    return _sqlservermanagementInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The SQLServerManagement item info.
            /// </summary>
            [RepositoryItemInfo("9d404c67-ebeb-4d00-9427-0c86139381f7")]
            public virtual RepoItemInfo SQLServerManagementInfo
            {
                get
                {
                    return _sqlservermanagementInfo;
                }
            }

            /// <summary>
            /// The ToolWindowHeaderDollar1 item.
            /// </summary>
            [RepositoryItem("5fc4aadb-cf8c-4b4f-a0f0-f8fba81c5ef7")]
            public virtual Ranorex.Container ToolWindowHeaderDollar1
            {
                get
                {
                    return _toolwindowheaderdollar1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ToolWindowHeaderDollar1 item info.
            /// </summary>
            [RepositoryItemInfo("5fc4aadb-cf8c-4b4f-a0f0-f8fba81c5ef7")]
            public virtual RepoItemInfo ToolWindowHeaderDollar1Info
            {
                get
                {
                    return _toolwindowheaderdollar1Info;
                }
            }
        }

        /// <summary>
        /// The NewServerGroupAppFolder folder.
        /// </summary>
        [RepositoryFolder("1708bbc2-a4fa-4e11-8c4f-9f5990351ff8")]
        public partial class NewServerGroupAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _optionpanetextfieldInfo;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new NewServerGroup  folder.
            /// </summary>
            public NewServerGroupAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NewServerGroup", "/form[@title='New Server Group']", parentFolder, 30000, null, false, "1708bbc2-a4fa-4e11-8c4f-9f5990351ff8", "")
            {
                _optionpanetextfieldInfo = new RepoItemInfo(this, "OptionPaneTextField", ".//container[@name='OptionPane.realBody']/container[@name='OptionPane.body']/text[@name='OptionPane.textField']", 30000, null, "1d351359-168c-4a59-af6e-1c56dc40d3a0");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "?/?/container[@name='OptionPane.buttonArea']/button[@text='OK']", 30000, null, "5a009c5a-620b-4ad0-8002-248596d390e2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1708bbc2-a4fa-4e11-8c4f-9f5990351ff8")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1708bbc2-a4fa-4e11-8c4f-9f5990351ff8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OptionPaneTextField item.
            /// </summary>
            [RepositoryItem("1d351359-168c-4a59-af6e-1c56dc40d3a0")]
            public virtual Ranorex.Text OptionPaneTextField
            {
                get
                {
                    return _optionpanetextfieldInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The OptionPaneTextField item info.
            /// </summary>
            [RepositoryItemInfo("1d351359-168c-4a59-af6e-1c56dc40d3a0")]
            public virtual RepoItemInfo OptionPaneTextFieldInfo
            {
                get
                {
                    return _optionpanetextfieldInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("5a009c5a-620b-4ad0-8002-248596d390e2")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("5a009c5a-620b-4ad0-8002-248596d390e2")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The ServersAppFolder folder.
        /// </summary>
        [RepositoryFolder("84ea137a-f58e-4bc0-ab31-b6ffd6c0c4e8")]
        public partial class ServersAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _serverstoolbarpanelInfo;

            /// <summary>
            /// Creates a new Servers  folder.
            /// </summary>
            public ServersAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Servers", "/form[@title='Servers']", parentFolder, 30000, null, false, "84ea137a-f58e-4bc0-ab31-b6ffd6c0c4e8", "")
            {
                _serverstoolbarpanelInfo = new RepoItemInfo(this, "ServersToolbarPanel", "container[@name='myInternalDecorator']//container[@type='ToolWindowHeader$1']", 30000, null, "56b442aa-48e0-4f5e-a3bd-531f67baedeb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("84ea137a-f58e-4bc0-ab31-b6ffd6c0c4e8")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("84ea137a-f58e-4bc0-ab31-b6ffd6c0c4e8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ServersToolbarPanel item.
            /// </summary>
            [RepositoryItem("56b442aa-48e0-4f5e-a3bd-531f67baedeb")]
            public virtual Ranorex.Container ServersToolbarPanel
            {
                get
                {
                    return _serverstoolbarpanelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ServersToolbarPanel item info.
            /// </summary>
            [RepositoryItemInfo("56b442aa-48e0-4f5e-a3bd-531f67baedeb")]
            public virtual RepoItemInfo ServersToolbarPanelInfo
            {
                get
                {
                    return _serverstoolbarpanelInfo;
                }
            }
        }

        /// <summary>
        /// The RemoveServerGroupAppFolder folder.
        /// </summary>
        [RepositoryFolder("67bf9665-9da3-46ea-ae4a-7b2edd43e269")]
        public partial class RemoveServerGroupAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _deleteworkgroupyesbuttonInfo;

            /// <summary>
            /// Creates a new RemoveServerGroup  folder.
            /// </summary>
            public RemoveServerGroupAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RemoveServerGroup", "/form[@title='Remove Server Group']", parentFolder, 30000, null, false, "67bf9665-9da3-46ea-ae4a-7b2edd43e269", "")
            {
                _deleteworkgroupyesbuttonInfo = new RepoItemInfo(this, "DeleteworkgroupYesbutton", "?/?/container[@name='OptionPane.buttonArea']/button[@text='Yes']", 30000, null, "c6c040cc-7193-4966-811a-befd65950eab");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("67bf9665-9da3-46ea-ae4a-7b2edd43e269")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("67bf9665-9da3-46ea-ae4a-7b2edd43e269")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DeleteworkgroupYesbutton item.
            /// </summary>
            [RepositoryItem("c6c040cc-7193-4966-811a-befd65950eab")]
            public virtual Ranorex.Button DeleteworkgroupYesbutton
            {
                get
                {
                    return _deleteworkgroupyesbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DeleteworkgroupYesbutton item info.
            /// </summary>
            [RepositoryItemInfo("c6c040cc-7193-4966-811a-befd65950eab")]
            public virtual RepoItemInfo DeleteworkgroupYesbuttonInfo
            {
                get
                {
                    return _deleteworkgroupyesbuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}