///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ADSAutomationPhaseIII.TC_10587
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TC10587 element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("af3ddc0c-32bd-4a47-95a1-aa516ac35d09")]
    public partial class TC10587 : RepoGenBaseFolder
    {
        static TC10587 instance = new TC10587();
        TC10587Folders.ApplicationAppFolder _application;
        TC10587Folders.DatastudioAppFolder _datastudio;
        TC10587Folders.ConfigurationAppFolder _configuration;
        TC10587Folders.CheckoutAppFolder _checkout;
        TC10587Folders.Datastudio1AppFolder _datastudio1;
        TC10587Folders.Datastudio2AppFolder _datastudio2;
        TC10587Folders.CreateFileAppFolder _createfile;
        TC10587Folders.MarkForAddAppFolder _markforadd;
        TC10587Folders.SunAwtWindowAppFolder _sunawtwindow;
        TC10587Folders.CommitAppFolder _commit;
        TC10587Folders.UpdateAppFolder _update;
        TC10587Folders.TextEditorAppFolder _texteditor;
        TC10587Folders.UnMountAppFolder _unmount;
        TC10587Folders.AquaDataStudioAppFolder _aquadatastudio;
        TC10587Folders.PerforceServerAppFolder _perforceserver;
        TC10587Folders.EditAppFolder _edit;
        TC10587Folders.HistoryAppFolder _history;
        TC10587Folders.CompareWindowAppFolder _comparewindow;

        /// <summary>
        /// Gets the singleton class instance representing the TC10587 element repository.
        /// </summary>
        [RepositoryFolder("af3ddc0c-32bd-4a47-95a1-aa516ac35d09")]
        public static TC10587 Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TC10587() 
            : base("TC10587", "/", null, 0, false, "af3ddc0c-32bd-4a47-95a1-aa516ac35d09", ".\\RepositoryImages\\TC10587af3ddc0c.rximgres")
        {
            _application = new TC10587Folders.ApplicationAppFolder(this);
            _datastudio = new TC10587Folders.DatastudioAppFolder(this);
            _configuration = new TC10587Folders.ConfigurationAppFolder(this);
            _checkout = new TC10587Folders.CheckoutAppFolder(this);
            _datastudio1 = new TC10587Folders.Datastudio1AppFolder(this);
            _datastudio2 = new TC10587Folders.Datastudio2AppFolder(this);
            _createfile = new TC10587Folders.CreateFileAppFolder(this);
            _markforadd = new TC10587Folders.MarkForAddAppFolder(this);
            _sunawtwindow = new TC10587Folders.SunAwtWindowAppFolder(this);
            _commit = new TC10587Folders.CommitAppFolder(this);
            _update = new TC10587Folders.UpdateAppFolder(this);
            _texteditor = new TC10587Folders.TextEditorAppFolder(this);
            _unmount = new TC10587Folders.UnMountAppFolder(this);
            _aquadatastudio = new TC10587Folders.AquaDataStudioAppFolder(this);
            _perforceserver = new TC10587Folders.PerforceServerAppFolder(this);
            _edit = new TC10587Folders.EditAppFolder(this);
            _history = new TC10587Folders.HistoryAppFolder(this);
            _comparewindow = new TC10587Folders.CompareWindowAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("af3ddc0c-32bd-4a47-95a1-aa516ac35d09")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Application folder.
        /// </summary>
        [RepositoryFolder("f94e07c3-b12b-4b44-8211-9b8edcb71531")]
        public virtual TC10587Folders.ApplicationAppFolder Application
        {
            get { return _application; }
        }

        /// <summary>
        /// The Datastudio folder.
        /// </summary>
        [RepositoryFolder("a69bb51a-6550-46d8-927c-ef4a7502a18f")]
        public virtual TC10587Folders.DatastudioAppFolder Datastudio
        {
            get { return _datastudio; }
        }

        /// <summary>
        /// The Configuration folder.
        /// </summary>
        [RepositoryFolder("948b5838-3038-4af9-9c07-fa32bc325efe")]
        public virtual TC10587Folders.ConfigurationAppFolder Configuration
        {
            get { return _configuration; }
        }

        /// <summary>
        /// The Checkout folder.
        /// </summary>
        [RepositoryFolder("2346cbb4-f5a8-4588-a0e3-3cd8aa94af36")]
        public virtual TC10587Folders.CheckoutAppFolder Checkout
        {
            get { return _checkout; }
        }

        /// <summary>
        /// The Datastudio1 folder.
        /// </summary>
        [RepositoryFolder("67991ba3-0bd7-470d-aa69-4b379c6acb01")]
        public virtual TC10587Folders.Datastudio1AppFolder Datastudio1
        {
            get { return _datastudio1; }
        }

        /// <summary>
        /// The Datastudio2 folder.
        /// </summary>
        [RepositoryFolder("4f47d9c0-8f14-46a3-9b4c-5884ff95a3bc")]
        public virtual TC10587Folders.Datastudio2AppFolder Datastudio2
        {
            get { return _datastudio2; }
        }

        /// <summary>
        /// The CreateFile folder.
        /// </summary>
        [RepositoryFolder("645d3097-2280-49a1-9b20-3b9039febc18")]
        public virtual TC10587Folders.CreateFileAppFolder CreateFile
        {
            get { return _createfile; }
        }

        /// <summary>
        /// The MarkForAdd folder.
        /// </summary>
        [RepositoryFolder("12df0a1a-8bee-422b-9301-3e4a057bd407")]
        public virtual TC10587Folders.MarkForAddAppFolder MarkForAdd
        {
            get { return _markforadd; }
        }

        /// <summary>
        /// The SunAwtWindow folder.
        /// </summary>
        [RepositoryFolder("83b767b9-ab3e-4693-932a-3ac8ed432cdd")]
        public virtual TC10587Folders.SunAwtWindowAppFolder SunAwtWindow
        {
            get { return _sunawtwindow; }
        }

        /// <summary>
        /// The Commit folder.
        /// </summary>
        [RepositoryFolder("adab8236-d5b8-41bd-b168-291958b006a8")]
        public virtual TC10587Folders.CommitAppFolder Commit
        {
            get { return _commit; }
        }

        /// <summary>
        /// The Update folder.
        /// </summary>
        [RepositoryFolder("f1871d75-58cf-4b3f-a272-a21c7521ca80")]
        public virtual TC10587Folders.UpdateAppFolder Update
        {
            get { return _update; }
        }

        /// <summary>
        /// The TextEditor folder.
        /// </summary>
        [RepositoryFolder("b80144d5-58ae-4324-8ae5-56b3c4f78b7f")]
        public virtual TC10587Folders.TextEditorAppFolder TextEditor
        {
            get { return _texteditor; }
        }

        /// <summary>
        /// The UnMount folder.
        /// </summary>
        [RepositoryFolder("29c74b0e-aa80-4b4a-94d8-78fafba1c005")]
        public virtual TC10587Folders.UnMountAppFolder UnMount
        {
            get { return _unmount; }
        }

        /// <summary>
        /// The AquaDataStudio folder.
        /// </summary>
        [RepositoryFolder("229a8614-b5ff-4306-a25c-53fe35c18ccc")]
        public virtual TC10587Folders.AquaDataStudioAppFolder AquaDataStudio
        {
            get { return _aquadatastudio; }
        }

        /// <summary>
        /// The PerforceServer folder.
        /// </summary>
        [RepositoryFolder("e7aad77b-a1a4-4eb2-b8f2-3d7c2d4a137f")]
        public virtual TC10587Folders.PerforceServerAppFolder PerforceServer
        {
            get { return _perforceserver; }
        }

        /// <summary>
        /// The Edit folder.
        /// </summary>
        [RepositoryFolder("2ff260e7-e139-4f49-bf16-e2c6a7a834ef")]
        public virtual TC10587Folders.EditAppFolder Edit
        {
            get { return _edit; }
        }

        /// <summary>
        /// The History folder.
        /// </summary>
        [RepositoryFolder("b5e38b6a-8e40-4757-ad89-a988e664fba0")]
        public virtual TC10587Folders.HistoryAppFolder History
        {
            get { return _history; }
        }

        /// <summary>
        /// The CompareWindow folder.
        /// </summary>
        [RepositoryFolder("a96f8cbc-49dd-46ca-87a6-c034c208a89f")]
        public virtual TC10587Folders.CompareWindowAppFolder CompareWindow
        {
            get { return _comparewindow; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class TC10587Folders
    {
        /// <summary>
        /// The ApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("f94e07c3-b12b-4b44-8211-9b8edcb71531")]
        public partial class ApplicationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _filestabInfo;
            RepoItemInfo _filesystemInfo;
            RepoItemInfo _filesInfo;
            RepoItemInfo _repositorypath2Info;
            RepoItemInfo _testfileInfo;
            RepoItemInfo _repositorypath1Info;
            RepoItemInfo _serverstabInfo;
            RepoItemInfo _newitemInfo;

            /// <summary>
            /// Creates a new Application  folder.
            /// </summary>
            public ApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Application", "/form[@title='Aqua Data Studio']", parentFolder, 30000, null, true, "f94e07c3-b12b-4b44-8211-9b8edcb71531", "")
            {
                _filestabInfo = new RepoItemInfo(this, "FilesTab", ".//container[@name='myLeftStripe']/checkbox[@text='F2: Files']", 30000, null, "2069a025-e089-48fc-bfc4-2dfeb95ae8de");
                _filesystemInfo = new RepoItemInfo(this, "FileSystem", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//container[@name='viewport']/tree[@name='scriptTree']/treeitem[@text='Filesystem']", 30000, null, "2d2b8687-a283-471a-8f24-1809711c2ee4");
                _filesInfo = new RepoItemInfo(this, "Files", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//container[@name='viewport']/tree[@name='scriptTree']/treeitem[@text='Filesystem']", 30000, null, "e4885c38-51ee-44af-a26e-a0ff216fabfb");
                _repositorypath2Info = new RepoItemInfo(this, "RepositoryPath2", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//container[@name='viewport']/tree[@name='scriptTree']/treeitem/treeitem[2]", 30000, null, "6d9220b2-f319-4217-8061-a38853bca290");
                _testfileInfo = new RepoItemInfo(this, "TestFile", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='scriptTree']//treeitem[@text='Test5.sql']", 30000, null, "8c80f26c-c7f8-410d-9d0a-2d122d339df0");
                _repositorypath1Info = new RepoItemInfo(this, "RepositoryPath1", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//container[@name='viewport']/tree[@name='scriptTree']/treeitem/treeitem[@text='C:\\Users\\Admin\\Documents\\Aqua Data Studio Repository']", 30000, null, "fa49097f-8349-45a9-915f-98080d127301");
                _serverstabInfo = new RepoItemInfo(this, "ServersTab", ".//container[@name='myLeftStripe']/checkbox[@text='F1: Servers']", 30000, null, "c11cd4eb-1ce3-442f-991e-b433640b1fdc");
                _newitemInfo = new RepoItemInfo(this, "NewItem", "element", 30000, null, "224e5ca9-f5fa-4886-873f-6efd9a20386c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f94e07c3-b12b-4b44-8211-9b8edcb71531")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f94e07c3-b12b-4b44-8211-9b8edcb71531")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FilesTab item.
            /// </summary>
            [RepositoryItem("2069a025-e089-48fc-bfc4-2dfeb95ae8de")]
            public virtual Ranorex.CheckBox FilesTab
            {
                get
                {
                    return _filestabInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The FilesTab item info.
            /// </summary>
            [RepositoryItemInfo("2069a025-e089-48fc-bfc4-2dfeb95ae8de")]
            public virtual RepoItemInfo FilesTabInfo
            {
                get
                {
                    return _filestabInfo;
                }
            }

            /// <summary>
            /// The FileSystem item.
            /// </summary>
            [RepositoryItem("2d2b8687-a283-471a-8f24-1809711c2ee4")]
            public virtual Ranorex.TreeItem FileSystem
            {
                get
                {
                    return _filesystemInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The FileSystem item info.
            /// </summary>
            [RepositoryItemInfo("2d2b8687-a283-471a-8f24-1809711c2ee4")]
            public virtual RepoItemInfo FileSystemInfo
            {
                get
                {
                    return _filesystemInfo;
                }
            }

            /// <summary>
            /// The Files item.
            /// </summary>
            [RepositoryItem("e4885c38-51ee-44af-a26e-a0ff216fabfb")]
            public virtual Ranorex.TreeItem Files
            {
                get
                {
                    return _filesInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Files item info.
            /// </summary>
            [RepositoryItemInfo("e4885c38-51ee-44af-a26e-a0ff216fabfb")]
            public virtual RepoItemInfo FilesInfo
            {
                get
                {
                    return _filesInfo;
                }
            }

            /// <summary>
            /// The RepositoryPath2 item.
            /// </summary>
            [RepositoryItem("6d9220b2-f319-4217-8061-a38853bca290")]
            public virtual Ranorex.TreeItem RepositoryPath2
            {
                get
                {
                    return _repositorypath2Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The RepositoryPath2 item info.
            /// </summary>
            [RepositoryItemInfo("6d9220b2-f319-4217-8061-a38853bca290")]
            public virtual RepoItemInfo RepositoryPath2Info
            {
                get
                {
                    return _repositorypath2Info;
                }
            }

            /// <summary>
            /// The TestFile item.
            /// </summary>
            [RepositoryItem("8c80f26c-c7f8-410d-9d0a-2d122d339df0")]
            public virtual Ranorex.TreeItem TestFile
            {
                get
                {
                    return _testfileInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The TestFile item info.
            /// </summary>
            [RepositoryItemInfo("8c80f26c-c7f8-410d-9d0a-2d122d339df0")]
            public virtual RepoItemInfo TestFileInfo
            {
                get
                {
                    return _testfileInfo;
                }
            }

            /// <summary>
            /// The RepositoryPath1 item.
            /// </summary>
            [RepositoryItem("fa49097f-8349-45a9-915f-98080d127301")]
            public virtual Ranorex.TreeItem RepositoryPath1
            {
                get
                {
                    return _repositorypath1Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The RepositoryPath1 item info.
            /// </summary>
            [RepositoryItemInfo("fa49097f-8349-45a9-915f-98080d127301")]
            public virtual RepoItemInfo RepositoryPath1Info
            {
                get
                {
                    return _repositorypath1Info;
                }
            }

            /// <summary>
            /// The ServersTab item.
            /// </summary>
            [RepositoryItem("c11cd4eb-1ce3-442f-991e-b433640b1fdc")]
            public virtual Ranorex.CheckBox ServersTab
            {
                get
                {
                    return _serverstabInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ServersTab item info.
            /// </summary>
            [RepositoryItemInfo("c11cd4eb-1ce3-442f-991e-b433640b1fdc")]
            public virtual RepoItemInfo ServersTabInfo
            {
                get
                {
                    return _serverstabInfo;
                }
            }

            /// <summary>
            /// The NewItem item.
            /// </summary>
            [RepositoryItem("224e5ca9-f5fa-4886-873f-6efd9a20386c")]
            public virtual Ranorex.Unknown NewItem
            {
                get
                {
                    return _newitemInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The NewItem item info.
            /// </summary>
            [RepositoryItemInfo("224e5ca9-f5fa-4886-873f-6efd9a20386c")]
            public virtual RepoItemInfo NewItemInfo
            {
                get
                {
                    return _newitemInfo;
                }
            }
        }

        /// <summary>
        /// The DatastudioAppFolder folder.
        /// </summary>
        [RepositoryFolder("a69bb51a-6550-46d8-927c-ef4a7502a18f")]
        public partial class DatastudioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _versioncontrolInfo;
            RepoItemInfo _perforceInfo;
            RepoItemInfo _checkoutInfo;
            RepoItemInfo _newInfo;
            RepoItemInfo _markforaddInfo;
            RepoItemInfo _unmountInfo;

            /// <summary>
            /// Creates a new Datastudio  folder.
            /// </summary>
            public DatastudioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Datastudio", "/form[@processname='datastudio']", parentFolder, 30000, null, true, "a69bb51a-6550-46d8-927c-ef4a7502a18f", "")
            {
                _versioncontrolInfo = new RepoItemInfo(this, "VersionControl", ".//menuitem[@text='Version Control']", 30000, null, "6edec237-24c7-4356-8bce-007ba4f92591");
                _perforceInfo = new RepoItemInfo(this, "Perforce", ".//menuitem[@text='Perforce']", 30000, null, "cb4e3a99-66fa-4ade-b9aa-40aafcae5c90");
                _checkoutInfo = new RepoItemInfo(this, "Checkout", ".//menuitem[@text='Checkout']", 30000, null, "19764f1c-156b-4475-ad7a-930c374f6de8");
                _newInfo = new RepoItemInfo(this, "New", ".//menuitem[@text='New']", 30000, null, "ed81c5f6-b62a-4677-8b9d-ba0c785234e0");
                _markforaddInfo = new RepoItemInfo(this, "MarkForAdd", ".//menuitem[@text='Mark for Add']", 30000, null, "e7813c21-5811-4c49-9606-d6fb97eb3b36");
                _unmountInfo = new RepoItemInfo(this, "UnMount", ".//menuitem[@text='Unmount Directory']", 30000, null, "45476586-10b2-4273-9ea0-2d250174e896");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a69bb51a-6550-46d8-927c-ef4a7502a18f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a69bb51a-6550-46d8-927c-ef4a7502a18f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The VersionControl item.
            /// </summary>
            [RepositoryItem("6edec237-24c7-4356-8bce-007ba4f92591")]
            public virtual Ranorex.MenuItem VersionControl
            {
                get
                {
                    return _versioncontrolInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The VersionControl item info.
            /// </summary>
            [RepositoryItemInfo("6edec237-24c7-4356-8bce-007ba4f92591")]
            public virtual RepoItemInfo VersionControlInfo
            {
                get
                {
                    return _versioncontrolInfo;
                }
            }

            /// <summary>
            /// The Perforce item.
            /// </summary>
            [RepositoryItem("cb4e3a99-66fa-4ade-b9aa-40aafcae5c90")]
            public virtual Ranorex.MenuItem Perforce
            {
                get
                {
                    return _perforceInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Perforce item info.
            /// </summary>
            [RepositoryItemInfo("cb4e3a99-66fa-4ade-b9aa-40aafcae5c90")]
            public virtual RepoItemInfo PerforceInfo
            {
                get
                {
                    return _perforceInfo;
                }
            }

            /// <summary>
            /// The Checkout item.
            /// </summary>
            [RepositoryItem("19764f1c-156b-4475-ad7a-930c374f6de8")]
            public virtual Ranorex.MenuItem Checkout
            {
                get
                {
                    return _checkoutInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Checkout item info.
            /// </summary>
            [RepositoryItemInfo("19764f1c-156b-4475-ad7a-930c374f6de8")]
            public virtual RepoItemInfo CheckoutInfo
            {
                get
                {
                    return _checkoutInfo;
                }
            }

            /// <summary>
            /// The New item.
            /// </summary>
            [RepositoryItem("ed81c5f6-b62a-4677-8b9d-ba0c785234e0")]
            public virtual Ranorex.MenuItem New
            {
                get
                {
                    return _newInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The New item info.
            /// </summary>
            [RepositoryItemInfo("ed81c5f6-b62a-4677-8b9d-ba0c785234e0")]
            public virtual RepoItemInfo NewInfo
            {
                get
                {
                    return _newInfo;
                }
            }

            /// <summary>
            /// The MarkForAdd item.
            /// </summary>
            [RepositoryItem("e7813c21-5811-4c49-9606-d6fb97eb3b36")]
            public virtual Ranorex.MenuItem MarkForAdd
            {
                get
                {
                    return _markforaddInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MarkForAdd item info.
            /// </summary>
            [RepositoryItemInfo("e7813c21-5811-4c49-9606-d6fb97eb3b36")]
            public virtual RepoItemInfo MarkForAddInfo
            {
                get
                {
                    return _markforaddInfo;
                }
            }

            /// <summary>
            /// The UnMount item.
            /// </summary>
            [RepositoryItem("45476586-10b2-4273-9ea0-2d250174e896")]
            public virtual Ranorex.MenuItem UnMount
            {
                get
                {
                    return _unmountInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The UnMount item info.
            /// </summary>
            [RepositoryItemInfo("45476586-10b2-4273-9ea0-2d250174e896")]
            public virtual RepoItemInfo UnMountInfo
            {
                get
                {
                    return _unmountInfo;
                }
            }
        }

        /// <summary>
        /// The ConfigurationAppFolder folder.
        /// </summary>
        [RepositoryFolder("948b5838-3038-4af9-9c07-fa32bc325efe")]
        public partial class ConfigurationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _urlInfo;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _workspaceInfo;
            RepoItemInfo _folderInfo;
            RepoItemInfo _okbuttonInfo;
            RepoItemInfo _createnewperforceInfo;
            RepoItemInfo _selectexistingInfo;

            /// <summary>
            /// Creates a new Configuration  folder.
            /// </summary>
            public ConfigurationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Configuration", "/form[@title='Configure Version Control']", parentFolder, 30000, null, true, "948b5838-3038-4af9-9c07-fa32bc325efe", "")
            {
                _urlInfo = new RepoItemInfo(this, "Url", ".//container[@type='JPanel']/container[@accessiblename='General   ']/container[@type='JPanel']/?/?/container[@name='configPanel']//text[@name='serverUrlField']", 30000, null, "aaaa094e-25f5-43e6-8aad-b1f60133efca");
                _usernameInfo = new RepoItemInfo(this, "Username", ".//container[@type='JPanel']/container[@accessiblename='General   ']/container[@type='JPanel']/?/?/container[@name='configPanel']//text[@name='usernameField']", 30000, null, "fb34da4f-6346-423d-81f2-c05c23a3cf91");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//container[@type='JPanel']/container[@accessiblename='General   ']/container[@type='JPanel']/?/?/container[@name='configPanel']//text[@name='passwordField']", 30000, null, "d49ca6cf-a5cb-4519-b75a-daec2ea6b9ae");
                _workspaceInfo = new RepoItemInfo(this, "Workspace", ".//container[@type='JPanel']/container[@accessiblename='General   ']/container[@type='JPanel']/?/?/container[@name='configPanel']/?/?/container[@type='CPanel']/container[@type='JPanel']/text[12]", 30000, null, "6274c073-eaae-415f-b623-3cae1f5c55b0");
                _folderInfo = new RepoItemInfo(this, "Folder", ".//container[@type='JPanel']/container[@accessiblename='General   ']/container[@type='JPanel']/?/?/container[@name='configPanel']/?/?/container[@type='CPanel']/container[@type='JPanel']/text[14]", 30000, null, "0c2fe8c3-210b-486b-a20e-902f53d061b9");
                _okbuttonInfo = new RepoItemInfo(this, "OkButton", ".//container[@type='JPanel']/?/?/button[@text='OK']", 30000, null, "583d9975-ea4b-4379-ab53-cc5f18a7ff1e");
                _createnewperforceInfo = new RepoItemInfo(this, "CreateNewPerforce", ".//container[@type='JPanel']/container[@accessiblename='General   ']/container[@type='JPanel']/?/?/container[@name='configPanel']//radiobutton[@name='configNewButton']", 30000, null, "6f9dc662-5aa9-4046-a0a9-f847a709cdae");
                _selectexistingInfo = new RepoItemInfo(this, "SelectExisting", ".//container[@type='JPanel']/container[@accessiblename='General   ']/container[@type='JPanel']/?/?/container[@name='configPanel']//radiobutton[@name='configExistingButton']", 30000, null, "b0b4914e-c3fd-43bb-a4d7-770e8470a19f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("948b5838-3038-4af9-9c07-fa32bc325efe")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("948b5838-3038-4af9-9c07-fa32bc325efe")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Url item.
            /// </summary>
            [RepositoryItem("aaaa094e-25f5-43e6-8aad-b1f60133efca")]
            public virtual Ranorex.Text Url
            {
                get
                {
                    return _urlInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Url item info.
            /// </summary>
            [RepositoryItemInfo("aaaa094e-25f5-43e6-8aad-b1f60133efca")]
            public virtual RepoItemInfo UrlInfo
            {
                get
                {
                    return _urlInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("fb34da4f-6346-423d-81f2-c05c23a3cf91")]
            public virtual Ranorex.Text Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("fb34da4f-6346-423d-81f2-c05c23a3cf91")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("d49ca6cf-a5cb-4519-b75a-daec2ea6b9ae")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("d49ca6cf-a5cb-4519-b75a-daec2ea6b9ae")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Workspace item.
            /// </summary>
            [RepositoryItem("6274c073-eaae-415f-b623-3cae1f5c55b0")]
            public virtual Ranorex.Text Workspace
            {
                get
                {
                    return _workspaceInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Workspace item info.
            /// </summary>
            [RepositoryItemInfo("6274c073-eaae-415f-b623-3cae1f5c55b0")]
            public virtual RepoItemInfo WorkspaceInfo
            {
                get
                {
                    return _workspaceInfo;
                }
            }

            /// <summary>
            /// The Folder item.
            /// </summary>
            [RepositoryItem("0c2fe8c3-210b-486b-a20e-902f53d061b9")]
            public virtual Ranorex.Text Folder
            {
                get
                {
                    return _folderInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Folder item info.
            /// </summary>
            [RepositoryItemInfo("0c2fe8c3-210b-486b-a20e-902f53d061b9")]
            public virtual RepoItemInfo FolderInfo
            {
                get
                {
                    return _folderInfo;
                }
            }

            /// <summary>
            /// The OkButton item.
            /// </summary>
            [RepositoryItem("583d9975-ea4b-4379-ab53-cc5f18a7ff1e")]
            public virtual Ranorex.Button OkButton
            {
                get
                {
                    return _okbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OkButton item info.
            /// </summary>
            [RepositoryItemInfo("583d9975-ea4b-4379-ab53-cc5f18a7ff1e")]
            public virtual RepoItemInfo OkButtonInfo
            {
                get
                {
                    return _okbuttonInfo;
                }
            }

            /// <summary>
            /// The CreateNewPerforce item.
            /// </summary>
            [RepositoryItem("6f9dc662-5aa9-4046-a0a9-f847a709cdae")]
            public virtual Ranorex.RadioButton CreateNewPerforce
            {
                get
                {
                    return _createnewperforceInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The CreateNewPerforce item info.
            /// </summary>
            [RepositoryItemInfo("6f9dc662-5aa9-4046-a0a9-f847a709cdae")]
            public virtual RepoItemInfo CreateNewPerforceInfo
            {
                get
                {
                    return _createnewperforceInfo;
                }
            }

            /// <summary>
            /// The SelectExisting item.
            /// </summary>
            [RepositoryItem("b0b4914e-c3fd-43bb-a4d7-770e8470a19f")]
            public virtual Ranorex.RadioButton SelectExisting
            {
                get
                {
                    return _selectexistingInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The SelectExisting item info.
            /// </summary>
            [RepositoryItemInfo("b0b4914e-c3fd-43bb-a4d7-770e8470a19f")]
            public virtual RepoItemInfo SelectExistingInfo
            {
                get
                {
                    return _selectexistingInfo;
                }
            }
        }

        /// <summary>
        /// The CheckoutAppFolder folder.
        /// </summary>
        [RepositoryFolder("2346cbb4-f5a8-4588-a0e3-3cd8aa94af36")]
        public partial class CheckoutAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _okbuttonInfo;

            /// <summary>
            /// Creates a new Checkout  folder.
            /// </summary>
            public CheckoutAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Checkout", "/form[@title='Checkout']", parentFolder, 30000, null, true, "2346cbb4-f5a8-4588-a0e3-3cd8aa94af36", "")
            {
                _okbuttonInfo = new RepoItemInfo(this, "OkButton", ".//container[@name='panel']//button[@text='OK']", 30000, null, "acd3a936-2a72-4738-b938-f670777fa1fb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2346cbb4-f5a8-4588-a0e3-3cd8aa94af36")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2346cbb4-f5a8-4588-a0e3-3cd8aa94af36")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OkButton item.
            /// </summary>
            [RepositoryItem("acd3a936-2a72-4738-b938-f670777fa1fb")]
            public virtual Ranorex.Button OkButton
            {
                get
                {
                    return _okbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OkButton item info.
            /// </summary>
            [RepositoryItemInfo("acd3a936-2a72-4738-b938-f670777fa1fb")]
            public virtual RepoItemInfo OkButtonInfo
            {
                get
                {
                    return _okbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The Datastudio1AppFolder folder.
        /// </summary>
        [RepositoryFolder("67991ba3-0bd7-470d-aa69-4b379c6acb01")]
        public partial class Datastudio1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _perforceInfo;
            RepoItemInfo _browsedepotsInfo;
            RepoItemInfo _editworkspaceclientInfo;
            RepoItemInfo _showhistoryInfo;

            /// <summary>
            /// Creates a new Datastudio1  folder.
            /// </summary>
            public Datastudio1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Datastudio1", "/form[@class='SunAwtWindow' and @type='Popup$HeavyWeightWindow' and @fulltype='javax.swing.Popup$HeavyWeightWindow' and @instance='1']", parentFolder, 30000, null, false, "67991ba3-0bd7-470d-aa69-4b379c6acb01", "")
            {
                _perforceInfo = new RepoItemInfo(this, "Perforce", "?/?/menuitem[@text='Perforce']", 30000, null, "8a24b10a-6f1e-47e5-9859-c96720ed2b7a");
                _browsedepotsInfo = new RepoItemInfo(this, "BrowseDepots", ".//menuitem[@text='Browse Depot']", 30000, null, "d1b14fd4-8c87-4a63-ab9a-f86b63007011");
                _editworkspaceclientInfo = new RepoItemInfo(this, "EditWorkspaceClient", ".//menuitem[@text='Edit Workspace Client']", 30000, null, "1a61ef73-a5da-4f73-939c-eadf977e75e1");
                _showhistoryInfo = new RepoItemInfo(this, "ShowHistory", ".//menuitem[@text='Show History']", 30000, null, "e69bcd77-9612-4e18-899e-fafb116a9160");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("67991ba3-0bd7-470d-aa69-4b379c6acb01")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("67991ba3-0bd7-470d-aa69-4b379c6acb01")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Perforce item.
            /// </summary>
            [RepositoryItem("8a24b10a-6f1e-47e5-9859-c96720ed2b7a")]
            public virtual Ranorex.MenuItem Perforce
            {
                get
                {
                    return _perforceInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Perforce item info.
            /// </summary>
            [RepositoryItemInfo("8a24b10a-6f1e-47e5-9859-c96720ed2b7a")]
            public virtual RepoItemInfo PerforceInfo
            {
                get
                {
                    return _perforceInfo;
                }
            }

            /// <summary>
            /// The BrowseDepots item.
            /// </summary>
            [RepositoryItem("d1b14fd4-8c87-4a63-ab9a-f86b63007011")]
            public virtual Ranorex.MenuItem BrowseDepots
            {
                get
                {
                    return _browsedepotsInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The BrowseDepots item info.
            /// </summary>
            [RepositoryItemInfo("d1b14fd4-8c87-4a63-ab9a-f86b63007011")]
            public virtual RepoItemInfo BrowseDepotsInfo
            {
                get
                {
                    return _browsedepotsInfo;
                }
            }

            /// <summary>
            /// The EditWorkspaceClient item.
            /// </summary>
            [RepositoryItem("1a61ef73-a5da-4f73-939c-eadf977e75e1")]
            public virtual Ranorex.MenuItem EditWorkspaceClient
            {
                get
                {
                    return _editworkspaceclientInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The EditWorkspaceClient item info.
            /// </summary>
            [RepositoryItemInfo("1a61ef73-a5da-4f73-939c-eadf977e75e1")]
            public virtual RepoItemInfo EditWorkspaceClientInfo
            {
                get
                {
                    return _editworkspaceclientInfo;
                }
            }

            /// <summary>
            /// The ShowHistory item.
            /// </summary>
            [RepositoryItem("e69bcd77-9612-4e18-899e-fafb116a9160")]
            public virtual Ranorex.MenuItem ShowHistory
            {
                get
                {
                    return _showhistoryInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ShowHistory item info.
            /// </summary>
            [RepositoryItemInfo("e69bcd77-9612-4e18-899e-fafb116a9160")]
            public virtual RepoItemInfo ShowHistoryInfo
            {
                get
                {
                    return _showhistoryInfo;
                }
            }
        }

        /// <summary>
        /// The Datastudio2AppFolder folder.
        /// </summary>
        [RepositoryFolder("4f47d9c0-8f14-46a3-9b4c-5884ff95a3bc")]
        public partial class Datastudio2AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _checkoutInfo;

            /// <summary>
            /// Creates a new Datastudio2  folder.
            /// </summary>
            public Datastudio2AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Datastudio2", "/form[@class='SunAwtWindow' and @type='Popup$HeavyWeightWindow' and @fulltype='javax.swing.Popup$HeavyWeightWindow' and @instance='2']", parentFolder, 30000, null, false, "4f47d9c0-8f14-46a3-9b4c-5884ff95a3bc", "")
            {
                _checkoutInfo = new RepoItemInfo(this, "Checkout", "?/?/menuitem[@text='Checkout']", 30000, null, "140537b2-f980-4dc5-b978-df259b1707b2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4f47d9c0-8f14-46a3-9b4c-5884ff95a3bc")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4f47d9c0-8f14-46a3-9b4c-5884ff95a3bc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Checkout item.
            /// </summary>
            [RepositoryItem("140537b2-f980-4dc5-b978-df259b1707b2")]
            public virtual Ranorex.MenuItem Checkout
            {
                get
                {
                    return _checkoutInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Checkout item info.
            /// </summary>
            [RepositoryItemInfo("140537b2-f980-4dc5-b978-df259b1707b2")]
            public virtual RepoItemInfo CheckoutInfo
            {
                get
                {
                    return _checkoutInfo;
                }
            }
        }

        /// <summary>
        /// The CreateFileAppFolder folder.
        /// </summary>
        [RepositoryFolder("645d3097-2280-49a1-9b20-3b9039febc18")]
        public partial class CreateFileAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _nameInfo;
            RepoItemInfo _okbuttonInfo;

            /// <summary>
            /// Creates a new CreateFile  folder.
            /// </summary>
            public CreateFileAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CreateFile", "/form[@title='Create New File']", parentFolder, 30000, null, true, "645d3097-2280-49a1-9b20-3b9039febc18", "")
            {
                _nameInfo = new RepoItemInfo(this, "Name", ".//text[@name='nameField']", 30000, null, "6fece5b5-3d98-4110-b521-f305b176e3d0");
                _okbuttonInfo = new RepoItemInfo(this, "OkButton", ".//button[@text='OK']", 30000, null, "c7e8a7b1-a393-4d8c-9125-f8691b8da73c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("645d3097-2280-49a1-9b20-3b9039febc18")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("645d3097-2280-49a1-9b20-3b9039febc18")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Name item.
            /// </summary>
            [RepositoryItem("6fece5b5-3d98-4110-b521-f305b176e3d0")]
            public virtual Ranorex.Text Name
            {
                get
                {
                    return _nameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Name item info.
            /// </summary>
            [RepositoryItemInfo("6fece5b5-3d98-4110-b521-f305b176e3d0")]
            public virtual RepoItemInfo NameInfo
            {
                get
                {
                    return _nameInfo;
                }
            }

            /// <summary>
            /// The OkButton item.
            /// </summary>
            [RepositoryItem("c7e8a7b1-a393-4d8c-9125-f8691b8da73c")]
            public virtual Ranorex.Button OkButton
            {
                get
                {
                    return _okbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OkButton item info.
            /// </summary>
            [RepositoryItemInfo("c7e8a7b1-a393-4d8c-9125-f8691b8da73c")]
            public virtual RepoItemInfo OkButtonInfo
            {
                get
                {
                    return _okbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The MarkForAddAppFolder folder.
        /// </summary>
        [RepositoryFolder("12df0a1a-8bee-422b-9301-3e4a057bd407")]
        public partial class MarkForAddAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _okbuttonInfo;

            /// <summary>
            /// Creates a new MarkForAdd  folder.
            /// </summary>
            public MarkForAddAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MarkForAdd", "/form[@title~'^Mark\\ for\\ Add\\ -\\ C:\\\\Users\\\\A']", parentFolder, 30000, null, true, "12df0a1a-8bee-422b-9301-3e4a057bd407", "")
            {
                _okbuttonInfo = new RepoItemInfo(this, "OkButton", ".//container[@name='panel']//button[@text='OK']", 30000, null, "9ca0a3b7-fc45-4b88-9e75-224902606907");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("12df0a1a-8bee-422b-9301-3e4a057bd407")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("12df0a1a-8bee-422b-9301-3e4a057bd407")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OkButton item.
            /// </summary>
            [RepositoryItem("9ca0a3b7-fc45-4b88-9e75-224902606907")]
            public virtual Ranorex.Button OkButton
            {
                get
                {
                    return _okbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OkButton item info.
            /// </summary>
            [RepositoryItemInfo("9ca0a3b7-fc45-4b88-9e75-224902606907")]
            public virtual RepoItemInfo OkButtonInfo
            {
                get
                {
                    return _okbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The SunAwtWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("83b767b9-ab3e-4693-932a-3ac8ed432cdd")]
        public partial class SunAwtWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _commitInfo;
            RepoItemInfo _updatesyncInfo;
            RepoItemInfo _openInfo;
            RepoItemInfo _showchangesInfo;

            /// <summary>
            /// Creates a new SunAwtWindow  folder.
            /// </summary>
            public SunAwtWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SunAwtWindow", "/form[@class='SunAwtWindow']", parentFolder, 30000, null, true, "83b767b9-ab3e-4693-932a-3ac8ed432cdd", "")
            {
                _commitInfo = new RepoItemInfo(this, "Commit", ".//menuitem[@text='Commit...']", 30000, null, "5548eb17-e33f-4665-b3fc-76032a7edbfb");
                _updatesyncInfo = new RepoItemInfo(this, "UpdateSync", ".//menuitem[@text='Update (Sync)']", 30000, null, "832ffe28-1678-4eae-918e-1bf39b20c01c");
                _openInfo = new RepoItemInfo(this, "Open", ".//menuitem[@text='Open']", 30000, null, "aec8197e-46ef-4814-bf75-36a15076e15b");
                _showchangesInfo = new RepoItemInfo(this, "ShowChanges", ".//menuitem[@text='Show Changes']", 30000, null, "5551c6b6-da05-4176-b327-750a7534b72a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("83b767b9-ab3e-4693-932a-3ac8ed432cdd")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("83b767b9-ab3e-4693-932a-3ac8ed432cdd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Commit item.
            /// </summary>
            [RepositoryItem("5548eb17-e33f-4665-b3fc-76032a7edbfb")]
            public virtual Ranorex.MenuItem Commit
            {
                get
                {
                    return _commitInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Commit item info.
            /// </summary>
            [RepositoryItemInfo("5548eb17-e33f-4665-b3fc-76032a7edbfb")]
            public virtual RepoItemInfo CommitInfo
            {
                get
                {
                    return _commitInfo;
                }
            }

            /// <summary>
            /// The UpdateSync item.
            /// </summary>
            [RepositoryItem("832ffe28-1678-4eae-918e-1bf39b20c01c")]
            public virtual Ranorex.MenuItem UpdateSync
            {
                get
                {
                    return _updatesyncInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The UpdateSync item info.
            /// </summary>
            [RepositoryItemInfo("832ffe28-1678-4eae-918e-1bf39b20c01c")]
            public virtual RepoItemInfo UpdateSyncInfo
            {
                get
                {
                    return _updatesyncInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("aec8197e-46ef-4814-bf75-36a15076e15b")]
            public virtual Ranorex.MenuItem Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("aec8197e-46ef-4814-bf75-36a15076e15b")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The ShowChanges item.
            /// </summary>
            [RepositoryItem("5551c6b6-da05-4176-b327-750a7534b72a")]
            public virtual Ranorex.MenuItem ShowChanges
            {
                get
                {
                    return _showchangesInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ShowChanges item info.
            /// </summary>
            [RepositoryItemInfo("5551c6b6-da05-4176-b327-750a7534b72a")]
            public virtual RepoItemInfo ShowChangesInfo
            {
                get
                {
                    return _showchangesInfo;
                }
            }
        }

        /// <summary>
        /// The CommitAppFolder folder.
        /// </summary>
        [RepositoryFolder("adab8236-d5b8-41bd-b168-291958b006a8")]
        public partial class CommitAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _commitbuttonInfo;

            /// <summary>
            /// Creates a new Commit  folder.
            /// </summary>
            public CommitAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Commit", "/form[@title~'^Commit\\ -\\ C:\\\\Users\\\\Admin\\\\D']", parentFolder, 30000, null, true, "adab8236-d5b8-41bd-b168-291958b006a8", "")
            {
                _commitbuttonInfo = new RepoItemInfo(this, "CommitButton", ".//container[@type='JPanel']//button[@text='Commit']", 30000, null, "aabe01c0-ed3e-49a3-9fe4-ba115e23b715");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("adab8236-d5b8-41bd-b168-291958b006a8")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("adab8236-d5b8-41bd-b168-291958b006a8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CommitButton item.
            /// </summary>
            [RepositoryItem("aabe01c0-ed3e-49a3-9fe4-ba115e23b715")]
            public virtual Ranorex.Button CommitButton
            {
                get
                {
                    return _commitbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CommitButton item info.
            /// </summary>
            [RepositoryItemInfo("aabe01c0-ed3e-49a3-9fe4-ba115e23b715")]
            public virtual RepoItemInfo CommitButtonInfo
            {
                get
                {
                    return _commitbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The UpdateAppFolder folder.
        /// </summary>
        [RepositoryFolder("f1871d75-58cf-4b3f-a272-a21c7521ca80")]
        public partial class UpdateAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _okbuttonInfo;

            /// <summary>
            /// Creates a new Update  folder.
            /// </summary>
            public UpdateAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Update", "/form[@title~'^Update\\ -\\ C:\\\\Users\\\\Admin\\\\D']", parentFolder, 30000, null, true, "f1871d75-58cf-4b3f-a272-a21c7521ca80", "")
            {
                _okbuttonInfo = new RepoItemInfo(this, "OkButton", ".//container[@name='panel']//button[@text='OK']", 30000, null, "b886d5e7-f3c4-44f7-ad48-1b665eb22ccb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f1871d75-58cf-4b3f-a272-a21c7521ca80")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f1871d75-58cf-4b3f-a272-a21c7521ca80")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OkButton item.
            /// </summary>
            [RepositoryItem("b886d5e7-f3c4-44f7-ad48-1b665eb22ccb")]
            public virtual Ranorex.Button OkButton
            {
                get
                {
                    return _okbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OkButton item info.
            /// </summary>
            [RepositoryItemInfo("b886d5e7-f3c4-44f7-ad48-1b665eb22ccb")]
            public virtual RepoItemInfo OkButtonInfo
            {
                get
                {
                    return _okbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The TextEditorAppFolder folder.
        /// </summary>
        [RepositoryFolder("b80144d5-58ae-4324-8ae5-56b3c4f78b7f")]
        public partial class TextEditorAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _opentexteditorInfo;

            /// <summary>
            /// Creates a new TextEditor  folder.
            /// </summary>
            public TextEditorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TextEditor", "/form[@title='Choose Server or Database']", parentFolder, 30000, null, true, "b80144d5-58ae-4324-8ae5-56b3c4f78b7f", "")
            {
                _opentexteditorInfo = new RepoItemInfo(this, "OpenTextEditor", ".//button[@text='Open in Text Editor']", 30000, null, "8f562d60-9cfc-49fc-a749-ebbc2e5a34af");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b80144d5-58ae-4324-8ae5-56b3c4f78b7f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b80144d5-58ae-4324-8ae5-56b3c4f78b7f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OpenTextEditor item.
            /// </summary>
            [RepositoryItem("8f562d60-9cfc-49fc-a749-ebbc2e5a34af")]
            public virtual Ranorex.Button OpenTextEditor
            {
                get
                {
                    return _opentexteditorInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OpenTextEditor item info.
            /// </summary>
            [RepositoryItemInfo("8f562d60-9cfc-49fc-a749-ebbc2e5a34af")]
            public virtual RepoItemInfo OpenTextEditorInfo
            {
                get
                {
                    return _opentexteditorInfo;
                }
            }
        }

        /// <summary>
        /// The UnMountAppFolder folder.
        /// </summary>
        [RepositoryFolder("29c74b0e-aa80-4b4a-94d8-78fafba1c005")]
        public partial class UnMountAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _yesInfo;

            /// <summary>
            /// Creates a new UnMount  folder.
            /// </summary>
            public UnMountAppFolder(RepoGenBaseFolder parentFolder) :
                    base("UnMount", "/form[@title='Unmount']", parentFolder, 30000, null, true, "29c74b0e-aa80-4b4a-94d8-78fafba1c005", "")
            {
                _yesInfo = new RepoItemInfo(this, "Yes", ".//container[@name='OptionPane.buttonArea']/button[@text='Yes']", 30000, null, "304e7f48-96ce-42a1-aaa8-f75bb5baf6e1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("29c74b0e-aa80-4b4a-94d8-78fafba1c005")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("29c74b0e-aa80-4b4a-94d8-78fafba1c005")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Yes item.
            /// </summary>
            [RepositoryItem("304e7f48-96ce-42a1-aaa8-f75bb5baf6e1")]
            public virtual Ranorex.Button Yes
            {
                get
                {
                    return _yesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Yes item info.
            /// </summary>
            [RepositoryItemInfo("304e7f48-96ce-42a1-aaa8-f75bb5baf6e1")]
            public virtual RepoItemInfo YesInfo
            {
                get
                {
                    return _yesInfo;
                }
            }
        }

        /// <summary>
        /// The AquaDataStudioAppFolder folder.
        /// </summary>
        [RepositoryFolder("229a8614-b5ff-4306-a25c-53fe35c18ccc")]
        public partial class AquaDataStudioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _editorwindowInfo;
            RepoItemInfo _saveInfo;

            /// <summary>
            /// Creates a new AquaDataStudio  folder.
            /// </summary>
            public AquaDataStudioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AquaDataStudio", "/form[@title~'^Aqua\\ Data\\ Studio\\ \\[T']", parentFolder, 30000, null, true, "229a8614-b5ff-4306-a25c-53fe35c18ccc", "")
            {
                _editorwindowInfo = new RepoItemInfo(this, "EditorWindow", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myInnerComponent']//container[@type='EditorPanel']//container[@type='EditorImpl$MyScrollPane']/container[6]/element[@type='EditorComponentImpl']", 30000, null, "f58da005-b9c6-4c01-b1b0-9a45aaec1664");
                _saveInfo = new RepoItemInfo(this, "Save", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//container[@type='CToolBar']/button[3]", 30000, null, "2c8a7ae0-0971-49d6-9958-d960b9c4d38e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("229a8614-b5ff-4306-a25c-53fe35c18ccc")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("229a8614-b5ff-4306-a25c-53fe35c18ccc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EditorWindow item.
            /// </summary>
            [RepositoryItem("f58da005-b9c6-4c01-b1b0-9a45aaec1664")]
            public virtual Ranorex.Unknown EditorWindow
            {
                get
                {
                    return _editorwindowInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The EditorWindow item info.
            /// </summary>
            [RepositoryItemInfo("f58da005-b9c6-4c01-b1b0-9a45aaec1664")]
            public virtual RepoItemInfo EditorWindowInfo
            {
                get
                {
                    return _editorwindowInfo;
                }
            }

            /// <summary>
            /// The Save item.
            /// </summary>
            [RepositoryItem("2c8a7ae0-0971-49d6-9958-d960b9c4d38e")]
            public virtual Ranorex.Button Save
            {
                get
                {
                    return _saveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Save item info.
            /// </summary>
            [RepositoryItemInfo("2c8a7ae0-0971-49d6-9958-d960b9c4d38e")]
            public virtual RepoItemInfo SaveInfo
            {
                get
                {
                    return _saveInfo;
                }
            }
        }

        /// <summary>
        /// The PerforceServerAppFolder folder.
        /// </summary>
        [RepositoryFolder("e7aad77b-a1a4-4eb2-b8f2-3d7c2d4a137f")]
        public partial class PerforceServerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _depotInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new PerforceServer  folder.
            /// </summary>
            public PerforceServerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PerforceServer", "/form[@title~'^Perforce\\ Server\\ p4jrpc://']", parentFolder, 30000, null, true, "e7aad77b-a1a4-4eb2-b8f2-3d7c2d4a137f", "")
            {
                _depotInfo = new RepoItemInfo(this, "Depot", ".//container[@name='PerforceDepotBrowser']/?/?/container[@type='CScrollPane']/container[1]/table[@name='tree']/?/?/cell[@text~'^com\\.aquafold\\.datastudio\\.v']", 30000, null, "6a9cbd04-e820-48cf-8b51-04a8a3266ff0");
                _closeInfo = new RepoItemInfo(this, "Close", ".//button[@accessiblename='Close']", 30000, null, "dd317822-acb9-4220-810b-933956b70e1a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e7aad77b-a1a4-4eb2-b8f2-3d7c2d4a137f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e7aad77b-a1a4-4eb2-b8f2-3d7c2d4a137f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Depot item.
            /// </summary>
            [RepositoryItem("6a9cbd04-e820-48cf-8b51-04a8a3266ff0")]
            public virtual Ranorex.Cell Depot
            {
                get
                {
                    return _depotInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Depot item info.
            /// </summary>
            [RepositoryItemInfo("6a9cbd04-e820-48cf-8b51-04a8a3266ff0")]
            public virtual RepoItemInfo DepotInfo
            {
                get
                {
                    return _depotInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("dd317822-acb9-4220-810b-933956b70e1a")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("dd317822-acb9-4220-810b-933956b70e1a")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The EditAppFolder folder.
        /// </summary>
        [RepositoryFolder("2ff260e7-e139-4f49-bf16-e2c6a7a834ef")]
        public partial class EditAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _viewtabInfo;
            RepoItemInfo _depotInfo;
            RepoItemInfo _f1Info;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new Edit  folder.
            /// </summary>
            public EditAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Edit", "/form[@title~'^ADS\\ \\(WIN-UVJIOABRMC7:1666']", parentFolder, 30000, null, true, "2ff260e7-e139-4f49-bf16-e2c6a7a834ef", "")
            {
                _viewtabInfo = new RepoItemInfo(this, "ViewTab", ".//container[@name='tabbedPane']/tabpage[@title='View   ']", 30000, null, "254ba454-80ca-4c7b-b18e-8c837fe3d438");
                _depotInfo = new RepoItemInfo(this, "Depot", ".//container[@name='tabbedPane']/container[3]//table[@name='tree']/row[@index='0']/cell[@columnindex='0']", 30000, null, "753d610f-c894-4251-a709-ae663846a1d3");
                _f1Info = new RepoItemInfo(this, "F1", ".//container[@name='tabbedPane']/container[3]//table[@name='tree']/row[@index='1']/cell[@columnindex='0']", 30000, null, "a8cc6141-3d68-49ef-ac02-94762ee18aae");
                _closeInfo = new RepoItemInfo(this, "Close", ".//button[@accessiblename='Close']", 30000, null, "3445f948-6369-41fd-b6a4-5bf0598b6b14");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2ff260e7-e139-4f49-bf16-e2c6a7a834ef")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2ff260e7-e139-4f49-bf16-e2c6a7a834ef")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ViewTab item.
            /// </summary>
            [RepositoryItem("254ba454-80ca-4c7b-b18e-8c837fe3d438")]
            public virtual Ranorex.TabPage ViewTab
            {
                get
                {
                    return _viewtabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The ViewTab item info.
            /// </summary>
            [RepositoryItemInfo("254ba454-80ca-4c7b-b18e-8c837fe3d438")]
            public virtual RepoItemInfo ViewTabInfo
            {
                get
                {
                    return _viewtabInfo;
                }
            }

            /// <summary>
            /// The Depot item.
            /// </summary>
            [RepositoryItem("753d610f-c894-4251-a709-ae663846a1d3")]
            public virtual Ranorex.Cell Depot
            {
                get
                {
                    return _depotInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Depot item info.
            /// </summary>
            [RepositoryItemInfo("753d610f-c894-4251-a709-ae663846a1d3")]
            public virtual RepoItemInfo DepotInfo
            {
                get
                {
                    return _depotInfo;
                }
            }

            /// <summary>
            /// The F1 item.
            /// </summary>
            [RepositoryItem("a8cc6141-3d68-49ef-ac02-94762ee18aae")]
            public virtual Ranorex.Cell F1
            {
                get
                {
                    return _f1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The F1 item info.
            /// </summary>
            [RepositoryItemInfo("a8cc6141-3d68-49ef-ac02-94762ee18aae")]
            public virtual RepoItemInfo F1Info
            {
                get
                {
                    return _f1Info;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("3445f948-6369-41fd-b6a4-5bf0598b6b14")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("3445f948-6369-41fd-b6a4-5bf0598b6b14")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The HistoryAppFolder folder.
        /// </summary>
        [RepositoryFolder("b5e38b6a-8e40-4757-ad89-a988e664fba0")]
        public partial class HistoryAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _revisionhistoryInfo;
            RepoItemInfo _datesubmittedInfo;
            RepoItemInfo _descriptionInfo;
            RepoItemInfo _submittedbyInfo;
            RepoItemInfo _revisioncellInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new History  folder.
            /// </summary>
            public HistoryAppFolder(RepoGenBaseFolder parentFolder) :
                    base("History", "/form[@title~'^History\\ -\\ C:\\\\Users\\\\Admin\\\\']", parentFolder, 30000, null, true, "b5e38b6a-8e40-4757-ad89-a988e664fba0", "")
            {
                _revisionhistoryInfo = new RepoItemInfo(this, "RevisionHistory", ".//container[@name='historyPanel']/?/?/container[@accessiblename=' History ']/container[@name='scroll']/container[6]/?/?/cell[@text='Revision (Changelist)']", 30000, null, "13b4b601-d318-45ef-8d58-1ca12659a34a");
                _datesubmittedInfo = new RepoItemInfo(this, "DateSubmitted", ".//container[@name='historyPanel']/?/?/container[@accessiblename=' History ']/container[@name='scroll']/container[6]/?/?/cell[@text='Date Submitted']", 30000, null, "b028cb83-6a11-4c5a-aeb4-c72b05332526");
                _descriptionInfo = new RepoItemInfo(this, "Description", ".//container[@name='historyPanel']/?/?/container[@accessiblename=' History ']/container[@name='scroll']/container[6]/?/?/cell[@text='Description']", 30000, null, "1e2442d6-3756-470d-8d98-5f119b79499e");
                _submittedbyInfo = new RepoItemInfo(this, "SubmittedBy", ".//container[@name='historyPanel']/?/?/container[@accessiblename=' History ']/container[@name='scroll']/container[6]/?/?/cell[@text='Submitted By']", 30000, null, "e84d511d-2076-49da-9dfb-100872a5f898");
                _revisioncellInfo = new RepoItemInfo(this, "RevisionCell", ".//container[@name='historyPanel']//table[@name='table']/row[@index='0']/cell[1]", 30000, null, "2142c705-5922-48be-85e6-8e01ed563b21");
                _closeInfo = new RepoItemInfo(this, "Close", ".//button[@text='Close' and @accessibledescription='Closes the window']", 30000, null, "7120092e-3671-4b84-b9ff-aea91b167ed1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b5e38b6a-8e40-4757-ad89-a988e664fba0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b5e38b6a-8e40-4757-ad89-a988e664fba0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RevisionHistory item.
            /// </summary>
            [RepositoryItem("13b4b601-d318-45ef-8d58-1ca12659a34a")]
            public virtual Ranorex.Cell RevisionHistory
            {
                get
                {
                    return _revisionhistoryInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The RevisionHistory item info.
            /// </summary>
            [RepositoryItemInfo("13b4b601-d318-45ef-8d58-1ca12659a34a")]
            public virtual RepoItemInfo RevisionHistoryInfo
            {
                get
                {
                    return _revisionhistoryInfo;
                }
            }

            /// <summary>
            /// The DateSubmitted item.
            /// </summary>
            [RepositoryItem("b028cb83-6a11-4c5a-aeb4-c72b05332526")]
            public virtual Ranorex.Cell DateSubmitted
            {
                get
                {
                    return _datesubmittedInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The DateSubmitted item info.
            /// </summary>
            [RepositoryItemInfo("b028cb83-6a11-4c5a-aeb4-c72b05332526")]
            public virtual RepoItemInfo DateSubmittedInfo
            {
                get
                {
                    return _datesubmittedInfo;
                }
            }

            /// <summary>
            /// The Description item.
            /// </summary>
            [RepositoryItem("1e2442d6-3756-470d-8d98-5f119b79499e")]
            public virtual Ranorex.Cell Description
            {
                get
                {
                    return _descriptionInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Description item info.
            /// </summary>
            [RepositoryItemInfo("1e2442d6-3756-470d-8d98-5f119b79499e")]
            public virtual RepoItemInfo DescriptionInfo
            {
                get
                {
                    return _descriptionInfo;
                }
            }

            /// <summary>
            /// The SubmittedBy item.
            /// </summary>
            [RepositoryItem("e84d511d-2076-49da-9dfb-100872a5f898")]
            public virtual Ranorex.Cell SubmittedBy
            {
                get
                {
                    return _submittedbyInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The SubmittedBy item info.
            /// </summary>
            [RepositoryItemInfo("e84d511d-2076-49da-9dfb-100872a5f898")]
            public virtual RepoItemInfo SubmittedByInfo
            {
                get
                {
                    return _submittedbyInfo;
                }
            }

            /// <summary>
            /// The RevisionCell item.
            /// </summary>
            [RepositoryItem("2142c705-5922-48be-85e6-8e01ed563b21")]
            public virtual Ranorex.Cell RevisionCell
            {
                get
                {
                    return _revisioncellInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The RevisionCell item info.
            /// </summary>
            [RepositoryItemInfo("2142c705-5922-48be-85e6-8e01ed563b21")]
            public virtual RepoItemInfo RevisionCellInfo
            {
                get
                {
                    return _revisioncellInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("7120092e-3671-4b84-b9ff-aea91b167ed1")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("7120092e-3671-4b84-b9ff-aea91b167ed1")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The CompareWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("a96f8cbc-49dd-46ca-87a6-c034c208a89f")]
        public partial class CompareWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new CompareWindow  folder.
            /// </summary>
            public CompareWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CompareWindow", "/form[@title~'^Compare\\ -\\ C:\\\\Users\\\\Admin\\\\']", parentFolder, 30000, null, true, "a96f8cbc-49dd-46ca-87a6-c034c208a89f", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", ".//button[@accessiblename='Close']", 30000, null, "8dc0a159-34ad-4629-9faa-5caf0beadd4f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a96f8cbc-49dd-46ca-87a6-c034c208a89f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a96f8cbc-49dd-46ca-87a6-c034c208a89f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("8dc0a159-34ad-4629-9faa-5caf0beadd4f")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("8dc0a159-34ad-4629-9faa-5caf0beadd4f")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}