///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ADSAutomationPhaseII.TC_10597
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TC10597Repo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("67d4f77a-b655-483e-8f11-b39f37f096df")]
    public partial class TC10597Repo : RepoGenBaseFolder
    {
        static TC10597Repo instance = new TC10597Repo();
        TC10597RepoFolders.ApplicationAppFolder _application;
        TC10597RepoFolders.SaveChangesAppFolder _savechanges;
        TC10597RepoFolders.VisualAnalyticsBook1AsteriskAppFolder _visualanalyticsbook1asterisk;
        TC10597RepoFolders.DatastudioAppFolder _datastudio;
        TC10597RepoFolders.Datastudio1AppFolder _datastudio1;
        TC10597RepoFolders.EditAxisLASTStockCloseAppFolder _editaxislaststockclose;
        TC10597RepoFolders.ServersListAppFolder _serverslist;
        TC10597RepoFolders.QuaryAnalyzerWindowAppFolder _quaryanalyzerwindow;

        /// <summary>
        /// Gets the singleton class instance representing the TC10597Repo element repository.
        /// </summary>
        [RepositoryFolder("67d4f77a-b655-483e-8f11-b39f37f096df")]
        public static TC10597Repo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TC10597Repo() 
            : base("TC10597Repo", "/", null, 0, false, "67d4f77a-b655-483e-8f11-b39f37f096df", ".\\RepositoryImages\\TC10597Repo67d4f77a.rximgres")
        {
            _application = new TC10597RepoFolders.ApplicationAppFolder(this);
            _savechanges = new TC10597RepoFolders.SaveChangesAppFolder(this);
            _visualanalyticsbook1asterisk = new TC10597RepoFolders.VisualAnalyticsBook1AsteriskAppFolder(this);
            _datastudio = new TC10597RepoFolders.DatastudioAppFolder(this);
            _datastudio1 = new TC10597RepoFolders.Datastudio1AppFolder(this);
            _editaxislaststockclose = new TC10597RepoFolders.EditAxisLASTStockCloseAppFolder(this);
            _serverslist = new TC10597RepoFolders.ServersListAppFolder(this);
            _quaryanalyzerwindow = new TC10597RepoFolders.QuaryAnalyzerWindowAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("67d4f77a-b655-483e-8f11-b39f37f096df")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Application folder.
        /// </summary>
        [RepositoryFolder("d49bec0e-06ca-4dc7-b22a-4e1ead5f4e66")]
        public virtual TC10597RepoFolders.ApplicationAppFolder Application
        {
            get { return _application; }
        }

        /// <summary>
        /// The SaveChanges folder.
        /// </summary>
        [RepositoryFolder("d793453c-44f8-41c3-92c3-a09e1d1ad973")]
        public virtual TC10597RepoFolders.SaveChangesAppFolder SaveChanges
        {
            get { return _savechanges; }
        }

        /// <summary>
        /// The VisualAnalyticsBook1Asterisk folder.
        /// </summary>
        [RepositoryFolder("c8b5f347-51ec-4f95-966a-891a9d08c9de")]
        public virtual TC10597RepoFolders.VisualAnalyticsBook1AsteriskAppFolder VisualAnalyticsBook1Asterisk
        {
            get { return _visualanalyticsbook1asterisk; }
        }

        /// <summary>
        /// The Datastudio folder.
        /// </summary>
        [RepositoryFolder("ef93d7e5-f3f8-48d9-8ac3-08973ceb56d0")]
        public virtual TC10597RepoFolders.DatastudioAppFolder Datastudio
        {
            get { return _datastudio; }
        }

        /// <summary>
        /// The Datastudio1 folder.
        /// </summary>
        [RepositoryFolder("29b0ea4b-e19f-4625-925d-2910db81d700")]
        public virtual TC10597RepoFolders.Datastudio1AppFolder Datastudio1
        {
            get { return _datastudio1; }
        }

        /// <summary>
        /// The EditAxisLASTStockClose folder.
        /// </summary>
        [RepositoryFolder("3ae05c5c-a2fe-4558-802a-9fbf3998740f")]
        public virtual TC10597RepoFolders.EditAxisLASTStockCloseAppFolder EditAxisLASTStockClose
        {
            get { return _editaxislaststockclose; }
        }

        /// <summary>
        /// The ServersList folder.
        /// </summary>
        [RepositoryFolder("074e9ce7-9035-4f66-9c1e-6128b4f5101b")]
        public virtual TC10597RepoFolders.ServersListAppFolder ServersList
        {
            get { return _serverslist; }
        }

        /// <summary>
        /// The QuaryAnalyzerWindow folder.
        /// </summary>
        [RepositoryFolder("21f2cc24-0138-40c1-ad00-85cfc867d70f")]
        public virtual TC10597RepoFolders.QuaryAnalyzerWindowAppFolder QuaryAnalyzerWindow
        {
            get { return _quaryanalyzerwindow; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class TC10597RepoFolders
    {
        /// <summary>
        /// The ApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("d49bec0e-06ca-4dc7-b22a-4e1ead5f4e66")]
        public partial class ApplicationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _newvamenuInfo;

            /// <summary>
            /// Creates a new Application  folder.
            /// </summary>
            public ApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Application", "/form[@title~'^Aqua\\ Data\\ Studio']", parentFolder, 30000, null, true, "d49bec0e-06ca-4dc7-b22a-4e1ead5f4e66", "")
            {
                _newvamenuInfo = new RepoItemInfo(this, "NewVAMenu", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//container[@type='QueryPanel']/container[@name='panel']/?/?/container[@name='splitPane']/?/?/container[@name='tabbedPane']/container[@name='_gridResultsView']//container[@type='ResultSetTableView$ResultGridsSplitPane']//container[@type='HorizontalLayoutPanel']/container[1]/menuitem[1]", 30000, null, "3c865f39-05c8-4f40-8322-507fa564efe9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d49bec0e-06ca-4dc7-b22a-4e1ead5f4e66")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d49bec0e-06ca-4dc7-b22a-4e1ead5f4e66")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NewVAMenu item.
            /// </summary>
            [RepositoryItem("3c865f39-05c8-4f40-8322-507fa564efe9")]
            public virtual Ranorex.MenuItem NewVAMenu
            {
                get
                {
                    return _newvamenuInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The NewVAMenu item info.
            /// </summary>
            [RepositoryItemInfo("3c865f39-05c8-4f40-8322-507fa564efe9")]
            public virtual RepoItemInfo NewVAMenuInfo
            {
                get
                {
                    return _newvamenuInfo;
                }
            }
        }

        /// <summary>
        /// The SaveChangesAppFolder folder.
        /// </summary>
        [RepositoryFolder("d793453c-44f8-41c3-92c3-a09e1d1ad973")]
        public partial class SaveChangesAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _discardbuttonInfo;

            /// <summary>
            /// Creates a new SaveChanges  folder.
            /// </summary>
            public SaveChangesAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SaveChanges", "/form[@title='Save Changes']", parentFolder, 30000, null, true, "d793453c-44f8-41c3-92c3-a09e1d1ad973", "")
            {
                _discardbuttonInfo = new RepoItemInfo(this, "DiscardButton", ".//container[@name='OptionPane.buttonArea']/button[@text='Discard']", 30000, null, "7de80509-8ca8-4d1d-9a40-ae7c2819e6a6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d793453c-44f8-41c3-92c3-a09e1d1ad973")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d793453c-44f8-41c3-92c3-a09e1d1ad973")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DiscardButton item.
            /// </summary>
            [RepositoryItem("7de80509-8ca8-4d1d-9a40-ae7c2819e6a6")]
            public virtual Ranorex.Button DiscardButton
            {
                get
                {
                    return _discardbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DiscardButton item info.
            /// </summary>
            [RepositoryItemInfo("7de80509-8ca8-4d1d-9a40-ae7c2819e6a6")]
            public virtual RepoItemInfo DiscardButtonInfo
            {
                get
                {
                    return _discardbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The VisualAnalyticsBook1AsteriskAppFolder folder.
        /// </summary>
        [RepositoryFolder("c8b5f347-51ec-4f95-966a-891a9d08c9de")]
        public partial class VisualAnalyticsBook1AsteriskAppFolder : RepoGenBaseFolder
        {
            TC10597RepoFolders.ContainerMainPanelFolder _containermainpanel;

            /// <summary>
            /// Creates a new VisualAnalyticsBook1Asterisk  folder.
            /// </summary>
            public VisualAnalyticsBook1AsteriskAppFolder(RepoGenBaseFolder parentFolder) :
                    base("VisualAnalyticsBook1Asterisk", "/form[@title~'^Visual\\ Analytics\\ -\\ \\[Book']", parentFolder, 30000, null, false, "c8b5f347-51ec-4f95-966a-891a9d08c9de", "")
            {
                _containermainpanel = new TC10597RepoFolders.ContainerMainPanelFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c8b5f347-51ec-4f95-966a-891a9d08c9de")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c8b5f347-51ec-4f95-966a-891a9d08c9de")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ContainerMainPanel folder.
            /// </summary>
            [RepositoryFolder("c14697f8-713e-4b99-b35a-1f93f93e3486")]
            public virtual TC10597RepoFolders.ContainerMainPanelFolder ContainerMainPanel
            {
                get { return _containermainpanel; }
            }
        }

        /// <summary>
        /// The ContainerMainPanelFolder folder.
        /// </summary>
        [RepositoryFolder("c14697f8-713e-4b99-b35a-1f93f93e3486")]
        public partial class ContainerMainPanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _bichartoverlaypanelInfo;
            RepoItemInfo _stockdateInfo;
            RepoItemInfo _stocksymbolInfo;
            RepoItemInfo _sumstockcloseInfo;
            RepoItemInfo _sumstockhighInfo;
            RepoItemInfo _sumstocklowInfo;
            RepoItemInfo _sumstockopenInfo;
            RepoItemInfo _windowscomboboxuidollarxpcomboboxbuttonInfo;
            RepoItemInfo _panelInfo;
            RepoItemInfo _panel2Info;
            RepoItemInfo _panel1Info;
            RepoItemInfo _sumstockclose1Info;
            RepoItemInfo _listitemallInfo;
            RepoItemInfo _aaplInfo;
            RepoItemInfo _highInfo;
            RepoItemInfo _textlowInfo;
            RepoItemInfo _openInfo;
            RepoItemInfo _bichartoverlaypanel1Info;

            /// <summary>
            /// Creates a new ContainerMainPanel  folder.
            /// </summary>
            public ContainerMainPanelFolder(RepoGenBaseFolder parentFolder) :
                    base("ContainerMainPanel", "container[@name='_mainPanel']", parentFolder, 30000, null, false, "c14697f8-713e-4b99-b35a-1f93f93e3486", "")
            {
                _bichartoverlaypanelInfo = new RepoItemInfo(this, "BIChartOverlayPanel", ".//container[@name='_sheetsPane']/container[@name='Worksheet 1']//container[@name='main']/container[@name='_cardPanel']/container[@name='_chartPanel']/container/container[22]", 30000, null, "3799afdd-ed51-4279-902a-f852c82a0798");
                _stockdateInfo = new RepoItemInfo(this, "StockDate", "container[@name='_contentPanel']/?/?/container[@name='_leftPanel']//container[@type='BIDimensionDataPane']//container[@name='viewport']/list[@type='BIDraggableList']/listitem[@text='stock_date']", 30000, null, "2be9872a-0c1b-43cd-936c-5bd501ee8585");
                _stocksymbolInfo = new RepoItemInfo(this, "StockSymbol", "container[@name='_contentPanel']/?/?/container[@name='_leftPanel']//container[@type='BIDimensionDataPane']//container[@name='viewport']/list[@type='BIDraggableList']/listitem[@text='stock_symbol']", 30000, null, "679c7041-fbe9-41b3-8f8d-0801c567e7e4");
                _sumstockcloseInfo = new RepoItemInfo(this, "SUMStockClose", "container[@name='_contentPanel']/?/?/container[@name='_leftPanel']//container[@type='BIMeasureDataPane']//container[@name='viewport']/list[@type='BIDraggableList']/listitem[@text='SUM(stock_close)']", 30000, null, "e8354661-9279-4c3a-8295-de333dc1c730");
                _sumstockhighInfo = new RepoItemInfo(this, "SUMStockHigh", "container[@name='_contentPanel']/?/?/container[@name='_leftPanel']//container[@type='BIMeasureDataPane']//container[@name='viewport']/list[@type='BIDraggableList']/listitem[@text='SUM(stock_high)']", 30000, null, "804830a8-5970-49c4-acbd-886d742992e9");
                _sumstocklowInfo = new RepoItemInfo(this, "SUMStockLow", "container[@name='_contentPanel']/?/?/container[@name='_leftPanel']//container[@type='BIMeasureDataPane']//container[@name='viewport']/list[@type='BIDraggableList']/listitem[@text='SUM(stock_low)']", 30000, null, "2d2bb366-a280-41e8-b2e3-a674cbd62053");
                _sumstockopenInfo = new RepoItemInfo(this, "SUMStockOpen", "container[@name='_contentPanel']/?/?/container[@name='_leftPanel']//container[@type='BIMeasureDataPane']//container[@name='viewport']/list[@type='BIDraggableList']/listitem[@text='SUM(stock_open)']", 30000, null, "07727cae-e89d-4c01-8847-4f19ea9a54b1");
                _windowscomboboxuidollarxpcomboboxbuttonInfo = new RepoItemInfo(this, "WindowsComboBoxUIDollarXPComboBoxButton", "container[@name='_contentPanel']/?/?/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//combobox[@type='MarkChartTypeSelector$1']/button[@text='']", 30000, null, "85e6e373-55d2-4bdf-bb15-5a2c71aac0d8");
                _panelInfo = new RepoItemInfo(this, "Panel", "container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']//container[@name='cols']//container[@name='panel']", 30000, null, "d28849e0-043f-4e70-9255-0a6e54d38a38");
                _panel2Info = new RepoItemInfo(this, "Panel2", "container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']//container[@name='filter']//container[@name='panel']", 30000, null, "298ef850-5c39-49d6-ae5d-a88e0443059e");
                _panel1Info = new RepoItemInfo(this, "Panel1", "container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']//container[@name='rows']//container[@name='panel']", 30000, null, "e6056c11-37c2-4483-b0be-a5b5341b4d62");
                _sumstockclose1Info = new RepoItemInfo(this, "SUMStockClose1", "container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']//container[@name='rows']//text[@caption='SUM(stock_close)']", 30000, null, "5969237d-b844-477a-89f6-02d0079d6945");
                _listitemallInfo = new RepoItemInfo(this, "ListItemAll", "container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']//container[@name='stock_symbol,11,true,,Dimension']//list[@type='CategoricalFilterEditorPane$MultiSelectList']/listitem[@text='(All)']", 30000, null, "0f9755ce-faef-4114-a257-7f191a02d360");
                _aaplInfo = new RepoItemInfo(this, "AAPL", "container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']//container[@name='stock_symbol,11,true,,Dimension']//list[@type='CategoricalFilterEditorPane$MultiSelectList']/listitem[@text='AAPL']", 30000, null, "0a7dbfc0-5082-41fe-85f2-bbdeeba23fb3");
                _highInfo = new RepoItemInfo(this, "High", "container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//text[@caption='High']", 30000, null, "d0bd05d8-1ea4-445c-9667-051183c3b20f");
                _textlowInfo = new RepoItemInfo(this, "TextLow", "container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//text[@caption='Low']", 30000, null, "8725859d-e91f-4d0c-b09d-8181c3b4b673");
                _openInfo = new RepoItemInfo(this, "Open", "container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//text[@caption='Open']", 30000, null, "1b61050f-c46e-47e5-a491-1060a5806fb9");
                _bichartoverlaypanel1Info = new RepoItemInfo(this, "BIChartOverlayPanel1", ".//container[@name='_sheetsPane']/container[@name='Worksheet 1']//container[@name='main']/container[@name='_cardPanel']/container[@name='_chartPanel']/container", 30000, null, "afa7aa78-25fe-4abd-97a2-500787d4f4fb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c14697f8-713e-4b99-b35a-1f93f93e3486")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c14697f8-713e-4b99-b35a-1f93f93e3486")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BIChartOverlayPanel item.
            /// </summary>
            [RepositoryItem("3799afdd-ed51-4279-902a-f852c82a0798")]
            public virtual Ranorex.Container BIChartOverlayPanel
            {
                get
                {
                    return _bichartoverlaypanelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The BIChartOverlayPanel item info.
            /// </summary>
            [RepositoryItemInfo("3799afdd-ed51-4279-902a-f852c82a0798")]
            public virtual RepoItemInfo BIChartOverlayPanelInfo
            {
                get
                {
                    return _bichartoverlaypanelInfo;
                }
            }

            /// <summary>
            /// The StockDate item.
            /// </summary>
            [RepositoryItem("2be9872a-0c1b-43cd-936c-5bd501ee8585")]
            public virtual Ranorex.ListItem StockDate
            {
                get
                {
                    return _stockdateInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The StockDate item info.
            /// </summary>
            [RepositoryItemInfo("2be9872a-0c1b-43cd-936c-5bd501ee8585")]
            public virtual RepoItemInfo StockDateInfo
            {
                get
                {
                    return _stockdateInfo;
                }
            }

            /// <summary>
            /// The StockSymbol item.
            /// </summary>
            [RepositoryItem("679c7041-fbe9-41b3-8f8d-0801c567e7e4")]
            public virtual Ranorex.ListItem StockSymbol
            {
                get
                {
                    return _stocksymbolInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The StockSymbol item info.
            /// </summary>
            [RepositoryItemInfo("679c7041-fbe9-41b3-8f8d-0801c567e7e4")]
            public virtual RepoItemInfo StockSymbolInfo
            {
                get
                {
                    return _stocksymbolInfo;
                }
            }

            /// <summary>
            /// The SUMStockClose item.
            /// </summary>
            [RepositoryItem("e8354661-9279-4c3a-8295-de333dc1c730")]
            public virtual Ranorex.ListItem SUMStockClose
            {
                get
                {
                    return _sumstockcloseInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SUMStockClose item info.
            /// </summary>
            [RepositoryItemInfo("e8354661-9279-4c3a-8295-de333dc1c730")]
            public virtual RepoItemInfo SUMStockCloseInfo
            {
                get
                {
                    return _sumstockcloseInfo;
                }
            }

            /// <summary>
            /// The SUMStockHigh item.
            /// </summary>
            [RepositoryItem("804830a8-5970-49c4-acbd-886d742992e9")]
            public virtual Ranorex.ListItem SUMStockHigh
            {
                get
                {
                    return _sumstockhighInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SUMStockHigh item info.
            /// </summary>
            [RepositoryItemInfo("804830a8-5970-49c4-acbd-886d742992e9")]
            public virtual RepoItemInfo SUMStockHighInfo
            {
                get
                {
                    return _sumstockhighInfo;
                }
            }

            /// <summary>
            /// The SUMStockLow item.
            /// </summary>
            [RepositoryItem("2d2bb366-a280-41e8-b2e3-a674cbd62053")]
            public virtual Ranorex.ListItem SUMStockLow
            {
                get
                {
                    return _sumstocklowInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SUMStockLow item info.
            /// </summary>
            [RepositoryItemInfo("2d2bb366-a280-41e8-b2e3-a674cbd62053")]
            public virtual RepoItemInfo SUMStockLowInfo
            {
                get
                {
                    return _sumstocklowInfo;
                }
            }

            /// <summary>
            /// The SUMStockOpen item.
            /// </summary>
            [RepositoryItem("07727cae-e89d-4c01-8847-4f19ea9a54b1")]
            public virtual Ranorex.ListItem SUMStockOpen
            {
                get
                {
                    return _sumstockopenInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SUMStockOpen item info.
            /// </summary>
            [RepositoryItemInfo("07727cae-e89d-4c01-8847-4f19ea9a54b1")]
            public virtual RepoItemInfo SUMStockOpenInfo
            {
                get
                {
                    return _sumstockopenInfo;
                }
            }

            /// <summary>
            /// The WindowsComboBoxUIDollarXPComboBoxButton item.
            /// </summary>
            [RepositoryItem("85e6e373-55d2-4bdf-bb15-5a2c71aac0d8")]
            public virtual Ranorex.Button WindowsComboBoxUIDollarXPComboBoxButton
            {
                get
                {
                    return _windowscomboboxuidollarxpcomboboxbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The WindowsComboBoxUIDollarXPComboBoxButton item info.
            /// </summary>
            [RepositoryItemInfo("85e6e373-55d2-4bdf-bb15-5a2c71aac0d8")]
            public virtual RepoItemInfo WindowsComboBoxUIDollarXPComboBoxButtonInfo
            {
                get
                {
                    return _windowscomboboxuidollarxpcomboboxbuttonInfo;
                }
            }

            /// <summary>
            /// The Panel item.
            /// </summary>
            [RepositoryItem("d28849e0-043f-4e70-9255-0a6e54d38a38")]
            public virtual Ranorex.Container Panel
            {
                get
                {
                    return _panelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Panel item info.
            /// </summary>
            [RepositoryItemInfo("d28849e0-043f-4e70-9255-0a6e54d38a38")]
            public virtual RepoItemInfo PanelInfo
            {
                get
                {
                    return _panelInfo;
                }
            }

            /// <summary>
            /// The Panel2 item.
            /// </summary>
            [RepositoryItem("298ef850-5c39-49d6-ae5d-a88e0443059e")]
            public virtual Ranorex.Container Panel2
            {
                get
                {
                    return _panel2Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Panel2 item info.
            /// </summary>
            [RepositoryItemInfo("298ef850-5c39-49d6-ae5d-a88e0443059e")]
            public virtual RepoItemInfo Panel2Info
            {
                get
                {
                    return _panel2Info;
                }
            }

            /// <summary>
            /// The Panel1 item.
            /// </summary>
            [RepositoryItem("e6056c11-37c2-4483-b0be-a5b5341b4d62")]
            public virtual Ranorex.Container Panel1
            {
                get
                {
                    return _panel1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Panel1 item info.
            /// </summary>
            [RepositoryItemInfo("e6056c11-37c2-4483-b0be-a5b5341b4d62")]
            public virtual RepoItemInfo Panel1Info
            {
                get
                {
                    return _panel1Info;
                }
            }

            /// <summary>
            /// The SUMStockClose1 item.
            /// </summary>
            [RepositoryItem("5969237d-b844-477a-89f6-02d0079d6945")]
            public virtual Ranorex.Text SUMStockClose1
            {
                get
                {
                    return _sumstockclose1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SUMStockClose1 item info.
            /// </summary>
            [RepositoryItemInfo("5969237d-b844-477a-89f6-02d0079d6945")]
            public virtual RepoItemInfo SUMStockClose1Info
            {
                get
                {
                    return _sumstockclose1Info;
                }
            }

            /// <summary>
            /// The ListItemAll item.
            /// </summary>
            [RepositoryItem("0f9755ce-faef-4114-a257-7f191a02d360")]
            public virtual Ranorex.ListItem ListItemAll
            {
                get
                {
                    return _listitemallInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemAll item info.
            /// </summary>
            [RepositoryItemInfo("0f9755ce-faef-4114-a257-7f191a02d360")]
            public virtual RepoItemInfo ListItemAllInfo
            {
                get
                {
                    return _listitemallInfo;
                }
            }

            /// <summary>
            /// The AAPL item.
            /// </summary>
            [RepositoryItem("0a7dbfc0-5082-41fe-85f2-bbdeeba23fb3")]
            public virtual Ranorex.ListItem AAPL
            {
                get
                {
                    return _aaplInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The AAPL item info.
            /// </summary>
            [RepositoryItemInfo("0a7dbfc0-5082-41fe-85f2-bbdeeba23fb3")]
            public virtual RepoItemInfo AAPLInfo
            {
                get
                {
                    return _aaplInfo;
                }
            }

            /// <summary>
            /// The High item.
            /// </summary>
            [RepositoryItem("d0bd05d8-1ea4-445c-9667-051183c3b20f")]
            public virtual Ranorex.Text High
            {
                get
                {
                    return _highInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The High item info.
            /// </summary>
            [RepositoryItemInfo("d0bd05d8-1ea4-445c-9667-051183c3b20f")]
            public virtual RepoItemInfo HighInfo
            {
                get
                {
                    return _highInfo;
                }
            }

            /// <summary>
            /// The TextLow item.
            /// </summary>
            [RepositoryItem("8725859d-e91f-4d0c-b09d-8181c3b4b673")]
            public virtual Ranorex.Text TextLow
            {
                get
                {
                    return _textlowInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextLow item info.
            /// </summary>
            [RepositoryItemInfo("8725859d-e91f-4d0c-b09d-8181c3b4b673")]
            public virtual RepoItemInfo TextLowInfo
            {
                get
                {
                    return _textlowInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("1b61050f-c46e-47e5-a491-1060a5806fb9")]
            public virtual Ranorex.Text Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("1b61050f-c46e-47e5-a491-1060a5806fb9")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The BIChartOverlayPanel1 item.
            /// </summary>
            [RepositoryItem("afa7aa78-25fe-4abd-97a2-500787d4f4fb")]
            public virtual Ranorex.Container BIChartOverlayPanel1
            {
                get
                {
                    return _bichartoverlaypanel1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The BIChartOverlayPanel1 item info.
            /// </summary>
            [RepositoryItemInfo("afa7aa78-25fe-4abd-97a2-500787d4f4fb")]
            public virtual RepoItemInfo BIChartOverlayPanel1Info
            {
                get
                {
                    return _bichartoverlaypanel1Info;
                }
            }
        }

        /// <summary>
        /// The DatastudioAppFolder folder.
        /// </summary>
        [RepositoryFolder("ef93d7e5-f3f8-48d9-8ac3-08973ceb56d0")]
        public partial class DatastudioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _measuretypesumInfo;
            RepoItemInfo _priceInfo;
            RepoItemInfo _editaxisInfo;

            /// <summary>
            /// Creates a new Datastudio  folder.
            /// </summary>
            public DatastudioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Datastudio", "/form[@class='SunAwtWindow' and @type='Popup$HeavyWeightWindow' and @fulltype='javax.swing.Popup$HeavyWeightWindow' and @instance='0']", parentFolder, 30000, null, false, "ef93d7e5-f3f8-48d9-8ac3-08973ceb56d0", "")
            {
                _measuretypesumInfo = new RepoItemInfo(this, "MeasureTypeSum", "?/?/menuitem[@text='Measure Type (Sum)']", 30000, null, "aacc986e-ba98-40ea-bf3c-c18d22a51805");
                _priceInfo = new RepoItemInfo(this, "Price", ".//container[@name='viewport']/list[@name='ComboBox.list']/listitem[@text='Price']", 30000, null, "28826628-98c6-4c30-933e-a08fcffe4904");
                _editaxisInfo = new RepoItemInfo(this, "EditAxis", "?/?/menuitem[@text='Edit Axis...']", 30000, null, "723e26a4-2349-48a0-8ac7-5eaa6619a9e8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ef93d7e5-f3f8-48d9-8ac3-08973ceb56d0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ef93d7e5-f3f8-48d9-8ac3-08973ceb56d0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MeasureTypeSum item.
            /// </summary>
            [RepositoryItem("aacc986e-ba98-40ea-bf3c-c18d22a51805")]
            public virtual Ranorex.MenuItem MeasureTypeSum
            {
                get
                {
                    return _measuretypesumInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MeasureTypeSum item info.
            /// </summary>
            [RepositoryItemInfo("aacc986e-ba98-40ea-bf3c-c18d22a51805")]
            public virtual RepoItemInfo MeasureTypeSumInfo
            {
                get
                {
                    return _measuretypesumInfo;
                }
            }

            /// <summary>
            /// The Price item.
            /// </summary>
            [RepositoryItem("28826628-98c6-4c30-933e-a08fcffe4904")]
            public virtual Ranorex.ListItem Price
            {
                get
                {
                    return _priceInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Price item info.
            /// </summary>
            [RepositoryItemInfo("28826628-98c6-4c30-933e-a08fcffe4904")]
            public virtual RepoItemInfo PriceInfo
            {
                get
                {
                    return _priceInfo;
                }
            }

            /// <summary>
            /// The EditAxis item.
            /// </summary>
            [RepositoryItem("723e26a4-2349-48a0-8ac7-5eaa6619a9e8")]
            public virtual Ranorex.MenuItem EditAxis
            {
                get
                {
                    return _editaxisInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The EditAxis item info.
            /// </summary>
            [RepositoryItemInfo("723e26a4-2349-48a0-8ac7-5eaa6619a9e8")]
            public virtual RepoItemInfo EditAxisInfo
            {
                get
                {
                    return _editaxisInfo;
                }
            }
        }

        /// <summary>
        /// The Datastudio1AppFolder folder.
        /// </summary>
        [RepositoryFolder("29b0ea4b-e19f-4625-925d-2910db81d700")]
        public partial class Datastudio1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lastInfo;

            /// <summary>
            /// Creates a new Datastudio1  folder.
            /// </summary>
            public Datastudio1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Datastudio1", "/form[@class='SunAwtWindow' and @type='Popup$HeavyWeightWindow' and @fulltype='javax.swing.Popup$HeavyWeightWindow' and @instance='1']", parentFolder, 30000, null, false, "29b0ea4b-e19f-4625-925d-2910db81d700", "")
            {
                _lastInfo = new RepoItemInfo(this, "Last", "?/?/menuitem[@text='Last']", 30000, null, "e5dd0bcf-95a8-4e05-b9f8-e887340f440e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("29b0ea4b-e19f-4625-925d-2910db81d700")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("29b0ea4b-e19f-4625-925d-2910db81d700")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Last item.
            /// </summary>
            [RepositoryItem("e5dd0bcf-95a8-4e05-b9f8-e887340f440e")]
            public virtual Ranorex.MenuItem Last
            {
                get
                {
                    return _lastInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Last item info.
            /// </summary>
            [RepositoryItemInfo("e5dd0bcf-95a8-4e05-b9f8-e887340f440e")]
            public virtual RepoItemInfo LastInfo
            {
                get
                {
                    return _lastInfo;
                }
            }
        }

        /// <summary>
        /// The EditAxisLASTStockCloseAppFolder folder.
        /// </summary>
        [RepositoryFolder("3ae05c5c-a2fe-4558-802a-9fbf3998740f")]
        public partial class EditAxisLASTStockCloseAppFolder : RepoGenBaseFolder
        {
            TC10597RepoFolders.CPanelFolder _cpanel;

            /// <summary>
            /// Creates a new EditAxisLASTStockClose  folder.
            /// </summary>
            public EditAxisLASTStockCloseAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EditAxisLASTStockClose", "/form[@title~'^Edit\\ Axis\\ \\[LAST\\(stock_clo']", parentFolder, 30000, null, false, "3ae05c5c-a2fe-4558-802a-9fbf3998740f", "")
            {
                _cpanel = new TC10597RepoFolders.CPanelFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3ae05c5c-a2fe-4558-802a-9fbf3998740f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3ae05c5c-a2fe-4558-802a-9fbf3998740f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CPanel folder.
            /// </summary>
            [RepositoryFolder("3231daf4-b9d2-4961-9eea-ccb14f8ff44d")]
            public virtual TC10597RepoFolders.CPanelFolder CPanel
            {
                get { return _cpanel; }
            }
        }

        /// <summary>
        /// The CPanelFolder folder.
        /// </summary>
        [RepositoryFolder("3231daf4-b9d2-4961-9eea-ccb14f8ff44d")]
        public partial class CPanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _applyInfo;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _includezeroInfo;

            /// <summary>
            /// Creates a new CPanel  folder.
            /// </summary>
            public CPanelFolder(RepoGenBaseFolder parentFolder) :
                    base("CPanel", "container[@type='CPanel']", parentFolder, 30000, null, false, "3231daf4-b9d2-4961-9eea-ccb14f8ff44d", "")
            {
                _applyInfo = new RepoItemInfo(this, "Apply", ".//button[@name='applyBtn']", 30000, null, "ce666f76-0c70-4374-ba42-2b1aa41f92e2");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", ".//button[@text='OK']", 30000, null, "e0aabf25-12b0-411f-a71e-6f29a99cbfa0");
                _includezeroInfo = new RepoItemInfo(this, "IncludeZero", ".//container[@name='axisRangePanel']/?/?/checkbox[@name='includeZero']", 30000, null, "0072f6fe-e8a7-4cdc-850f-3ee4e430bbc4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3231daf4-b9d2-4961-9eea-ccb14f8ff44d")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3231daf4-b9d2-4961-9eea-ccb14f8ff44d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Apply item.
            /// </summary>
            [RepositoryItem("ce666f76-0c70-4374-ba42-2b1aa41f92e2")]
            public virtual Ranorex.Button Apply
            {
                get
                {
                    return _applyInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Apply item info.
            /// </summary>
            [RepositoryItemInfo("ce666f76-0c70-4374-ba42-2b1aa41f92e2")]
            public virtual RepoItemInfo ApplyInfo
            {
                get
                {
                    return _applyInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("e0aabf25-12b0-411f-a71e-6f29a99cbfa0")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("e0aabf25-12b0-411f-a71e-6f29a99cbfa0")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The IncludeZero item.
            /// </summary>
            [RepositoryItem("0072f6fe-e8a7-4cdc-850f-3ee4e430bbc4")]
            public virtual Ranorex.CheckBox IncludeZero
            {
                get
                {
                    return _includezeroInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The IncludeZero item info.
            /// </summary>
            [RepositoryItemInfo("0072f6fe-e8a7-4cdc-850f-3ee4e430bbc4")]
            public virtual RepoItemInfo IncludeZeroInfo
            {
                get
                {
                    return _includezeroInfo;
                }
            }
        }

        /// <summary>
        /// The ServersListAppFolder folder.
        /// </summary>
        [RepositoryFolder("074e9ce7-9035-4f66-9c1e-6128b4f5101b")]
        public partial class ServersListAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _localdbserverstreeitemInfo;
            RepoItemInfo _amazonredshiftInfo;
            RepoItemInfo _cassandra37Info;
            RepoItemInfo _cassandra22Info;
            RepoItemInfo _derby1014Info;
            RepoItemInfo _derby1013Info;
            RepoItemInfo _db2111Info;
            RepoItemInfo _db2105Info;
            RepoItemInfo _excellInfo;
            RepoItemInfo _greenplum50Info;
            RepoItemInfo _greenplum4312Info;
            RepoItemInfo _informix1210Info;
            RepoItemInfo _informix1170Info;
            RepoItemInfo _mariadbInfo;
            RepoItemInfo _mongodb341Info;
            RepoItemInfo _mongodb321Info;
            RepoItemInfo _mysql80Info;
            RepoItemInfo _mysql57Info;

            /// <summary>
            /// Creates a new ServersList  folder.
            /// </summary>
            public ServersListAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ServersList", "/form[@title~'^Aqua Data Studio']", parentFolder, 30000, null, true, "074e9ce7-9035-4f66-9c1e-6128b4f5101b", "")
            {
                _localdbserverstreeitemInfo = new RepoItemInfo(this, "LocalDBServersTreeItem", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//container[@name='viewport']/tree[@name='schemaTree']/?/?/treeitem[@text='Local Database Servers']", 30000, null, "0f6e214a-25ee-4eaa-81ac-a97c7eb5ef44");
                _amazonredshiftInfo = new RepoItemInfo(this, "AmazonRedshift", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='Amazon Redshift']", 30000, null, "42455817-093b-43f2-a874-6b64bbf54c32");
                _cassandra37Info = new RepoItemInfo(this, "Cassandra37", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='Cassandra 172.24.1.77 3.7']", 30000, null, "687b1d8a-8279-4b44-b9b9-df583870cdde");
                _cassandra22Info = new RepoItemInfo(this, "Cassandra22", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Cassandra\\ 172\\.24\\.1\\.122\\ 2\\.']", 30000, null, "c3acc780-3500-40ab-9700-abe57717e048");
                _derby1014Info = new RepoItemInfo(this, "Derby1014", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='Derby 172.24.1.199 v10.14']", 30000, null, "1ebfbf8a-748c-4072-9785-c73c555586e0");
                _derby1013Info = new RepoItemInfo(this, "Derby1013", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='Derby 172.24.1.8 v10.13']", 30000, null, "8951d885-6114-41bb-88a4-8e67f1954167");
                _db2111Info = new RepoItemInfo(this, "DB2111", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='DB2 LUW 172.24.1.8 v11.1']", 30000, null, "e4c2b412-7fed-4196-b33f-034a187a4270");
                _db2105Info = new RepoItemInfo(this, "DB2105", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^DB2\\ LUW\\ 172\\.24\\.1\\.145\\ v10\\.']", 30000, null, "e41fea87-364c-402d-a3df-f6ed69c45513");
                _excellInfo = new RepoItemInfo(this, "Excell", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='MS Excel']", 30000, null, "d8a9f856-d6ec-46a3-94a2-3317bc42b65c");
                _greenplum50Info = new RepoItemInfo(this, "Greenplum50", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Greenplum\\ 10\\.90\\.1\\.146\\ v5\\.']", 30000, null, "838dd8c3-66c0-4e84-99ea-420f63697081");
                _greenplum4312Info = new RepoItemInfo(this, "Greenplum4312", "element", 30000, null, "bc650173-6ba2-4fad-9143-134c4b4d3593");
                _informix1210Info = new RepoItemInfo(this, "Informix1210", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Informix\\ 172\\.24\\.1\\.145\\ v12']", 30000, null, "f6382d4e-bc5c-411b-ae82-7b65ff2c0cdf");
                _informix1170Info = new RepoItemInfo(this, "Informix1170", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Informix\\ 172\\.24\\.1\\.140\\ v11']", 30000, null, "9684e933-b68d-4b42-93a7-2bc40e524ea1");
                _mariadbInfo = new RepoItemInfo(this, "MariaDB", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='MariaDB 172.24.1.8 v10.2']", 30000, null, "f96380ae-605b-4713-9452-d6d45b55a5e0");
                _mongodb341Info = new RepoItemInfo(this, "MongoDB341", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^MongoDB\\ 172\\.24\\.1\\.155\\ v3\\.4']", 30000, null, "d96209e6-546a-46ae-8862-6e64bcafd706");
                _mongodb321Info = new RepoItemInfo(this, "MongoDB321", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^MongoDB\\ 172\\.24\\.1\\.155\\ v3\\.2']", 30000, null, "f46006da-8173-4ad0-93ae-1ba2488ead71");
                _mysql80Info = new RepoItemInfo(this, "MySQL80", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='MySQL 172.24.1.199 v8.0']", 30000, null, "1ea11b55-56ac-41f6-a396-99a59261cf39");
                _mysql57Info = new RepoItemInfo(this, "MySQL57", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='MySQL 172.24.1.8 v5.7']", 30000, null, "af69ff7f-c42b-40b6-b521-f1466fc88fc2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("074e9ce7-9035-4f66-9c1e-6128b4f5101b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("074e9ce7-9035-4f66-9c1e-6128b4f5101b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LocalDBServersTreeItem item.
            /// </summary>
            [RepositoryItem("0f6e214a-25ee-4eaa-81ac-a97c7eb5ef44")]
            public virtual Ranorex.TreeItem LocalDBServersTreeItem
            {
                get
                {
                    return _localdbserverstreeitemInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The LocalDBServersTreeItem item info.
            /// </summary>
            [RepositoryItemInfo("0f6e214a-25ee-4eaa-81ac-a97c7eb5ef44")]
            public virtual RepoItemInfo LocalDBServersTreeItemInfo
            {
                get
                {
                    return _localdbserverstreeitemInfo;
                }
            }

            /// <summary>
            /// The AmazonRedshift item.
            /// </summary>
            [RepositoryItem("42455817-093b-43f2-a874-6b64bbf54c32")]
            public virtual Ranorex.TreeItem AmazonRedshift
            {
                get
                {
                    return _amazonredshiftInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The AmazonRedshift item info.
            /// </summary>
            [RepositoryItemInfo("42455817-093b-43f2-a874-6b64bbf54c32")]
            public virtual RepoItemInfo AmazonRedshiftInfo
            {
                get
                {
                    return _amazonredshiftInfo;
                }
            }

            /// <summary>
            /// The Cassandra37 item.
            /// </summary>
            [RepositoryItem("687b1d8a-8279-4b44-b9b9-df583870cdde")]
            public virtual Ranorex.TreeItem Cassandra37
            {
                get
                {
                    return _cassandra37Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Cassandra37 item info.
            /// </summary>
            [RepositoryItemInfo("687b1d8a-8279-4b44-b9b9-df583870cdde")]
            public virtual RepoItemInfo Cassandra37Info
            {
                get
                {
                    return _cassandra37Info;
                }
            }

            /// <summary>
            /// The Cassandra22 item.
            /// </summary>
            [RepositoryItem("c3acc780-3500-40ab-9700-abe57717e048")]
            public virtual Ranorex.TreeItem Cassandra22
            {
                get
                {
                    return _cassandra22Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Cassandra22 item info.
            /// </summary>
            [RepositoryItemInfo("c3acc780-3500-40ab-9700-abe57717e048")]
            public virtual RepoItemInfo Cassandra22Info
            {
                get
                {
                    return _cassandra22Info;
                }
            }

            /// <summary>
            /// The Derby1014 item.
            /// </summary>
            [RepositoryItem("1ebfbf8a-748c-4072-9785-c73c555586e0")]
            public virtual Ranorex.TreeItem Derby1014
            {
                get
                {
                    return _derby1014Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Derby1014 item info.
            /// </summary>
            [RepositoryItemInfo("1ebfbf8a-748c-4072-9785-c73c555586e0")]
            public virtual RepoItemInfo Derby1014Info
            {
                get
                {
                    return _derby1014Info;
                }
            }

            /// <summary>
            /// The Derby1013 item.
            /// </summary>
            [RepositoryItem("8951d885-6114-41bb-88a4-8e67f1954167")]
            public virtual Ranorex.TreeItem Derby1013
            {
                get
                {
                    return _derby1013Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Derby1013 item info.
            /// </summary>
            [RepositoryItemInfo("8951d885-6114-41bb-88a4-8e67f1954167")]
            public virtual RepoItemInfo Derby1013Info
            {
                get
                {
                    return _derby1013Info;
                }
            }

            /// <summary>
            /// The DB2111 item.
            /// </summary>
            [RepositoryItem("e4c2b412-7fed-4196-b33f-034a187a4270")]
            public virtual Ranorex.TreeItem DB2111
            {
                get
                {
                    return _db2111Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The DB2111 item info.
            /// </summary>
            [RepositoryItemInfo("e4c2b412-7fed-4196-b33f-034a187a4270")]
            public virtual RepoItemInfo DB2111Info
            {
                get
                {
                    return _db2111Info;
                }
            }

            /// <summary>
            /// The DB2105 item.
            /// </summary>
            [RepositoryItem("e41fea87-364c-402d-a3df-f6ed69c45513")]
            public virtual Ranorex.TreeItem DB2105
            {
                get
                {
                    return _db2105Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The DB2105 item info.
            /// </summary>
            [RepositoryItemInfo("e41fea87-364c-402d-a3df-f6ed69c45513")]
            public virtual RepoItemInfo DB2105Info
            {
                get
                {
                    return _db2105Info;
                }
            }

            /// <summary>
            /// The Excell item.
            /// </summary>
            [RepositoryItem("d8a9f856-d6ec-46a3-94a2-3317bc42b65c")]
            public virtual Ranorex.TreeItem Excell
            {
                get
                {
                    return _excellInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Excell item info.
            /// </summary>
            [RepositoryItemInfo("d8a9f856-d6ec-46a3-94a2-3317bc42b65c")]
            public virtual RepoItemInfo ExcellInfo
            {
                get
                {
                    return _excellInfo;
                }
            }

            /// <summary>
            /// The Greenplum50 item.
            /// </summary>
            [RepositoryItem("838dd8c3-66c0-4e84-99ea-420f63697081")]
            public virtual Ranorex.TreeItem Greenplum50
            {
                get
                {
                    return _greenplum50Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Greenplum50 item info.
            /// </summary>
            [RepositoryItemInfo("838dd8c3-66c0-4e84-99ea-420f63697081")]
            public virtual RepoItemInfo Greenplum50Info
            {
                get
                {
                    return _greenplum50Info;
                }
            }

            /// <summary>
            /// The Greenplum4312 item.
            /// </summary>
            [RepositoryItem("bc650173-6ba2-4fad-9143-134c4b4d3593")]
            public virtual Ranorex.Unknown Greenplum4312
            {
                get
                {
                    return _greenplum4312Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Greenplum4312 item info.
            /// </summary>
            [RepositoryItemInfo("bc650173-6ba2-4fad-9143-134c4b4d3593")]
            public virtual RepoItemInfo Greenplum4312Info
            {
                get
                {
                    return _greenplum4312Info;
                }
            }

            /// <summary>
            /// The Informix1210 item.
            /// </summary>
            [RepositoryItem("f6382d4e-bc5c-411b-ae82-7b65ff2c0cdf")]
            public virtual Ranorex.TreeItem Informix1210
            {
                get
                {
                    return _informix1210Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Informix1210 item info.
            /// </summary>
            [RepositoryItemInfo("f6382d4e-bc5c-411b-ae82-7b65ff2c0cdf")]
            public virtual RepoItemInfo Informix1210Info
            {
                get
                {
                    return _informix1210Info;
                }
            }

            /// <summary>
            /// The Informix1170 item.
            /// </summary>
            [RepositoryItem("9684e933-b68d-4b42-93a7-2bc40e524ea1")]
            public virtual Ranorex.TreeItem Informix1170
            {
                get
                {
                    return _informix1170Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Informix1170 item info.
            /// </summary>
            [RepositoryItemInfo("9684e933-b68d-4b42-93a7-2bc40e524ea1")]
            public virtual RepoItemInfo Informix1170Info
            {
                get
                {
                    return _informix1170Info;
                }
            }

            /// <summary>
            /// The MariaDB item.
            /// </summary>
            [RepositoryItem("f96380ae-605b-4713-9452-d6d45b55a5e0")]
            public virtual Ranorex.TreeItem MariaDB
            {
                get
                {
                    return _mariadbInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The MariaDB item info.
            /// </summary>
            [RepositoryItemInfo("f96380ae-605b-4713-9452-d6d45b55a5e0")]
            public virtual RepoItemInfo MariaDBInfo
            {
                get
                {
                    return _mariadbInfo;
                }
            }

            /// <summary>
            /// The MongoDB341 item.
            /// </summary>
            [RepositoryItem("d96209e6-546a-46ae-8862-6e64bcafd706")]
            public virtual Ranorex.TreeItem MongoDB341
            {
                get
                {
                    return _mongodb341Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The MongoDB341 item info.
            /// </summary>
            [RepositoryItemInfo("d96209e6-546a-46ae-8862-6e64bcafd706")]
            public virtual RepoItemInfo MongoDB341Info
            {
                get
                {
                    return _mongodb341Info;
                }
            }

            /// <summary>
            /// The MongoDB321 item.
            /// </summary>
            [RepositoryItem("f46006da-8173-4ad0-93ae-1ba2488ead71")]
            public virtual Ranorex.TreeItem MongoDB321
            {
                get
                {
                    return _mongodb321Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The MongoDB321 item info.
            /// </summary>
            [RepositoryItemInfo("f46006da-8173-4ad0-93ae-1ba2488ead71")]
            public virtual RepoItemInfo MongoDB321Info
            {
                get
                {
                    return _mongodb321Info;
                }
            }

            /// <summary>
            /// The MySQL80 item.
            /// </summary>
            [RepositoryItem("1ea11b55-56ac-41f6-a396-99a59261cf39")]
            public virtual Ranorex.TreeItem MySQL80
            {
                get
                {
                    return _mysql80Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The MySQL80 item info.
            /// </summary>
            [RepositoryItemInfo("1ea11b55-56ac-41f6-a396-99a59261cf39")]
            public virtual RepoItemInfo MySQL80Info
            {
                get
                {
                    return _mysql80Info;
                }
            }

            /// <summary>
            /// The MySQL57 item.
            /// </summary>
            [RepositoryItem("af69ff7f-c42b-40b6-b521-f1466fc88fc2")]
            public virtual Ranorex.TreeItem MySQL57
            {
                get
                {
                    return _mysql57Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The MySQL57 item info.
            /// </summary>
            [RepositoryItemInfo("af69ff7f-c42b-40b6-b521-f1466fc88fc2")]
            public virtual RepoItemInfo MySQL57Info
            {
                get
                {
                    return _mysql57Info;
                }
            }
        }

        /// <summary>
        /// The QuaryAnalyzerWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("21f2cc24-0138-40c1-ad00-85cfc867d70f")]
        public partial class QuaryAnalyzerWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _queryboxInfo;
            RepoItemInfo _gridInfo;
            RepoItemInfo _newvaInfo;

            /// <summary>
            /// Creates a new QuaryAnalyzerWindow  folder.
            /// </summary>
            public QuaryAnalyzerWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("QuaryAnalyzerWindow", "/form[@title~'^Aqua\\ Data\\ Studio']", parentFolder, 30000, null, true, "21f2cc24-0138-40c1-ad00-85cfc867d70f", "")
            {
                _queryboxInfo = new RepoItemInfo(this, "QueryBox", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myInnerComponent']//container[@type='QueryPanel']/container[@name='panel']/?/?/container[@name='splitPane']//container[@type='EditorImpl$MyScrollPane']/container[6]/element[@type='EditorComponentImpl']", 30000, null, "953a742b-3728-4080-b6f9-3b7ff87b5364");
                _gridInfo = new RepoItemInfo(this, "Grid", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//container[@type='QueryPanel']//container[@name='splitPane']//tabpage[@title='Grid   ']", 30000, null, "91a5afb5-a619-4ec1-84e6-5fa047abd0fd");
                _newvaInfo = new RepoItemInfo(this, "NewVA", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//container[@type='QueryPanel']/container[@name='panel']/?/?/container[@name='splitPane']/?/?/container[@name='tabbedPane']/container[@name='_gridResultsView']//container[@type='ResultSetTableView$ResultGridsSplitPane']//container[@type='HorizontalLayoutPanel']/container[1]/menuitem[1]", 30000, null, "09def949-7530-4e58-bc88-d46981ca0e93");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("21f2cc24-0138-40c1-ad00-85cfc867d70f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("21f2cc24-0138-40c1-ad00-85cfc867d70f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The QueryBox item.
            /// </summary>
            [RepositoryItem("953a742b-3728-4080-b6f9-3b7ff87b5364")]
            public virtual Ranorex.Unknown QueryBox
            {
                get
                {
                    return _queryboxInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The QueryBox item info.
            /// </summary>
            [RepositoryItemInfo("953a742b-3728-4080-b6f9-3b7ff87b5364")]
            public virtual RepoItemInfo QueryBoxInfo
            {
                get
                {
                    return _queryboxInfo;
                }
            }

            /// <summary>
            /// The Grid item.
            /// </summary>
            [RepositoryItem("91a5afb5-a619-4ec1-84e6-5fa047abd0fd")]
            public virtual Ranorex.TabPage Grid
            {
                get
                {
                    return _gridInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Grid item info.
            /// </summary>
            [RepositoryItemInfo("91a5afb5-a619-4ec1-84e6-5fa047abd0fd")]
            public virtual RepoItemInfo GridInfo
            {
                get
                {
                    return _gridInfo;
                }
            }

            /// <summary>
            /// The NewVA item.
            /// </summary>
            [RepositoryItem("09def949-7530-4e58-bc88-d46981ca0e93")]
            public virtual Ranorex.MenuItem NewVA
            {
                get
                {
                    return _newvaInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The NewVA item info.
            /// </summary>
            [RepositoryItemInfo("09def949-7530-4e58-bc88-d46981ca0e93")]
            public virtual RepoItemInfo NewVAInfo
            {
                get
                {
                    return _newvaInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}