///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ADSAutomationPhaseIII.TC_10574
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TC10574Repo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("11c4f6c8-1d4e-4217-b2eb-1926bb15b259")]
    public partial class TC10574Repo : RepoGenBaseFolder
    {
        static TC10574Repo instance = new TC10574Repo();
        TC10574RepoFolders.SunAwtWindowAppFolder _sunawtwindow;
        TC10574RepoFolders.OptionsWindowAppFolder _optionswindow;
        TC10574RepoFolders.AbbrevationWindowAppFolder _abbrevationwindow;
        TC10574RepoFolders.ServersListAppFolder _serverslist;
        TC10574RepoFolders.QuaryAnalyzerWindowAppFolder _quaryanalyzerwindow;
        TC10574RepoFolders.QueryAnalyzerAppFolder _queryanalyzer;
        TC10574RepoFolders.FileModifiedAppFolder _filemodified;

        /// <summary>
        /// Gets the singleton class instance representing the TC10574Repo element repository.
        /// </summary>
        [RepositoryFolder("11c4f6c8-1d4e-4217-b2eb-1926bb15b259")]
        public static TC10574Repo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TC10574Repo() 
            : base("TC10574Repo", "/", null, 0, false, "11c4f6c8-1d4e-4217-b2eb-1926bb15b259", ".\\RepositoryImages\\TC10574Repo11c4f6c8.rximgres")
        {
            _sunawtwindow = new TC10574RepoFolders.SunAwtWindowAppFolder(this);
            _optionswindow = new TC10574RepoFolders.OptionsWindowAppFolder(this);
            _abbrevationwindow = new TC10574RepoFolders.AbbrevationWindowAppFolder(this);
            _serverslist = new TC10574RepoFolders.ServersListAppFolder(this);
            _quaryanalyzerwindow = new TC10574RepoFolders.QuaryAnalyzerWindowAppFolder(this);
            _queryanalyzer = new TC10574RepoFolders.QueryAnalyzerAppFolder(this);
            _filemodified = new TC10574RepoFolders.FileModifiedAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("11c4f6c8-1d4e-4217-b2eb-1926bb15b259")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SunAwtWindow folder.
        /// </summary>
        [RepositoryFolder("c3edb99e-6572-42f7-8b35-012be61bdeb6")]
        public virtual TC10574RepoFolders.SunAwtWindowAppFolder SunAwtWindow
        {
            get { return _sunawtwindow; }
        }

        /// <summary>
        /// The OptionsWindow folder.
        /// </summary>
        [RepositoryFolder("c87b273f-3cd9-499b-b213-fbdb10d37fe4")]
        public virtual TC10574RepoFolders.OptionsWindowAppFolder OptionsWindow
        {
            get { return _optionswindow; }
        }

        /// <summary>
        /// The AbbrevationWindow folder.
        /// </summary>
        [RepositoryFolder("7fc7df1e-b41e-4f9d-b2de-719c947fa50d")]
        public virtual TC10574RepoFolders.AbbrevationWindowAppFolder AbbrevationWindow
        {
            get { return _abbrevationwindow; }
        }

        /// <summary>
        /// The ServersList folder.
        /// </summary>
        [RepositoryFolder("074e9ce7-9035-4f66-9c1e-6128b4f5101b")]
        public virtual TC10574RepoFolders.ServersListAppFolder ServersList
        {
            get { return _serverslist; }
        }

        /// <summary>
        /// The QuaryAnalyzerWindow folder.
        /// </summary>
        [RepositoryFolder("21f2cc24-0138-40c1-ad00-85cfc867d70f")]
        public virtual TC10574RepoFolders.QuaryAnalyzerWindowAppFolder QuaryAnalyzerWindow
        {
            get { return _quaryanalyzerwindow; }
        }

        /// <summary>
        /// The QueryAnalyzer folder.
        /// </summary>
        [RepositoryFolder("f6b88477-0d52-45f6-b295-5d8cf5cea688")]
        public virtual TC10574RepoFolders.QueryAnalyzerAppFolder QueryAnalyzer
        {
            get { return _queryanalyzer; }
        }

        /// <summary>
        /// The FileModified folder.
        /// </summary>
        [RepositoryFolder("a5a26537-b61a-4329-abdc-90f948d192bf")]
        public virtual TC10574RepoFolders.FileModifiedAppFolder FileModified
        {
            get { return _filemodified; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class TC10574RepoFolders
    {
        /// <summary>
        /// The SunAwtWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("c3edb99e-6572-42f7-8b35-012be61bdeb6")]
        public partial class SunAwtWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _optionsInfo;
            RepoItemInfo _enterInfo;
            RepoItemInfo _tabInfo;
            RepoItemInfo _spaceInfo;
            RepoItemInfo _closetabInfo;
            RepoItemInfo _closealltabsInfo;

            /// <summary>
            /// Creates a new SunAwtWindow  folder.
            /// </summary>
            public SunAwtWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SunAwtWindow", "/form[@class='SunAwtWindow']", parentFolder, 30000, null, false, "c3edb99e-6572-42f7-8b35-012be61bdeb6", "")
            {
                _optionsInfo = new RepoItemInfo(this, "Options", ".//menuitem[@text='Options']", 30000, null, "2e871dfd-2a9b-4c98-bd0f-13bc0757e6f4");
                _enterInfo = new RepoItemInfo(this, "Enter", ".//container[@name='viewport']/list[@name='ComboBox.list']/listitem[@text='Enter']", 30000, null, "3d46484a-8935-4732-b22a-f4cf7bfb0a9c");
                _tabInfo = new RepoItemInfo(this, "Tab", ".//container[@name='viewport']/list[@name='ComboBox.list']/listitem[@text='Tab']", 30000, null, "68b780c1-1cd4-4672-ad7a-445b4ba71837");
                _spaceInfo = new RepoItemInfo(this, "Space", ".//container/list[@name='ComboBox.list']/listitem[@text='Space']", 30000, null, "b7798b1a-b16b-451a-8e2b-16c48c177d48");
                _closetabInfo = new RepoItemInfo(this, "CloseTab", ".//menuitem[@name='TabDocumentPane.close']", 30000, null, "eb500414-461b-4b47-ab8a-2c04c611db2b");
                _closealltabsInfo = new RepoItemInfo(this, "CloseAllTabs", ".//menuitem[@name='TabDocumentPane.closeAll']", 30000, null, "5b0bad73-9b95-4fbe-8c2b-3e3f8776a9ef");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c3edb99e-6572-42f7-8b35-012be61bdeb6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c3edb99e-6572-42f7-8b35-012be61bdeb6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Options item.
            /// </summary>
            [RepositoryItem("2e871dfd-2a9b-4c98-bd0f-13bc0757e6f4")]
            public virtual Ranorex.MenuItem Options
            {
                get
                {
                    return _optionsInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Options item info.
            /// </summary>
            [RepositoryItemInfo("2e871dfd-2a9b-4c98-bd0f-13bc0757e6f4")]
            public virtual RepoItemInfo OptionsInfo
            {
                get
                {
                    return _optionsInfo;
                }
            }

            /// <summary>
            /// The Enter item.
            /// </summary>
            [RepositoryItem("3d46484a-8935-4732-b22a-f4cf7bfb0a9c")]
            public virtual Ranorex.ListItem Enter
            {
                get
                {
                    return _enterInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Enter item info.
            /// </summary>
            [RepositoryItemInfo("3d46484a-8935-4732-b22a-f4cf7bfb0a9c")]
            public virtual RepoItemInfo EnterInfo
            {
                get
                {
                    return _enterInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("68b780c1-1cd4-4672-ad7a-445b4ba71837")]
            public virtual Ranorex.ListItem Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("68b780c1-1cd4-4672-ad7a-445b4ba71837")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The Space item.
            /// </summary>
            [RepositoryItem("b7798b1a-b16b-451a-8e2b-16c48c177d48")]
            public virtual Ranorex.ListItem Space
            {
                get
                {
                    return _spaceInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Space item info.
            /// </summary>
            [RepositoryItemInfo("b7798b1a-b16b-451a-8e2b-16c48c177d48")]
            public virtual RepoItemInfo SpaceInfo
            {
                get
                {
                    return _spaceInfo;
                }
            }

            /// <summary>
            /// The CloseTab item.
            /// </summary>
            [RepositoryItem("eb500414-461b-4b47-ab8a-2c04c611db2b")]
            public virtual Ranorex.MenuItem CloseTab
            {
                get
                {
                    return _closetabInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The CloseTab item info.
            /// </summary>
            [RepositoryItemInfo("eb500414-461b-4b47-ab8a-2c04c611db2b")]
            public virtual RepoItemInfo CloseTabInfo
            {
                get
                {
                    return _closetabInfo;
                }
            }

            /// <summary>
            /// The CloseAllTabs item.
            /// </summary>
            [RepositoryItem("5b0bad73-9b95-4fbe-8c2b-3e3f8776a9ef")]
            public virtual Ranorex.MenuItem CloseAllTabs
            {
                get
                {
                    return _closealltabsInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The CloseAllTabs item info.
            /// </summary>
            [RepositoryItemInfo("5b0bad73-9b95-4fbe-8c2b-3e3f8776a9ef")]
            public virtual RepoItemInfo CloseAllTabsInfo
            {
                get
                {
                    return _closealltabsInfo;
                }
            }
        }

        /// <summary>
        /// The OptionsWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("c87b273f-3cd9-499b-b213-fbdb10d37fe4")]
        public partial class OptionsWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _sqleditorInfo;
            RepoItemInfo _abbrevationInfo;
            RepoItemInfo _expandsymbolInfo;
            RepoItemInfo _expandedtextboxInfo;
            RepoItemInfo _triangleiconInfo;
            RepoItemInfo _okayInfo;
            RepoItemInfo _selectInfo;
            RepoItemInfo _closeInfo;
            RepoItemInfo _insertInfo;
            RepoItemInfo _createInfo;
            RepoItemInfo _removesymbolInfo;
            RepoItemInfo _columnsInfo;
            RepoItemInfo _upiconInfo;
            RepoItemInfo _downiconInfo;

            /// <summary>
            /// Creates a new OptionsWindow  folder.
            /// </summary>
            public OptionsWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OptionsWindow", "/form[@title='Options']", parentFolder, 30000, null, true, "c87b273f-3cd9-499b-b213-fbdb10d37fe4", "")
            {
                _sqleditorInfo = new RepoItemInfo(this, "SQLEditor", ".//container[1]/?/?/container[@name='mySplitter']//container[@type='SettingsTreeView$2']/tree[@name='myTree']/treeitem/treeitem[4]", 30000, null, "d721a24d-7320-436b-aee8-9b796160f606");
                _abbrevationInfo = new RepoItemInfo(this, "Abbrevation", ".//container[1]/?/?/container[@name='mySplitter']//container[@type='SettingsTreeView$2']/tree[@name='myTree']/treeitem/treeitem[4]/treeitem[3]", 30000, null, "0678f6f6-3615-4d38-b77f-f16dc7f7c16b");
                _expandsymbolInfo = new RepoItemInfo(this, "ExpandSymbol", ".//container[1]/?/?/container[@name='mySplitter']/container[3]/?/?/container[@name='myContent']//container[@type='CSplitPane']/container[1]/container[@name='abbreviationTablePanel']/?/?/container[@type='CommonActionsPanel']/container/element[1]", 30000, null, "4ce5c901-cdba-4298-8a38-25d9df420f17");
                _expandedtextboxInfo = new RepoItemInfo(this, "ExpandedTextBox", ".//container[1]/?/?/container[@name='mySplitter']/container[3]/?/?/container[@name='myContent']//container[@type='CSplitPane']/container[3]/?/?/container[@accessiblename='Expanded Text']/?/?/container[@type='PsiAwareTextEditorImpl$PsiAwareTextEditorComponent']/container/container[@type='JPanel']/?/?/container[@type='EditorImpl$MyScrollPane']/container[6]/element[@type='EditorComponentImpl']", 30000, null, "d2a6fb72-f663-4b87-8c58-f074328006ef");
                _triangleiconInfo = new RepoItemInfo(this, "TriangleIcon", ".//container[1]/?/?/container[@name='mySplitter']/container[3]/?/?/container[@name='myContent']//container[@type='CSplitPane']/container[3]/?/?/combobox[@name='expandOnCombo']/button[@text='']", 30000, null, "418efa6a-1c46-4bc9-b0ba-0d3cb0fb10a5");
                _okayInfo = new RepoItemInfo(this, "Okay", ".//container[2]/container[@type='JPanel']//button[@text='OK']", 30000, null, "1245c0e1-8ac3-46c3-b0da-fef9497c0b67");
                _selectInfo = new RepoItemInfo(this, "Select", ".//container[1]//container[@name='myContent']//container[@type='CSplitPane']/container[1]/container[@name='abbreviationTablePanel']/?/?/container[@name='scrollPaneTable']/container[1]/table[@name='mainTable']/row/cell[@text='select']", 30000, null, "1cb370c1-8daf-4e88-b087-4ca7d79e1da3");
                _closeInfo = new RepoItemInfo(this, "Close", ".//button[@accessiblename='Close']", 30000, null, "63182279-76c7-4d04-ab91-a9aec1415c7a");
                _insertInfo = new RepoItemInfo(this, "Insert", ".//container[1]//container[@name='myContent']//container[@type='CSplitPane']/container[1]/container[@name='abbreviationTablePanel']/?/?/container[@name='scrollPaneTable']/container[1]/table[@name='mainTable']/row/cell[@text='insert']", 30000, null, "4cdff5bc-4885-43ca-990d-dd49496a3497");
                _createInfo = new RepoItemInfo(this, "Create", ".//container[1]//container[@name='myContent']//container[@type='CSplitPane']/container[1]/container[@name='abbreviationTablePanel']/?/?/container[@name='scrollPaneTable']/container[1]/table[@name='mainTable']/row/cell[@text='create']", 30000, null, "40b5bf5b-2197-48f4-b614-b2d2e9863f9c");
                _removesymbolInfo = new RepoItemInfo(this, "RemoveSymbol", ".//container[1]/?/?/container[@name='mySplitter']/container[3]/?/?/container[@name='myContent']//container[@type='CSplitPane']/container[1]/container[@name='abbreviationTablePanel']/?/?/container[@type='CommonActionsPanel']/container/element[2]", 30000, null, "001a981a-cf4e-4570-86a5-659d4cf5e2cd");
                _columnsInfo = new RepoItemInfo(this, "Columns", ".//container[1]/?/?/container[@name='mySplitter']/container[3]/?/?/container[@name='myContent']//container[@name='abbreviationTablePanel']/?/?/container[@name='scrollPaneTable']/container[1]/table[@name='mainTable']/column[@text='Abbreviation']", 30000, null, "4501579d-cd60-4189-ac26-af38d327cda4");
                _upiconInfo = new RepoItemInfo(this, "UPIcon", ".//container[1]/?/?/container[@name='mySplitter']/container[3]/?/?/container[@name='myContent']//container[@type='CSplitPane']/container[1]/container[@name='abbreviationTablePanel']/?/?/container[@type='CommonActionsPanel']/container/element[3]", 30000, null, "4772c9df-0261-40ca-9c83-f7078dd86d52");
                _downiconInfo = new RepoItemInfo(this, "DownIcon", ".//container[1]/?/?/container[@name='mySplitter']/container[3]/?/?/container[@name='myContent']//container[@type='CSplitPane']/container[1]/container[@name='abbreviationTablePanel']/?/?/container[@type='CommonActionsPanel']/container/element[4]", 30000, null, "7d6c17d5-412b-4190-96f2-eb6a15d66d29");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c87b273f-3cd9-499b-b213-fbdb10d37fe4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c87b273f-3cd9-499b-b213-fbdb10d37fe4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SQLEditor item.
            /// </summary>
            [RepositoryItem("d721a24d-7320-436b-aee8-9b796160f606")]
            public virtual Ranorex.TreeItem SQLEditor
            {
                get
                {
                    return _sqleditorInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The SQLEditor item info.
            /// </summary>
            [RepositoryItemInfo("d721a24d-7320-436b-aee8-9b796160f606")]
            public virtual RepoItemInfo SQLEditorInfo
            {
                get
                {
                    return _sqleditorInfo;
                }
            }

            /// <summary>
            /// The Abbrevation item.
            /// </summary>
            [RepositoryItem("0678f6f6-3615-4d38-b77f-f16dc7f7c16b")]
            public virtual Ranorex.TreeItem Abbrevation
            {
                get
                {
                    return _abbrevationInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Abbrevation item info.
            /// </summary>
            [RepositoryItemInfo("0678f6f6-3615-4d38-b77f-f16dc7f7c16b")]
            public virtual RepoItemInfo AbbrevationInfo
            {
                get
                {
                    return _abbrevationInfo;
                }
            }

            /// <summary>
            /// The ExpandSymbol item.
            /// </summary>
            [RepositoryItem("4ce5c901-cdba-4298-8a38-25d9df420f17")]
            public virtual Ranorex.Unknown ExpandSymbol
            {
                get
                {
                    return _expandsymbolInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ExpandSymbol item info.
            /// </summary>
            [RepositoryItemInfo("4ce5c901-cdba-4298-8a38-25d9df420f17")]
            public virtual RepoItemInfo ExpandSymbolInfo
            {
                get
                {
                    return _expandsymbolInfo;
                }
            }

            /// <summary>
            /// The ExpandedTextBox item.
            /// </summary>
            [RepositoryItem("d2a6fb72-f663-4b87-8c58-f074328006ef")]
            public virtual Ranorex.Unknown ExpandedTextBox
            {
                get
                {
                    return _expandedtextboxInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ExpandedTextBox item info.
            /// </summary>
            [RepositoryItemInfo("d2a6fb72-f663-4b87-8c58-f074328006ef")]
            public virtual RepoItemInfo ExpandedTextBoxInfo
            {
                get
                {
                    return _expandedtextboxInfo;
                }
            }

            /// <summary>
            /// The TriangleIcon item.
            /// </summary>
            [RepositoryItem("418efa6a-1c46-4bc9-b0ba-0d3cb0fb10a5")]
            public virtual Ranorex.Button TriangleIcon
            {
                get
                {
                    return _triangleiconInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The TriangleIcon item info.
            /// </summary>
            [RepositoryItemInfo("418efa6a-1c46-4bc9-b0ba-0d3cb0fb10a5")]
            public virtual RepoItemInfo TriangleIconInfo
            {
                get
                {
                    return _triangleiconInfo;
                }
            }

            /// <summary>
            /// The Okay item.
            /// </summary>
            [RepositoryItem("1245c0e1-8ac3-46c3-b0da-fef9497c0b67")]
            public virtual Ranorex.Button Okay
            {
                get
                {
                    return _okayInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Okay item info.
            /// </summary>
            [RepositoryItemInfo("1245c0e1-8ac3-46c3-b0da-fef9497c0b67")]
            public virtual RepoItemInfo OkayInfo
            {
                get
                {
                    return _okayInfo;
                }
            }

            /// <summary>
            /// The Select item.
            /// </summary>
            [RepositoryItem("1cb370c1-8daf-4e88-b087-4ca7d79e1da3")]
            public virtual Ranorex.Cell Select
            {
                get
                {
                    return _selectInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Select item info.
            /// </summary>
            [RepositoryItemInfo("1cb370c1-8daf-4e88-b087-4ca7d79e1da3")]
            public virtual RepoItemInfo SelectInfo
            {
                get
                {
                    return _selectInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("63182279-76c7-4d04-ab91-a9aec1415c7a")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("63182279-76c7-4d04-ab91-a9aec1415c7a")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The Insert item.
            /// </summary>
            [RepositoryItem("4cdff5bc-4885-43ca-990d-dd49496a3497")]
            public virtual Ranorex.Cell Insert
            {
                get
                {
                    return _insertInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Insert item info.
            /// </summary>
            [RepositoryItemInfo("4cdff5bc-4885-43ca-990d-dd49496a3497")]
            public virtual RepoItemInfo InsertInfo
            {
                get
                {
                    return _insertInfo;
                }
            }

            /// <summary>
            /// The Create item.
            /// </summary>
            [RepositoryItem("40b5bf5b-2197-48f4-b614-b2d2e9863f9c")]
            public virtual Ranorex.Cell Create
            {
                get
                {
                    return _createInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Create item info.
            /// </summary>
            [RepositoryItemInfo("40b5bf5b-2197-48f4-b614-b2d2e9863f9c")]
            public virtual RepoItemInfo CreateInfo
            {
                get
                {
                    return _createInfo;
                }
            }

            /// <summary>
            /// The RemoveSymbol item.
            /// </summary>
            [RepositoryItem("001a981a-cf4e-4570-86a5-659d4cf5e2cd")]
            public virtual Ranorex.Unknown RemoveSymbol
            {
                get
                {
                    return _removesymbolInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The RemoveSymbol item info.
            /// </summary>
            [RepositoryItemInfo("001a981a-cf4e-4570-86a5-659d4cf5e2cd")]
            public virtual RepoItemInfo RemoveSymbolInfo
            {
                get
                {
                    return _removesymbolInfo;
                }
            }

            /// <summary>
            /// The Columns item.
            /// </summary>
            [RepositoryItem("4501579d-cd60-4189-ac26-af38d327cda4")]
            public virtual Ranorex.Column Columns
            {
                get
                {
                    return _columnsInfo.CreateAdapter<Ranorex.Column>(true);
                }
            }

            /// <summary>
            /// The Columns item info.
            /// </summary>
            [RepositoryItemInfo("4501579d-cd60-4189-ac26-af38d327cda4")]
            public virtual RepoItemInfo ColumnsInfo
            {
                get
                {
                    return _columnsInfo;
                }
            }

            /// <summary>
            /// The UPIcon item.
            /// </summary>
            [RepositoryItem("4772c9df-0261-40ca-9c83-f7078dd86d52")]
            public virtual Ranorex.Unknown UPIcon
            {
                get
                {
                    return _upiconInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The UPIcon item info.
            /// </summary>
            [RepositoryItemInfo("4772c9df-0261-40ca-9c83-f7078dd86d52")]
            public virtual RepoItemInfo UPIconInfo
            {
                get
                {
                    return _upiconInfo;
                }
            }

            /// <summary>
            /// The DownIcon item.
            /// </summary>
            [RepositoryItem("7d6c17d5-412b-4190-96f2-eb6a15d66d29")]
            public virtual Ranorex.Unknown DownIcon
            {
                get
                {
                    return _downiconInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The DownIcon item info.
            /// </summary>
            [RepositoryItemInfo("7d6c17d5-412b-4190-96f2-eb6a15d66d29")]
            public virtual RepoItemInfo DownIconInfo
            {
                get
                {
                    return _downiconInfo;
                }
            }
        }

        /// <summary>
        /// The AbbrevationWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("7fc7df1e-b41e-4f9d-b2de-719c947fa50d")]
        public partial class AbbrevationWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textboxInfo;
            RepoItemInfo _okaybuttonInfo;

            /// <summary>
            /// Creates a new AbbrevationWindow  folder.
            /// </summary>
            public AbbrevationWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AbbrevationWindow", "/form[@title='New Abbreviation']", parentFolder, 30000, null, true, "7fc7df1e-b41e-4f9d-b2de-719c947fa50d", "")
            {
                _textboxInfo = new RepoItemInfo(this, "TextBox", ".//container[1]/?/?/text[@type='JBTextField']", 30000, null, "0f4cc319-3c44-48c6-bc25-172ec0915bda");
                _okaybuttonInfo = new RepoItemInfo(this, "OkayButton", ".//container[2]/container[@type='JPanel']//button[@text='OK']", 30000, null, "9258ca9a-468f-44f8-89a9-a566e307b913");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7fc7df1e-b41e-4f9d-b2de-719c947fa50d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7fc7df1e-b41e-4f9d-b2de-719c947fa50d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TextBox item.
            /// </summary>
            [RepositoryItem("0f4cc319-3c44-48c6-bc25-172ec0915bda")]
            public virtual Ranorex.Text TextBox
            {
                get
                {
                    return _textboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextBox item info.
            /// </summary>
            [RepositoryItemInfo("0f4cc319-3c44-48c6-bc25-172ec0915bda")]
            public virtual RepoItemInfo TextBoxInfo
            {
                get
                {
                    return _textboxInfo;
                }
            }

            /// <summary>
            /// The OkayButton item.
            /// </summary>
            [RepositoryItem("9258ca9a-468f-44f8-89a9-a566e307b913")]
            public virtual Ranorex.Button OkayButton
            {
                get
                {
                    return _okaybuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OkayButton item info.
            /// </summary>
            [RepositoryItemInfo("9258ca9a-468f-44f8-89a9-a566e307b913")]
            public virtual RepoItemInfo OkayButtonInfo
            {
                get
                {
                    return _okaybuttonInfo;
                }
            }
        }

        /// <summary>
        /// The ServersListAppFolder folder.
        /// </summary>
        [RepositoryFolder("074e9ce7-9035-4f66-9c1e-6128b4f5101b")]
        public partial class ServersListAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _localdbserverstreeitemInfo;
            RepoItemInfo _filemenuInfo;

            /// <summary>
            /// Creates a new ServersList  folder.
            /// </summary>
            public ServersListAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ServersList", "/form[@title~'^Aqua Data Studio']", parentFolder, 30000, null, true, "074e9ce7-9035-4f66-9c1e-6128b4f5101b", "")
            {
                _localdbserverstreeitemInfo = new RepoItemInfo(this, "LocalDBServersTreeItem", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//container[@name='viewport']/tree[@name='schemaTree']/?/?/treeitem[@text='Local Database Servers']", 30000, null, "0f6e214a-25ee-4eaa-81ac-a97c7eb5ef44");
                _filemenuInfo = new RepoItemInfo(this, "FileMenu", ".//menuitem[@text='File']", 30000, null, "da992c0f-dfcc-4c8a-a60b-60218253b432");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("074e9ce7-9035-4f66-9c1e-6128b4f5101b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("074e9ce7-9035-4f66-9c1e-6128b4f5101b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LocalDBServersTreeItem item.
            /// </summary>
            [RepositoryItem("0f6e214a-25ee-4eaa-81ac-a97c7eb5ef44")]
            public virtual Ranorex.TreeItem LocalDBServersTreeItem
            {
                get
                {
                    return _localdbserverstreeitemInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The LocalDBServersTreeItem item info.
            /// </summary>
            [RepositoryItemInfo("0f6e214a-25ee-4eaa-81ac-a97c7eb5ef44")]
            public virtual RepoItemInfo LocalDBServersTreeItemInfo
            {
                get
                {
                    return _localdbserverstreeitemInfo;
                }
            }

            /// <summary>
            /// The FileMenu item.
            /// </summary>
            [RepositoryItem("da992c0f-dfcc-4c8a-a60b-60218253b432")]
            public virtual Ranorex.MenuItem FileMenu
            {
                get
                {
                    return _filemenuInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The FileMenu item info.
            /// </summary>
            [RepositoryItemInfo("da992c0f-dfcc-4c8a-a60b-60218253b432")]
            public virtual RepoItemInfo FileMenuInfo
            {
                get
                {
                    return _filemenuInfo;
                }
            }
        }

        /// <summary>
        /// The QuaryAnalyzerWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("21f2cc24-0138-40c1-ad00-85cfc867d70f")]
        public partial class QuaryAnalyzerWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _queryboxInfo;

            /// <summary>
            /// Creates a new QuaryAnalyzerWindow  folder.
            /// </summary>
            public QuaryAnalyzerWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("QuaryAnalyzerWindow", "/form[@title~'^Aqua\\ Data\\ Studio']", parentFolder, 30000, null, true, "21f2cc24-0138-40c1-ad00-85cfc867d70f", "")
            {
                _queryboxInfo = new RepoItemInfo(this, "QueryBox", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myInnerComponent']//container[@type='QueryPanel']/container[@name='panel']/?/?/container[@name='splitPane']//container[@type='EditorImpl$MyScrollPane']/container[6]/element[@type='EditorComponentImpl']", 30000, null, "953a742b-3728-4080-b6f9-3b7ff87b5364");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("21f2cc24-0138-40c1-ad00-85cfc867d70f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("21f2cc24-0138-40c1-ad00-85cfc867d70f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The QueryBox item.
            /// </summary>
            [RepositoryItem("953a742b-3728-4080-b6f9-3b7ff87b5364")]
            public virtual Ranorex.Unknown QueryBox
            {
                get
                {
                    return _queryboxInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The QueryBox item info.
            /// </summary>
            [RepositoryItemInfo("953a742b-3728-4080-b6f9-3b7ff87b5364")]
            public virtual RepoItemInfo QueryBoxInfo
            {
                get
                {
                    return _queryboxInfo;
                }
            }
        }

        /// <summary>
        /// The QueryAnalyzerAppFolder folder.
        /// </summary>
        [RepositoryFolder("f6b88477-0d52-45f6-b295-5d8cf5cea688")]
        public partial class QueryAnalyzerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _qacombotextboxInfo;
            RepoItemInfo _tab2qacombotextboxInfo;
            RepoItemInfo _tabInfo;
            RepoItemInfo _schemaqacombotextboxInfo;
            RepoItemInfo _tab2schemaqacombotextboxInfo;
            RepoItemInfo _tabcontainerInfo;

            /// <summary>
            /// Creates a new QueryAnalyzer  folder.
            /// </summary>
            public QueryAnalyzerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("QueryAnalyzer", "/form[@title~'^Aqua\\ Data\\ Studio']", parentFolder, 30000, null, true, "f6b88477-0d52-45f6-b295-5d8cf5cea688", "")
            {
                _qacombotextboxInfo = new RepoItemInfo(this, "QAComboTextbox", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']/?/?/container[1]/container[2]//container[@name='panelBar']//combobox[@name='databaseField']/text[@type='BasicComboBoxEditor$BorderlessTextField']", 30000, null, "09d3daa1-1798-48ca-99ca-306a7b1572fe");
                _tab2qacombotextboxInfo = new RepoItemInfo(this, "Tab2QAComboTextbox", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']/?/?/container[1]/container[3]//container[@name='panelBar']//combobox[@name='databaseField']/text[@type='BasicComboBoxEditor$BorderlessTextField']", 30000, null, "2e185ac3-4ea0-42db-b67b-2eebff89eb85");
                _tabInfo = new RepoItemInfo(this, "Tab", ".//container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//tabpage", 30000, null, "e2c06e88-20ad-4410-be03-61eeb00e94dd");
                _schemaqacombotextboxInfo = new RepoItemInfo(this, "SchemaQAComboTextbox", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//container[@type='QueryPanel']//container[@name='schemaComboPanel']/combobox[@name='schemaCombo']/text[@type='BasicComboBoxEditor$BorderlessTextField']", 30000, null, "92695ac7-b5a3-4868-9f78-b347027a7d80");
                _tab2schemaqacombotextboxInfo = new RepoItemInfo(this, "Tab2SchemaQAComboTextbox", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']/?/?/container[1]/container[3]//container[@name='schemaComboPanel']/combobox[@name='schemaCombo']/text[@type='BasicComboBoxEditor$BorderlessTextField']", 30000, null, "35c96d7a-7965-4c2a-a10e-ba6ad010759d");
                _tabcontainerInfo = new RepoItemInfo(this, "TabContainer", ".//container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']", 30000, null, "28f098d2-0f72-48ab-8e8a-dfef47934a3c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f6b88477-0d52-45f6-b295-5d8cf5cea688")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f6b88477-0d52-45f6-b295-5d8cf5cea688")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The QAComboTextbox item.
            /// </summary>
            [RepositoryItem("09d3daa1-1798-48ca-99ca-306a7b1572fe")]
            public virtual Ranorex.Text QAComboTextbox
            {
                get
                {
                    return _qacombotextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The QAComboTextbox item info.
            /// </summary>
            [RepositoryItemInfo("09d3daa1-1798-48ca-99ca-306a7b1572fe")]
            public virtual RepoItemInfo QAComboTextboxInfo
            {
                get
                {
                    return _qacombotextboxInfo;
                }
            }

            /// <summary>
            /// The Tab2QAComboTextbox item.
            /// </summary>
            [RepositoryItem("2e185ac3-4ea0-42db-b67b-2eebff89eb85")]
            public virtual Ranorex.Text Tab2QAComboTextbox
            {
                get
                {
                    return _tab2qacombotextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Tab2QAComboTextbox item info.
            /// </summary>
            [RepositoryItemInfo("2e185ac3-4ea0-42db-b67b-2eebff89eb85")]
            public virtual RepoItemInfo Tab2QAComboTextboxInfo
            {
                get
                {
                    return _tab2qacombotextboxInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("e2c06e88-20ad-4410-be03-61eeb00e94dd")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("e2c06e88-20ad-4410-be03-61eeb00e94dd")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The SchemaQAComboTextbox item.
            /// </summary>
            [RepositoryItem("92695ac7-b5a3-4868-9f78-b347027a7d80")]
            public virtual Ranorex.Text SchemaQAComboTextbox
            {
                get
                {
                    return _schemaqacombotextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SchemaQAComboTextbox item info.
            /// </summary>
            [RepositoryItemInfo("92695ac7-b5a3-4868-9f78-b347027a7d80")]
            public virtual RepoItemInfo SchemaQAComboTextboxInfo
            {
                get
                {
                    return _schemaqacombotextboxInfo;
                }
            }

            /// <summary>
            /// The Tab2SchemaQAComboTextbox item.
            /// </summary>
            [RepositoryItem("35c96d7a-7965-4c2a-a10e-ba6ad010759d")]
            public virtual Ranorex.Text Tab2SchemaQAComboTextbox
            {
                get
                {
                    return _tab2schemaqacombotextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Tab2SchemaQAComboTextbox item info.
            /// </summary>
            [RepositoryItemInfo("35c96d7a-7965-4c2a-a10e-ba6ad010759d")]
            public virtual RepoItemInfo Tab2SchemaQAComboTextboxInfo
            {
                get
                {
                    return _tab2schemaqacombotextboxInfo;
                }
            }

            /// <summary>
            /// The TabContainer item.
            /// </summary>
            [RepositoryItem("28f098d2-0f72-48ab-8e8a-dfef47934a3c")]
            public virtual Ranorex.Container TabContainer
            {
                get
                {
                    return _tabcontainerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The TabContainer item info.
            /// </summary>
            [RepositoryItemInfo("28f098d2-0f72-48ab-8e8a-dfef47934a3c")]
            public virtual RepoItemInfo TabContainerInfo
            {
                get
                {
                    return _tabcontainerInfo;
                }
            }
        }

        /// <summary>
        /// The FileModifiedAppFolder folder.
        /// </summary>
        [RepositoryFolder("a5a26537-b61a-4329-abdc-90f948d192bf")]
        public partial class FileModifiedAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _discardInfo;

            /// <summary>
            /// Creates a new FileModified  folder.
            /// </summary>
            public FileModifiedAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FileModified", "/form[@title='File Modified']", parentFolder, 30000, null, true, "a5a26537-b61a-4329-abdc-90f948d192bf", "")
            {
                _discardInfo = new RepoItemInfo(this, "Discard", ".//container[@name='OptionPane.buttonArea']/button[@text='Discard']", 30000, null, "243099b6-7ad3-4178-aef8-eb5a701d4d4b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a5a26537-b61a-4329-abdc-90f948d192bf")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a5a26537-b61a-4329-abdc-90f948d192bf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Discard item.
            /// </summary>
            [RepositoryItem("243099b6-7ad3-4178-aef8-eb5a701d4d4b")]
            public virtual Ranorex.Button Discard
            {
                get
                {
                    return _discardInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Discard item info.
            /// </summary>
            [RepositoryItemInfo("243099b6-7ad3-4178-aef8-eb5a701d4d4b")]
            public virtual RepoItemInfo DiscardInfo
            {
                get
                {
                    return _discardInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}